'use strict';
const {
  EmbedBuilder,ActionRowBuilder,ButtonBuilder,ButtonStyle,ChannelType,PermissionFlagsBits,
  ModalBuilder,TextInputBuilder,TextInputStyle,MessageFlags
}=require('discord.js');
const store=require('./sharedStore');
const {featureAllowed,limitFor}=require('./planPolicy');
const logs=require('./serverLogs');

let client=null;
let getSiteConfig=async()=>store.getGlobalConfig();
let getHomeGuildId=()=>'';
const voiceOwners=new Map();
const missionLocks=new Set();
const robberyLocks=new Set();
let tickTimer=null;

const EQUIPMENT={
  mask:{label:'🎭 قناع افتراضي',key:'mask',max:20},
  hacking:{label:'💻 جهاز اختراق',key:'hacking',max:3},
  drill:{label:'🛠️ مثقاب خزنة',key:'drill',max:3},
  radio:{label:'📻 جهاز اتصال',key:'radio',max:5},
  car:{label:'🚗 سيارة هروب',key:'car',max:2}
};

function featureOn(cfg,site,key){return Boolean(cfg?.features?.[key]!==false&&featureAllowed(site,cfg,key));}
function color(cfg){const n=parseInt(String(cfg?.branding?.color||'#7c3aed').replace('#',''),16);return Number.isFinite(n)?n:0x7c3aed;}
function currency(cfg){return `${cfg?.currency?.emoji||'🪙'} ${cfg?.currency?.name||'ZOM'}`;}
function isAdmin(i){return Boolean(i?.memberPermissions?.has(PermissionFlagsBits.ManageGuild)||i?.memberPermissions?.has(PermissionFlagsBits.Administrator));}
function safeName(v='gang'){return String(v||'gang').trim().replace(/[\s_]+/g,'-').replace(/[^\p{L}\p{N}-]/gu,'').replace(/-+/g,'-').slice(0,80)||'gang';}
function normalizeAnswer(s){return String(s||'').trim().toLowerCase().replace(/[أإآ]/g,'ا').replace(/ة/g,'ه').replace(/ى/g,'ي').replace(/\s+/g,' ');}
function randomInt(min,max){return Math.floor(Math.random()*(max-min+1))+min;}
function pick(arr){return arr[Math.floor(Math.random()*arr.length)];}
function format(n){return Math.max(0,Math.floor(Number(n)||0)).toLocaleString('en-US');}
async function ephemeral(i,content){const payload=typeof content==='string'?{content}:{...content};payload.flags=MessageFlags.Ephemeral;if(i.deferred)return i.editReply(payload);if(i.replied)return i.followUp(payload);return i.reply(payload);}

async function gangState(gid){const x=await store.data(gid,'gangs-public.json',{gangs:{},membership:{}});x.gangs=x.gangs||{};x.membership=x.membership||{};return x;}
async function saveGangState(gid,x){return store.saveData(gid,'gangs-public.json',x);}
async function currentGang(gid,uid){const state=await gangState(gid),id=state.membership[uid];return{state,id,gang:id?state.gangs[id]:null};}
function leaderOrDeputy(g,uid){return Boolean(g&&(g.leaderId===uid||(g.deputies||[]).includes(uid)));}
function gangEmbed(cfg,g){return new EmbedBuilder().setColor(color(cfg)).setTitle(`🏴 ${g.name}`).addFields(
  {name:'القائد',value:`<@${g.leaderId}>`,inline:true},
  {name:'الخزنة',value:`${format(g.bank)} ${currency(cfg)}`,inline:true},
  {name:'السمعة',value:`${format(g.reputation||0)}`,inline:true},
  {name:`الأعضاء (${g.members?.length||0})`,value:(g.members||[]).map(id=>`${(g.deputies||[]).includes(id)?'⭐ ':''}<@${id}>`).join('\n')||'—'}
).setFooter({text:'ZOMBI Gangs'});}

async function createGangResources(i,cfg,name){
  const role=await i.guild.roles.create({name:`🏴 ${name}`.slice(0,100),color:cfg.gangs?.roleColor||'#2b2d31',reason:`ZOMBI gang ${name}`});
  try{
    const overwrites=[
      {id:i.guild.id,deny:[PermissionFlagsBits.ViewChannel]},
      {id:role.id,allow:[PermissionFlagsBits.ViewChannel,PermissionFlagsBits.SendMessages,PermissionFlagsBits.ReadMessageHistory,PermissionFlagsBits.EmbedLinks,PermissionFlagsBits.AttachFiles]}
    ];
    const ch=await i.guild.channels.create({name:`gang-${safeName(name)}`,type:ChannelType.GuildText,parent:cfg.channels?.gangCategory||null,permissionOverwrites:overwrites,reason:`ZOMBI gang ${name}`});
    return{role,ch};
  }catch(e){await role.delete('Rollback gang creation').catch(()=>{});throw e;}
}
async function deleteGangResources(guild,g){
  if(g?.channelId){const ch=guild.channels.cache.get(g.channelId)||await guild.channels.fetch(g.channelId).catch(()=>null);await ch?.delete('ZOMBI gang deleted').catch(()=>{});}
  if(g?.roleId){const role=guild.roles.cache.get(g.roleId)||await guild.roles.fetch(g.roleId).catch(()=>null);await role?.delete('ZOMBI gang deleted').catch(()=>{});}
}
async function memberRole(guild,g,uid,add=true){if(!g?.roleId)return;const m=await guild.members.fetch(uid).catch(()=>null);if(!m)return;try{if(add)await m.roles.add(g.roleId,'ZOMBI gang membership');else await m.roles.remove(g.roleId,'ZOMBI gang membership');}catch{}}

async function createGang(i,cfg,site,name){
  if(!featureOn(cfg,site,'gangs'))return ephemeral(i,'❌ نظام العصابات غير متاح لهذه الخطة.');
  const gid=i.guild.id,uid=i.user.id,{state,gang}=await currentGang(gid,uid);if(gang)return ephemeral(i,'❌ أنت داخل عصابة بالفعل.');
  const clean=String(name||'').trim().slice(0,40);if(clean.length<2)return ephemeral(i,'❌ اكتب اسم عصابة صحيح.');
  const cost=Math.max(0,Number(cfg.gangs?.createCost||0)),u=await store.getUser(gid,uid);if(u.balance<cost)return ephemeral(i,`❌ إنشاء العصابة يحتاج **${format(cost)} ${currency(cfg)}**.`);
  const {role,ch}=await createGangResources(i,cfg,clean);
  if(cost)await store.updateUser(gid,uid,x=>x.balance-=cost);
  const id=`g_${Date.now().toString(36)}_${Math.random().toString(36).slice(2,6)}`;
  const g={id,name:clean,leaderId:uid,deputies:[],members:[uid],bank:0,reputation:0,level:1,roleId:role.id,channelId:ch.id,equipment:{},createdAt:Date.now(),lastMissionAt:0,missionsCompleted:0,missionsFailed:0,robberiesWon:0,robberiesFailed:0,activeMission:null};
  state.gangs[id]=g;state.membership[uid]=id;await saveGangState(gid,state);await memberRole(i.guild,g,uid,true);
  await ch.send({embeds:[new EmbedBuilder().setColor(color(cfg)).setTitle(`🏴 أهلًا بعصابة ${clean}`).setDescription(`هذا الشات **خاص بالعصابة**.\nالقائد: <@${uid}>\nاستخدموا \`/gang mission\` للمهمات و\`/gang equipment\` لمعدات سرقة البنك.`)]}).catch(()=>{});
  await logs.write(i.guild,'🏴 إنشاء عصابة',`الاسم: ${clean}\nالقائد: ${i.user.tag} (${uid})\nالروم: <#${ch.id}>\nالرتبة: ${role.name} (${role.id})`,'gangs').catch(()=>{});
  return ephemeral(i,`✅ تم إنشاء **${clean}** وإنشاء الشات الخاص ${ch}.`);
}

async function acceptGangInvite(i,cfg,site){
  if(!featureOn(cfg,site,'gangs'))return ephemeral(i,'❌ نظام العصابات غير متاح.');
  const parts=i.customId.split(':'),gangId=parts[3],targetId=parts[4];if(i.user.id!==targetId)return ephemeral(i,'❌ هذه الدعوة ليست لك.');
  const state=await gangState(i.guild.id),g=state.gangs[gangId];if(!g)return ephemeral(i,'❌ العصابة لم تعد موجودة.');if(state.membership[targetId])return ephemeral(i,'❌ أنت داخل عصابة بالفعل.');
  const max=Math.min(Number(cfg.gangs?.maxMembers||7),limitFor(site,cfg,'gangMembers'));if((g.members||[]).length>=max)return ephemeral(i,'❌ العصابة ممتلئة.');
  g.members.push(targetId);state.membership[targetId]=gangId;await saveGangState(i.guild.id,state);await memberRole(i.guild,g,targetId,true);await i.update({content:`✅ ${i.user} انضم إلى **${g.name}**.`,components:[]}).catch(()=>{});const ch=i.guild.channels.cache.get(g.channelId);await ch?.send(`👋 أهلًا ${i.user} في **${g.name}**!`).catch(()=>{});await logs.write(i.guild,'🏴 انضمام للعصابة',`العضو: ${i.user.tag} (${targetId})\nالعصابة: ${g.name} (${g.id})`,'gangs').catch(()=>{});return true;
}

function missionTemplatesDefault(){return[
  {id:'convoy',enabled:true,name:'📦 القافلة المفقودة',description:'استعيدوا شحنة العصابة عبر سلسلة تحديات.',difficulty:'hard',minParticipants:2,steps:['تحليل سجل المسار','فك رمز الحاوية','حراسة نقطة الاستلام']},
  {id:'signal',enabled:true,name:'🛰️ تعقب الإشارة',description:'تعقبوا إشارة متحركة وأكملوا التحقق الجماعي.',difficulty:'elite',minParticipants:2,steps:['فك تردد البداية','مطابقة رمز التتبع','حراسة الإشارة']},
  {id:'vault',enabled:true,name:'🔐 الصندوق الأسود',description:'حلوا أقفالًا افتراضية قبل انتهاء الوقت.',difficulty:'legendary',minParticipants:2,steps:['القفل الأول','رمز التحقق','تأكيد الفريق']}
];}
async function missionTemplates(gid){const raw=await store.data(gid,'gang-missions.json',missionTemplatesDefault());return Array.isArray(raw)&&raw.length?raw:missionTemplatesDefault();}
function missionReward(cfg,difficulty){const min=Math.max(0,Number(cfg.gangs?.missionRewardMin||0)),max=Math.max(min,Number(cfg.gangs?.missionRewardMax||min)),base=randomInt(min,max),mult=difficulty==='legendary'?1.55:difficulty==='elite'?1.3:1.1;return Math.round(base*mult);}
function missionChallenge(type){if(type==='math'){const a=randomInt(20,90),b=randomInt(10,70);return{question:`احسب: ${a} + ${b}`,answer:String(a+b)};}const code=`ZOM-${randomInt(1000,9999)}`;return{question:`اكتب الرمز بالضبط: ${code}`,answer:code};}
function missionCurrent(m){return m?.steps?.find(s=>!s.completed)||null;}
function missionPayload(cfg,g){const m=g.activeMission;if(!m)return{content:'⏳ لا توجد مهمة نشطة.',components:[]};const step=missionCurrent(m);const status=m.status==='open'?'🟡 التسجيل':m.status==='running'?'🔴 قيد التنفيذ':'⚫ منتهية';const lines=m.steps.map(s=>`${s.completed?'✅':'⏳'} **${s.label}**${s.assignedUserId?` — <@${s.assignedUserId}>`:''}${s.type==='voice'&&!s.completed?`\n↳ 🎙️ المطلوب: ${s.requiredUserIds.map(id=>`<@${id}>`).join(' و ')} في نفس الفويس **${s.requiredSeconds}ث**`:''}${s.challenge&&!s.completed&&s.type!=='voice'?`\n↳ ${s.challenge.question}`:''}`).join('\n');const rows=[];
  if(m.status==='open')rows.push(new ActionRowBuilder().addComponents(
    new ButtonBuilder().setCustomId(`pub:gm:join:${g.id}`).setLabel('انضم للمهمة').setEmoji('➕').setStyle(ButtonStyle.Success),
    new ButtonBuilder().setCustomId(`pub:gm:leave:${g.id}`).setLabel('مغادرة').setStyle(ButtonStyle.Secondary),
    new ButtonBuilder().setCustomId(`pub:gm:start:${g.id}`).setLabel('بدء المهمة').setEmoji('▶️').setStyle(ButtonStyle.Primary)
  ));
  return{embeds:[new EmbedBuilder().setColor(color(cfg)).setTitle(`🎯 ${m.name}`).setDescription(`${m.description||''}\n\n${status}\n👥 المشاركون (${m.participants.length}/${m.minParticipants}+): ${m.participants.map(id=>`<@${id}>`).join('، ')||'—'}\n💰 المكافأة: **${format(m.reward)} ${currency(cfg)}**\n⏳ تنتهي <t:${Math.floor(m.expiresAt/1000)}:R>\n\n${lines||'بانتظار بدء المراحل.'}`)],components:rows};}
async function missionMessage(guild,g,cfg){const ch=guild.channels.cache.get(g.channelId)||await guild.channels.fetch(g.channelId).catch(()=>null);if(!ch?.isTextBased())return null;let msg=null;if(g.activeMission?.messageId)msg=await ch.messages.fetch(g.activeMission.messageId).catch(()=>null);if(msg){await msg.edit(missionPayload(cfg,g)).catch(()=>{});return msg;}msg=await ch.send(missionPayload(cfg,g));if(g.activeMission)g.activeMission.messageId=msg.id;return msg;}
async function startMission(i,cfg,site,g,state){
  if(!featureOn(cfg,site,'gangMissions')||cfg.gangs?.missionsEnabled===false)return ephemeral(i,'❌ مهمات العصابات غير متاحة أو معطلة.');if(!leaderOrDeputy(g,i.user.id))return ephemeral(i,'❌ القائد أو النائب فقط يستطيع فتح مهمة.');if(g.activeMission)return ephemeral(i,'❌ عندكم مهمة نشطة بالفعل.');
  const now=Date.now(),cd=Math.max(1,Number(cfg.gangs?.missionCooldownMinutes||240))*60000;if(now-Number(g.lastMissionAt||0)<cd)return ephemeral(i,`⏳ المهمة التالية <t:${Math.floor((Number(g.lastMissionAt)+cd)/1000)}:R>.`);
  const templates=(await missionTemplates(i.guild.id)).filter(x=>x.enabled!==false).slice(0,limitFor(site,cfg,'gangMissionTemplates'));if(!templates.length)return ephemeral(i,'❌ لا توجد قوالب مهمات مفعلة من الداشبورد.');const t=pick(templates),min=Math.max(2,Math.min(g.members.length,Number(t.minParticipants||2)));if(g.members.length<min)return ephemeral(i,`❌ تحتاج العصابة **${min}** أعضاء على الأقل.`);
  g.activeMission={id:`m_${Date.now().toString(36)}`,templateId:t.id,name:t.name,description:t.description,difficulty:t.difficulty||'hard',status:'open',minParticipants:min,participants:[i.user.id],reward:missionReward(cfg,t.difficulty),createdAt:now,expiresAt:now+Math.max(5,Number(cfg.gangs?.missionDurationMinutes||30))*60000,steps:(Array.isArray(t.steps)&&t.steps.length?t.steps:['تحدي الشات','حراسة الفويس','التأكيد النهائي']).slice(0,5).map((label,index)=>({index,label,type:'',assignedUserId:null,requiredUserIds:[],requiredSeconds:0,challenge:null,attempts:0,completed:false,voiceStartedAt:0})),messageId:''};
  await saveGangState(i.guild.id,state);const msg=await missionMessage(i.guild,g,cfg);await saveGangState(i.guild.id,state);await logs.write(i.guild,'🎯 فتح مهمة عصابة',`العصابة: ${g.name} (${g.id})\nالمهمة: ${g.activeMission.name}\nالمكافأة: ${format(g.activeMission.reward)} ${currency(cfg)}\nبواسطة: ${i.user.tag}`,'gangs').catch(()=>{});return ephemeral(i,msg?`🎯 تم فتح المهمة في ${msg.channel}.`:'🎯 تم فتح المهمة.');
}
function prepareMission(g,cfg){const m=g.activeMission,parts=[...m.participants];m.status='running';m.steps.forEach((s,idx)=>{if(idx===1&&parts.length>=2){s.type='voice';s.requiredUserIds=parts.slice(0,2);s.requiredSeconds=Math.max(10,Number(cfg.gangs?.missionVoiceSeconds||60));}else{s.type=idx%2===0?'code':'math';s.assignedUserId=parts[idx%parts.length];s.challenge=missionChallenge(s.type);}});}
async function completeMission(guild,g,state,cfg,success,reason=''){
  if(missionLocks.has(g.id))return;missionLocks.add(g.id);try{const m=g.activeMission;if(!m)return;if(success){g.bank=Number(g.bank||0)+Number(m.reward||0);g.missionsCompleted=Number(g.missionsCompleted||0)+1;g.reputation=Number(g.reputation||0)+50;}else g.missionsFailed=Number(g.missionsFailed||0)+1;g.lastMissionAt=Date.now();const ch=guild.channels.cache.get(g.channelId)||await guild.channels.fetch(g.channelId).catch(()=>null),msg=m.messageId?await ch?.messages.fetch(m.messageId).catch(()=>null):null;g.activeMission=null;await saveGangState(guild.id,state);await msg?.edit({embeds:[new EmbedBuilder().setColor(success?0x57F287:0xED4245).setTitle(success?'✅ نجحت مهمة العصابة!':'❌ فشلت مهمة العصابة').setDescription(success?`${reason||'أكملت العصابة جميع المراحل.'}\n\n🏦 تم إيداع **${format(m.reward)} ${currency(cfg)}** في الخزنة.\n🏆 السمعة: **+50**`:`${reason||'انتهت المهمة.'}\n\nلم تدخل أي مكافأة.`)],components:[]}).catch(()=>{});await logs.write(guild,success?'✅ نجاح مهمة عصابة':'❌ فشل مهمة عصابة',`العصابة: ${g.name} (${g.id})\nالمهمة: ${m.name}\nالسبب/النتيجة: ${reason||'—'}\nالمكافأة: ${success?format(m.reward):0} ${currency(cfg)}`,'gangs').catch(()=>{});}finally{missionLocks.delete(g.id);}}
async function handleMissionButton(i,cfg,site){const p=i.customId.split(':'),action=p[2],gangId=p[3],state=await gangState(i.guild.id),g=state.gangs[gangId];if(!g||!g.activeMission)return ephemeral(i,'❌ المهمة لم تعد موجودة.');if(!g.members.includes(i.user.id))return ephemeral(i,'❌ هذه المهمة تخص العصابة فقط.');const m=g.activeMission;
  if(action==='join'){if(m.status!=='open')return ephemeral(i,'❌ بدأت المهمة بالفعل.');if(!m.participants.includes(i.user.id))m.participants.push(i.user.id);await saveGangState(i.guild.id,state);return i.update(missionPayload(cfg,g));}
  if(action==='leave'){if(m.status!=='open')return ephemeral(i,'❌ بدأت المهمة بالفعل.');m.participants=m.participants.filter(x=>x!==i.user.id);if(!m.participants.length)m.participants=[g.leaderId];await saveGangState(i.guild.id,state);return i.update(missionPayload(cfg,g));}
  if(action==='start'){if(!leaderOrDeputy(g,i.user.id))return ephemeral(i,'❌ القائد أو النائب فقط يستطيع البدء.');if(m.participants.length<m.minParticipants)return ephemeral(i,`❌ تحتاج **${m.minParticipants}** مشاركين.`);prepareMission(g,cfg);await saveGangState(i.guild.id,state);return i.update(missionPayload(cfg,g));}
}
async function handleMissionMessage(message,cfg,site){if(!featureOn(cfg,site,'gangMissions'))return false;const {state,gang:g}=await currentGang(message.guild.id,message.author.id);if(!g?.activeMission||g.channelId!==message.channel.id||g.activeMission.status!=='running')return false;const step=missionCurrent(g.activeMission);if(!step||step.type==='voice'||step.assignedUserId!==message.author.id)return false;if(normalizeAnswer(message.content)!==normalizeAnswer(step.challenge?.answer))return false;step.completed=true;await message.react('✅').catch(()=>{});if(g.activeMission.steps.every(s=>s.completed)){await completeMission(message.guild,g,state,cfg,true,'تم تنفيذ جميع التحديات الفعلية.');return true;}await saveGangState(message.guild.id,state);await missionMessage(message.guild,g,cfg);return true;}
async function evaluateMissionVoice(guild,cfg,state,g){const m=g.activeMission;if(!m||m.status!=='running')return;const s=missionCurrent(m);if(!s||s.type!=='voice')return;const members=await Promise.all(s.requiredUserIds.map(id=>guild.members.fetch(id).catch(()=>null))),ids=members.map(x=>x?.voice?.channelId||'');const same=ids.length>=2&&ids[0]&&ids.every(x=>x===ids[0]);if(!same){if(s.voiceStartedAt){s.voiceStartedAt=0;await saveGangState(guild.id,state);await missionMessage(guild,g,cfg);}return;}if(!s.voiceStartedAt){s.voiceStartedAt=Date.now();await saveGangState(guild.id,state);await missionMessage(guild,g,cfg);return;}if(Date.now()-s.voiceStartedAt>=s.requiredSeconds*1000){s.completed=true;await saveGangState(guild.id,state);if(m.steps.every(x=>x.completed))await completeMission(guild,g,state,cfg,true,'اكتملت حراسة الفويس وجميع المراحل.');else await missionMessage(guild,g,cfg);}}

async function equipmentState(gid){const x=await store.data(gid,'equipment-public.json',{users:{}});x.users=x.users||{};return x;}
function invFor(x,uid){x.users[uid]=x.users[uid]||{};for(const k of Object.keys(EQUIPMENT))x.users[uid][k]=Math.max(0,Number(x.users[uid][k]||0));return x.users[uid];}
function equipmentEmbed(cfg,inv){return new EmbedBuilder().setColor(color(cfg)).setTitle('🎒 معدات سرقة البنك').setDescription(Object.entries(EQUIPMENT).map(([k,v])=>`${v.label}: **${format(inv[k])}** — السعر **${format(cfg.robbery?.equipment?.[k]||0)} ${currency(cfg)}**`).join('\n')).setFooter({text:'الخصم من رصيد البنك الشخصي • معدات افتراضية داخل اللعبة'});}
async function equipmentCommand(i,cfg,site,buyItem=''){
  if(!featureOn(cfg,site,'bankRobbery'))return ephemeral(i,'❌ نظام سرقة البنك غير متاح لهذه الخطة.');const {gang}=await currentGang(i.guild.id,i.user.id);if(!gang)return ephemeral(i,'❌ يجب أن تكون عضوًا في عصابة.');const x=await equipmentState(i.guild.id),inv=invFor(x,i.user.id);if(!buyItem)return ephemeral(i,{embeds:[equipmentEmbed(cfg,inv)]});const item=EQUIPMENT[buyItem];if(!item)return ephemeral(i,'❌ المعدة غير موجودة.');if(inv[buyItem]>=item.max)return ephemeral(i,'❌ وصلت للحد الأقصى من هذه المعدة.');const price=Math.max(0,Number(cfg.robbery?.equipment?.[buyItem]||0)),u=await store.getUser(i.guild.id,i.user.id);if(u.bankBalance<price)return ephemeral(i,`❌ رصيد البنك الشخصي غير كافٍ. السعر **${format(price)} ${currency(cfg)}**.`);await store.updateUser(i.guild.id,i.user.id,z=>z.bankBalance-=price);inv[buyItem]++;await store.saveData(i.guild.id,'equipment-public.json',x);return ephemeral(i,`✅ اشتريت ${item.label}. الكمية الآن **${inv[buyItem]}**.`);}

async function robberyState(gid){const x=await store.data(gid,'robbery-public.json',{lobby:null,lastRobberyAt:{},history:[]});x.lastRobberyAt=x.lastRobberyAt||{};x.history=Array.isArray(x.history)?x.history:[];return x;}
function robberyPayload(cfg,g,state){const l=state.lobby;if(!l)return{content:'⛔ السرقة غير متاحة.',components:[]};if(l.status==='running'){const lines=l.tasks.map(t=>`${t.completed?'✅':'⏳'} **${t.label}:** <@${t.assignedUserId}>`).join('\n');return{embeds:[new EmbedBuilder().setColor(0xED4245).setTitle('🚨 سرقة البنك المركزي بدأت!').setDescription(`🏴 العصابة: **${g?.name||'—'}**\n💰 المكافأة: **${format(l.reward)} ${currency(cfg)}** لخزنة العصابة\n⏳ الوقت: <t:${Math.floor(l.expiresAt/1000)}:R>\n\n${lines}`)],components:[new ActionRowBuilder().addComponents(...l.tasks.slice(0,5).map(t=>new ButtonBuilder().setCustomId(`pub:robbery:task:${l.id}:${t.index}`).setLabel(t.label.slice(0,80)).setStyle(t.completed?ButtonStyle.Success:ButtonStyle.Danger).setDisabled(t.completed)))]};}
  const participants=l.participants.map(id=>`<@${id}>`).join('، ')||'بانتظار المشاركين';return{embeds:[new EmbedBuilder().setColor(0xED4245).setTitle('🚨 سرقة البنك أصبحت متاحة!').setDescription(`🏦 الهدف: **البنك المركزي**\n👥 المطلوب: **${l.requiredPlayers} لاعبين من نفس العصابة**\n🏴 العصابة: **${g?.name||'تُحدد عند أول انضمام'}**\n💰 المكافأة: **${format(l.reward)} ${currency(cfg)}**\n⏳ التسجيل: <t:${Math.floor(l.expiresAt/1000)}:R>\n\n**المشاركون (${l.participants.length}/${l.requiredPlayers}):**\n${participants}\n\n🎒 كل مشارك يحتاج قناعًا، والفريق يحتاج جهاز اتصال + جهاز اختراق + مثقاب + سيارة هروب. إذا كان العدد أقل من 5 يمكن للاعب حمل أكثر من مهمة.`).setFooter({text:'جميع الأحداث والمعدات افتراضية داخل اللعبة فقط'})],components:[new ActionRowBuilder().addComponents(
    new ButtonBuilder().setCustomId('pub:robbery:join').setLabel('الانضمام للسرقة').setEmoji('🔴').setStyle(ButtonStyle.Danger),
    new ButtonBuilder().setCustomId('pub:robbery:leave').setLabel('مغادرة').setStyle(ButtonStyle.Secondary),
    new ButtonBuilder().setCustomId('pub:robbery:start').setLabel('بدء العملية').setEmoji('▶️').setStyle(ButtonStyle.Success).setDisabled(l.participants.length<l.requiredPlayers)
  )]};}
async function robberyChannel(guild,cfg){const id=cfg.channels?.centralBank;const ch=id?(guild.channels.cache.get(id)||await guild.channels.fetch(id).catch(()=>null)):null;return ch?.isTextBased()?ch:null;}
function robberyMention(cfg){const mode=['none','everyone','here','role'].includes(String(cfg.robbery?.mentionMode))?String(cfg.robbery.mentionMode):'everyone';if(mode==='everyone')return{content:'@everyone',allowedMentions:{parse:['everyone']}};if(mode==='here')return{content:'@here',allowedMentions:{parse:['everyone']}};const roleId=String(cfg.robbery?.mentionRoleId||'');if(mode==='role'&&/^\d{15,25}$/.test(roleId))return{content:`<@&${roleId}>`,allowedMentions:{parse:[],roles:[roleId]}};return{allowedMentions:{parse:[]}};}
async function ensureRobberyLobby(guild,cfg,site,state){if(!featureOn(cfg,site,'bankRobbery')||cfg.robbery?.enabled!==true)return null;const required=Math.max(2,Math.min(Number(cfg.robbery?.minParticipants||5),limitFor(site,cfg,'robberyParticipants')));if(state.lobby){if(state.lobby.status==='open'&&state.lobby.requiredPlayers!==required){state.lobby.requiredPlayers=required;await store.saveData(guild.id,'robbery-public.json',state);}return state.lobby;}const ch=await robberyChannel(guild,cfg);if(!ch)return null;state.lobby={id:`rb_${Date.now().toString(36)}`,status:'open',channelId:ch.id,messageId:'',gangId:'',participants:[],requiredPlayers:required,reward:Math.max(1,Number(cfg.robbery?.reward||50000)),createdAt:Date.now(),expiresAt:Date.now()+Math.max(2,Number(cfg.robbery?.lobbyMinutes||10))*60000,tasks:[]};const msg=await ch.send({...robberyPayload(cfg,null,state),...robberyMention(cfg)});state.lobby.messageId=msg.id;await store.saveData(guild.id,'robbery-public.json',state);return state.lobby;}
async function editRobbery(guild,cfg,state,g=null){const l=state.lobby;if(!l)return;const ch=guild.channels.cache.get(l.channelId)||await guild.channels.fetch(l.channelId).catch(()=>null),msg=l.messageId?await ch?.messages.fetch(l.messageId).catch(()=>null):null;if(msg)return msg.edit(robberyPayload(cfg,g,state)).catch(()=>{});if(ch?.isTextBased()){const m=await ch.send(robberyPayload(cfg,g,state));l.messageId=m.id;await store.saveData(guild.id,'robbery-public.json',state);}}
async function closeRobbery(guild,cfg,state,reason){const l=state.lobby;if(!l)return;const ch=guild.channels.cache.get(l.channelId)||await guild.channels.fetch(l.channelId).catch(()=>null),msg=l.messageId?await ch?.messages.fetch(l.messageId).catch(()=>null):null;await msg?.edit({embeds:[new EmbedBuilder().setColor(0x747F8D).setTitle('⛔ تم إغلاق سرقة البنك').setDescription(reason)],components:[]}).catch(()=>{});state.lobby=null;await store.saveData(guild.id,'robbery-public.json',state);}
function robberyCooldown(cfg,state,gid){const last=Number(state.lastRobberyAt?.[gid]||0),cd=Math.max(0,Number(cfg.robbery?.cooldownHours||0))*3600000;return Math.max(0,last+cd-Date.now());}
async function assignRobberyGear(gid,participantIds){const x=await equipmentState(gid),used=new Set(),assign=[];for(const uid of participantIds){if(invFor(x,uid).mask<1)return{ok:false,error:`<@${uid}> لا يملك قناعًا.`};}if(!participantIds.length)return{ok:false,error:'لا يوجد مشاركون.'};for(const [role,gear,label] of [['leader','radio','قائد العملية'],['hacker','hacking','الهاكر'],['vault','drill','خبير الخزنة'],['driver','car','السائق']]){const uid=participantIds.find(id=>!used.has(id)&&invFor(x,id)[gear]>0)||participantIds.find(id=>invFor(x,id)[gear]>0);if(!uid)return{ok:false,error:'الفريق يحتاج جهاز اتصال + جهاز اختراق + مثقاب + سيارة هروب. يمكن للاعب واحد حمل أكثر من معدة إذا كان عدد المشاركين قليلًا.'};used.add(uid);assign.push({role,gear,label,userId:uid});}const counts=new Map(participantIds.map(id=>[id,0]));for(const a of assign)counts.set(a.userId,(counts.get(a.userId)||0)+1);const lookout=[...participantIds].sort((a,b)=>(counts.get(a)||0)-(counts.get(b)||0))[0];assign.push({role:'lookout',gear:'mask',label:'المراقب',userId:lookout});return{ok:true,assign,x};}
function robberyTask(a,index){const x=randomInt(20,95),y=randomInt(5,60),code=`RB-${randomInt(1000,9999)}`;if(a.role==='hacker')return{index,label:'اختراق النظام',assignedUserId:a.userId,question:`احسب رمز الاختراق: ${x} + ${y}`,answer:String(x+y),attempts:0,completed:false};if(a.role==='vault')return{index,label:'فتح الخزنة',assignedUserId:a.userId,question:`اكتب كود المثقاب: ${code}`,answer:code,attempts:0,completed:false};if(a.role==='driver')return{index,label:'تجهيز الهروب',assignedUserId:a.userId,question:`رمز المركبة: ${code}`,answer:code,attempts:0,completed:false};if(a.role==='leader')return{index,label:'تأكيد القيادة',assignedUserId:a.userId,question:`رمز الاتصال: ${code}`,answer:code,attempts:0,completed:false};return{index,label:'المراقبة',assignedUserId:a.userId,question:`احسب إشارة المراقبة: ${x} - ${y}`,answer:String(x-y),attempts:0,completed:false};}
async function beginRobbery(i,cfg,site,state,g){const l=state.lobby;if(l.participants.length<l.requiredPlayers)return ephemeral(i,`❌ تحتاج **${l.requiredPlayers}** مشاركين.`);const gear=await assignRobberyGear(i.guild.id,l.participants);if(!gear.ok)return ephemeral(i,`❌ ${gear.error}`);for(const uid of l.participants)invFor(gear.x,uid).mask=Math.max(0,invFor(gear.x,uid).mask-1);await store.saveData(i.guild.id,'equipment-public.json',gear.x);l.status='running';l.tasks=gear.assign.map(robberyTask);l.expiresAt=Date.now()+Math.max(5,Number(cfg.robbery?.missionMinutes||25))*60000;await store.saveData(i.guild.id,'robbery-public.json',state);return i.update(robberyPayload(cfg,g,state));}
async function finishRobbery(guild,cfg,state,success,reason){if(!state.lobby)return;const l=state.lobby;if(robberyLocks.has(l.id))return;robberyLocks.add(l.id);try{const gs=await gangState(guild.id),g=gs.gangs[l.gangId];if(g){if(success){g.bank=Number(g.bank||0)+Number(l.reward||0);g.robberiesWon=Number(g.robberiesWon||0)+1;g.reputation=Number(g.reputation||0)+200;state.lastRobberyAt[g.id]=Date.now();}else g.robberiesFailed=Number(g.robberiesFailed||0)+1;await saveGangState(guild.id,gs);}const ch=guild.channels.cache.get(l.channelId)||await guild.channels.fetch(l.channelId).catch(()=>null),msg=l.messageId?await ch?.messages.fetch(l.messageId).catch(()=>null):null;await msg?.edit({embeds:[new EmbedBuilder().setColor(success?0x57F287:0xED4245).setTitle(success?'✅ نجحت سرقة البنك!':'❌ فشلت سرقة البنك').setDescription(success?`${reason}\n\n🏴 العصابة: **${g?.name||'—'}**\n🏦 تم إيداع **${format(l.reward)} ${currency(cfg)}** في خزنة العصابة.`:`${reason}\n\nلم تدخل أي مكافأة.`)],components:[]}).catch(()=>{});state.history.unshift({gangId:l.gangId,success,reward:success?l.reward:0,finishedAt:Date.now()});state.history=state.history.slice(0,25);await logs.write(guild,success?'🚨 نجاح سرقة البنك':'🚨 فشل سرقة البنك',`العصابة: ${g?.name||l.gangId}\nالمشاركون: ${l.participants.map(id=>`<@${id}>`).join('، ')}\nالنتيجة: ${reason}\nالمكافأة: ${success?format(l.reward):0} ${currency(cfg)}`,'robbery').catch(()=>{});state.lobby=null;await store.saveData(guild.id,'robbery-public.json',state);}finally{robberyLocks.delete(l.id);}}
async function handleRobberyInteraction(i,cfg,site){const action=i.customId.split(':')[2],state=await robberyState(i.guild.id),l=state.lobby;if(!l)return ephemeral(i,'⛔ السرقة غير متاحة الآن.');const gs=await gangState(i.guild.id),memberGangId=gs.membership[i.user.id],g=memberGangId?gs.gangs[memberGangId]:null;
  if(action==='join'){if(l.status!=='open')return ephemeral(i,'❌ بدأت العملية بالفعل.');if(!g)return ephemeral(i,'❌ يجب أن تكون عضوًا في عصابة.');if(l.gangId&&l.gangId!==g.id)return ephemeral(i,'❌ فريق السرقة الحالي من عصابة أخرى.');if(!l.gangId){const rem=robberyCooldown(cfg,state,g.id);if(rem>0)return ephemeral(i,`⏳ عصابتك تستطيع السرقة <t:${Math.floor((Date.now()+rem)/1000)}:R>.`);}const eq=await equipmentState(i.guild.id);if(invFor(eq,i.user.id).mask<1)return ephemeral(i,'❌ تحتاج قناعًا من `/gang equipment` ثم `/gang buy-equipment`.');if(l.participants.includes(i.user.id))return ephemeral(i,'✅ أنت منضم بالفعل.');if(l.participants.length>=l.requiredPlayers)return ephemeral(i,'❌ الفريق مكتمل.');l.gangId=g.id;l.participants.push(i.user.id);await store.saveData(i.guild.id,'robbery-public.json',state);return i.update(robberyPayload(cfg,g,state));}
  if(action==='leave'){if(l.status!=='open')return ephemeral(i,'❌ لا يمكن المغادرة بعد البدء.');l.participants=l.participants.filter(x=>x!==i.user.id);if(!l.participants.length)l.gangId='';await store.saveData(i.guild.id,'robbery-public.json',state);const rg=l.gangId?gs.gangs[l.gangId]:null;return i.update(robberyPayload(cfg,rg,state));}
  if(action==='start'){const rg=gs.gangs[l.gangId];if(!rg||!leaderOrDeputy(rg,i.user.id))return ephemeral(i,'❌ القائد أو النائب فقط يستطيع بدء العملية.');return beginRobbery(i,cfg,site,state,rg);}
  if(action==='task'){const lobbyId=i.customId.split(':')[3],idx=Number(i.customId.split(':')[4]),task=l.id===lobbyId?l.tasks[idx]:null;if(!task||task.completed)return ephemeral(i,'❌ المهمة انتهت.');if(task.assignedUserId!==i.user.id)return ephemeral(i,`❌ هذه المهمة مخصصة لـ <@${task.assignedUserId}>.`);const input=new TextInputBuilder().setCustomId('answer').setLabel(String(task.question).slice(0,45)).setStyle(TextInputStyle.Short).setRequired(true).setMaxLength(60);return i.showModal(new ModalBuilder().setCustomId(`pub:robbery:modal:${l.id}:${idx}`).setTitle(`مهمة: ${task.label}`.slice(0,45)).addComponents(new ActionRowBuilder().addComponents(input)));}
}
async function handleRobberyModal(i,cfg,site){const p=i.customId.split(':'),state=await robberyState(i.guild.id),l=state.lobby,idx=Number(p[4]),task=l?.id===p[3]?l.tasks?.[idx]:null;if(!task||task.completed)return ephemeral(i,'❌ المهمة انتهت.');if(task.assignedUserId!==i.user.id)return ephemeral(i,'❌ هذه المهمة ليست لك.');const answer=i.fields.getTextInputValue('answer');if(normalizeAnswer(answer)!==normalizeAnswer(task.answer)){task.attempts=Number(task.attempts||0)+1;await store.saveData(i.guild.id,'robbery-public.json',state);if(task.attempts>=3){await ephemeral(i,'❌ فشلت المهمة 3 مرات وتم اكتشاف العملية.');return finishRobbery(i.guild,cfg,state,false,`فشل <@${task.assignedUserId}> في **${task.label}**.`);}return ephemeral(i,`❌ إجابة خاطئة. المتبقي **${3-task.attempts}** محاولات.`);}task.completed=true;await store.saveData(i.guild.id,'robbery-public.json',state);await ephemeral(i,`✅ أكملت **${task.label}**.`);if(l.tasks.every(x=>x.completed))return finishRobbery(i.guild,cfg,state,true,'تم تنفيذ جميع مهمات الفريق بنجاح.');const gs=await gangState(i.guild.id);return editRobbery(i.guild,cfg,state,gs.gangs[l.gangId]);}

async function createTempVoice(member,cfg,site){if(!featureOn(cfg,site,'voiceRooms')||cfg.voiceRooms?.enabled!==true||!cfg.channels?.voiceCreate||member.voice.channelId!==cfg.channels.voiceCreate)return null;const guild=member.guild,name=String(cfg.voiceRooms?.roomName||'🎙️・{username}').replace(/\{username\}/gi,member.displayName).slice(0,100);const ch=await guild.channels.create({name,type:ChannelType.GuildVoice,parent:cfg.channels?.voiceCategory||null,userLimit:Number(cfg.voiceRooms?.userLimit||0),bitrate:Math.min(guild.maximumBitrate||384000,Number(cfg.voiceRooms?.bitrate||64000)),permissionOverwrites:[{id:member.id,allow:[PermissionFlagsBits.Connect,PermissionFlagsBits.Speak,PermissionFlagsBits.ViewChannel,PermissionFlagsBits.MoveMembers,PermissionFlagsBits.MuteMembers,PermissionFlagsBits.DeafenMembers,PermissionFlagsBits.ManageChannels]}],reason:`ZOMBI temp voice for ${member.user.tag}`});voiceOwners.set(ch.id,{guildId:guild.id,ownerId:member.id});const state=await store.data(guild.id,'temp-voice.json',{rooms:{}});state.rooms=state.rooms||{};state.rooms[ch.id]={ownerId:member.id,createdAt:Date.now(),controlMessageId:''};await store.saveData(guild.id,'temp-voice.json',state);await member.voice.setChannel(ch).catch(()=>{});const ctrl=cfg.channels?.voiceControl?(guild.channels.cache.get(cfg.channels.voiceControl)||await guild.channels.fetch(cfg.channels.voiceControl).catch(()=>null)):null;if(ctrl?.isTextBased()){const row=new ActionRowBuilder().addComponents(
    new ButtonBuilder().setCustomId(`pub:voice:lock:${ch.id}`).setLabel('قفل').setEmoji('🔒').setStyle(ButtonStyle.Secondary),
    new ButtonBuilder().setCustomId(`pub:voice:unlock:${ch.id}`).setLabel('فتح').setEmoji('🔓').setStyle(ButtonStyle.Secondary),
    new ButtonBuilder().setCustomId(`pub:voice:rename:${ch.id}`).setLabel('تغيير الاسم').setEmoji('✏️').setStyle(ButtonStyle.Primary),
    new ButtonBuilder().setCustomId(`pub:voice:delete:${ch.id}`).setLabel('حذف').setEmoji('🗑️').setStyle(ButtonStyle.Danger)
  );const msg=await ctrl.send({content:`🎙️ ${member} لوحة تحكم رومك ${ch}`,components:[row]});state.rooms[ch.id].controlMessageId=msg.id;await store.saveData(guild.id,'temp-voice.json',state);}await logs.write(guild,'🎙️ إنشاء روم مؤقت',`المالك: ${member.user.tag} (${member.id})\nالروم: ${ch.name} (${ch.id})`,'voice').catch(()=>{});return ch;}
async function cleanupTempVoice(guild,channelId){const state=await store.data(guild.id,'temp-voice.json',{rooms:{}}),room=state.rooms?.[channelId];if(!room)return false;const ch=guild.channels.cache.get(channelId)||await guild.channels.fetch(channelId).catch(()=>null);if(ch?.members?.size)return false;if(ch)await ch.delete('ZOMBI temporary voice empty').catch(()=>{});delete state.rooms[channelId];await store.saveData(guild.id,'temp-voice.json',state);voiceOwners.delete(channelId);return true;}
async function handleVoiceInteraction(i,cfg,site){if(!featureOn(cfg,site,'voiceRooms'))return ephemeral(i,'❌ الرومات المؤقتة غير متاحة.');const p=i.customId.split(':'),action=p[2],channelId=p[3],state=await store.data(i.guild.id,'temp-voice.json',{rooms:{}}),room=state.rooms?.[channelId];if(!room)return ephemeral(i,'❌ الروم المؤقت غير موجود.');if(room.ownerId!==i.user.id&&!isAdmin(i))return ephemeral(i,'❌ هذه اللوحة لصاحب الروم فقط.');const ch=i.guild.channels.cache.get(channelId)||await i.guild.channels.fetch(channelId).catch(()=>null);if(!ch)return ephemeral(i,'❌ الروم غير موجود.');if(action==='lock'){await ch.permissionOverwrites.edit(i.guild.roles.everyone,{Connect:false});return ephemeral(i,'🔒 تم قفل الروم.');}if(action==='unlock'){await ch.permissionOverwrites.edit(i.guild.roles.everyone,{Connect:null});return ephemeral(i,'🔓 تم فتح الروم.');}if(action==='delete'){await ch.delete('Deleted from ZOMBI control').catch(()=>{});delete state.rooms[channelId];await store.saveData(i.guild.id,'temp-voice.json',state);return ephemeral(i,'🗑️ تم حذف الروم.');}if(action==='rename'){const input=new TextInputBuilder().setCustomId('name').setLabel('اسم الروم الجديد').setStyle(TextInputStyle.Short).setRequired(true).setMaxLength(80);return i.showModal(new ModalBuilder().setCustomId(`pub:voice:rename-modal:${channelId}`).setTitle('تغيير اسم الروم').addComponents(new ActionRowBuilder().addComponents(input)));}}
async function handleVoiceModal(i,cfg,site){const channelId=i.customId.split(':')[3],state=await store.data(i.guild.id,'temp-voice.json',{rooms:{}}),room=state.rooms?.[channelId];if(!room)return ephemeral(i,'❌ الروم غير موجود.');if(room.ownerId!==i.user.id&&!isAdmin(i))return ephemeral(i,'❌ هذه العملية لصاحب الروم فقط.');const ch=i.guild.channels.cache.get(channelId)||await i.guild.channels.fetch(channelId).catch(()=>null);if(!ch)return ephemeral(i,'❌ الروم غير موجود.');const name=i.fields.getTextInputValue('name').trim().slice(0,80);await ch.setName(name,'ZOMBI voice rename');return ephemeral(i,`✅ تم تغيير الاسم إلى **${name}**.`);}

async function handleGangCommand(i,cfg,site){const sub=i.options.getSubcommand();if(sub==='create')return createGang(i,cfg,site,i.options.getString('name'));if(!featureOn(cfg,site,'gangs'))return ephemeral(i,'❌ نظام العصابات غير متاح لهذه الخطة.');const gid=i.guild.id,uid=i.user.id,{state,gang:g}=await currentGang(gid,uid);const maxMembers=Math.min(Number(cfg.gangs?.maxMembers||7),limitFor(site,cfg,'gangMembers')),maxDeputies=Math.min(Number(cfg.gangs?.maxDeputies||2),limitFor(site,cfg,'gangDeputies'));
  if(sub==='list'){const list=Object.values(state.gangs||{});return ephemeral(i,{embeds:[new EmbedBuilder().setColor(color(cfg)).setTitle('🏴 عصابات السيرفر').setDescription(list.length?list.slice(0,20).map((x,n)=>`**${n+1}. ${x.name}** — 👥 ${(x.members||[]).length}/${maxMembers} • 🏦 ${format(x.bank)}`).join('\n'):'لا توجد عصابات.') ]});}
  if(!g)return ephemeral(i,'❌ أنت لست داخل عصابة.');if(sub==='info')return ephemeral(i,{embeds:[gangEmbed(cfg,g)]});const can=leaderOrDeputy(g,uid),leader=g.leaderId===uid;
  if(sub==='invite'){if(!can)return ephemeral(i,'❌ القائد أو النائب فقط.');const t=i.options.getUser('user');if(t.bot||state.membership[t.id])return ephemeral(i,'❌ لا يمكن دعوة هذا العضو.');if(g.members.length>=maxMembers)return ephemeral(i,'❌ العصابة ممتلئة.');const row=new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId(`pub:gang:accept:${g.id}:${t.id}`).setStyle(ButtonStyle.Success).setLabel('قبول').setEmoji('✅'));return ephemeral(i,{content:`🏴 ${t} تمت دعوتك إلى **${g.name}**.`,components:[row]});}
  if(sub==='kick'){if(!can)return ephemeral(i,'❌ لا تملك صلاحية.');const t=i.options.getUser('user');if(t.id===g.leaderId||!g.members.includes(t.id))return ephemeral(i,'❌ لا يمكن طرد هذا العضو.');if(!leader&&(g.deputies||[]).includes(t.id))return ephemeral(i,'❌ النائب لا يستطيع طرد نائب آخر.');g.members=g.members.filter(x=>x!==t.id);g.deputies=(g.deputies||[]).filter(x=>x!==t.id);delete state.membership[t.id];await saveGangState(gid,state);await memberRole(i.guild,g,t.id,false);return ephemeral(i,`✅ تم طرد ${t}.`);}
  if(sub==='deputy'){if(!leader)return ephemeral(i,'❌ القائد فقط.');const t=i.options.getUser('user');if(t.id===uid||!g.members.includes(t.id))return ephemeral(i,'❌ اختر عضوًا من العصابة.');g.deputies=g.deputies||[];if(g.deputies.includes(t.id)){g.deputies=g.deputies.filter(x=>x!==t.id);await saveGangState(gid,state);return ephemeral(i,`➖ تمت إزالة ${t} من النواب.`);}if(g.deputies.length>=maxDeputies)return ephemeral(i,`❌ الحد الأقصى **${maxDeputies}**.`);g.deputies.push(t.id);await saveGangState(gid,state);return ephemeral(i,`⭐ أصبح ${t} نائبًا.`);}
  if(sub==='leave'){if(leader&&g.members.length>1)return ephemeral(i,'❌ انقل الملكية أو اطرد الأعضاء قبل حل العصابة.');if(leader){for(const id of g.members)delete state.membership[id];delete state.gangs[g.id];await saveGangState(gid,state);await deleteGangResources(i.guild,g);return ephemeral(i,'🗑️ تم حل العصابة وحذف شاتها ورتبتها.');}g.members=g.members.filter(x=>x!==uid);g.deputies=(g.deputies||[]).filter(x=>x!==uid);delete state.membership[uid];await saveGangState(gid,state);await memberRole(i.guild,g,uid,false);return ephemeral(i,'✅ غادرت العصابة.');}
  if(sub==='rename'){if(!leader)return ephemeral(i,'❌ القائد فقط يستطيع تغيير الاسم.');const name=String(i.options.getString('name')||'').trim().slice(0,40);if(name.length<2)return ephemeral(i,'❌ الاسم غير صالح.');g.name=name;await saveGangState(gid,state);const role=g.roleId?(i.guild.roles.cache.get(g.roleId)||await i.guild.roles.fetch(g.roleId).catch(()=>null)):null,ch=g.channelId?(i.guild.channels.cache.get(g.channelId)||await i.guild.channels.fetch(g.channelId).catch(()=>null)):null;await role?.setName(`🏴 ${name}`.slice(0,100),'ZOMBI gang rename').catch(()=>{});await ch?.setName(`gang-${safeName(name)}`,'ZOMBI gang rename').catch(()=>{});return ephemeral(i,`✅ تم تغيير اسم العصابة إلى **${name}**.`);}
  if(sub==='transfer'){if(!leader)return ephemeral(i,'❌ القائد فقط يستطيع نقل الملكية.');const t=i.options.getUser('user');if(t.id===uid||!g.members.includes(t.id))return ephemeral(i,'❌ اختر عضوًا من العصابة.');g.leaderId=t.id;g.deputies=(g.deputies||[]).filter(x=>x!==t.id);await saveGangState(gid,state);return ephemeral(i,`👑 تم نقل ملكية العصابة إلى ${t}.`);}
  if(sub==='delete'){if(!leader)return ephemeral(i,'❌ القائد فقط يستطيع حذف العصابة.');for(const id of g.members)delete state.membership[id];delete state.gangs[g.id];await saveGangState(gid,state);await deleteGangResources(i.guild,g);return ephemeral(i,'🗑️ تم حذف العصابة وشاتها ورتبتها.');}
  if(sub==='mission')return startMission(i,cfg,site,g,state);
  if(sub==='equipment')return equipmentCommand(i,cfg,site,'');
  if(sub==='buy-equipment')return equipmentCommand(i,cfg,site,i.options.getString('item'));
  const amount=i.options.getInteger('amount');if(sub==='deposit'){if(cfg.gangs?.bankEnabled===false)return ephemeral(i,'❌ الخزنة معطلة.');const u=await store.getUser(gid,uid);if(u.balance<amount)return ephemeral(i,'❌ رصيدك لا يكفي.');await store.updateUser(gid,uid,x=>x.balance-=amount);g.bank=Number(g.bank||0)+amount;await saveGangState(gid,state);return ephemeral(i,`🏦 أودعت **${format(amount)}** في الخزنة.`);}if(sub==='withdraw'){if(cfg.gangs?.bankEnabled===false||!can)return ephemeral(i,'❌ لا تملك صلاحية السحب.');if(Number(g.bank||0)<amount)return ephemeral(i,'❌ الخزنة لا تكفي.');g.bank-=amount;await store.updateUser(gid,uid,x=>x.balance+=amount);await saveGangState(gid,state);return ephemeral(i,`💰 سحبت **${format(amount)}**.`);}}

async function onVoiceState(oldState,newState){const guild=newState.guild||oldState.guild;if(!guild||guild.id===String(getHomeGuildId()||''))return;try{const [cfg,site]=await Promise.all([store.getConfig(guild.id),getSiteConfig()]);const member=newState.member||oldState.member;if(!member||member.user.bot)return;if(newState.channelId===cfg.channels?.voiceCreate&&oldState.channelId!==newState.channelId)await createTempVoice(member,cfg,site);if(oldState.channelId&&oldState.channelId!==newState.channelId)setTimeout(()=>cleanupTempVoice(guild,oldState.channelId).catch(()=>{}),2500).unref?.();const state=await gangState(guild.id);for(const g of Object.values(state.gangs||{}))if(g.activeMission)await evaluateMissionVoice(guild,cfg,state,g);}catch(e){console.warn('Public city voice:',e.message);}}
async function onMessage(message,cfg,site){if(!message.guild||message.author.bot)return false;const raw=String(message.content||'').trim();if(raw==='سرقة البنك'){const state=await robberyState(message.guild.id);if(!state.lobby){await message.reply('⛔ سرقة البنك غير متاحة الآن. الإدارة تفتحها من Dashboard.').catch(()=>{});return true;}const gs=await gangState(message.guild.id),g=state.lobby.gangId?gs.gangs[state.lobby.gangId]:null;await message.reply(robberyPayload(cfg,g,state)).catch(()=>{});return true;}if(raw==='معدات'||raw==='عصابة معدات'){const {gang}=await currentGang(message.guild.id,message.author.id);if(!gang){await message.reply('❌ يجب أن تكون عضوًا في عصابة.').catch(()=>{});return true;}const x=await equipmentState(message.guild.id),inv=invFor(x,message.author.id);await message.reply({embeds:[equipmentEmbed(cfg,inv)]}).catch(()=>{});return true;}return handleMissionMessage(message,cfg,site);}
async function handleInteraction(i,cfg,site){const cid=String(i.customId||'');if(cid.startsWith('pub:gang:accept:'))return acceptGangInvite(i,cfg,site),true;if(cid.startsWith('pub:gm:'))return handleMissionButton(i,cfg,site),true;if(cid.startsWith('pub:robbery:modal:')&&i.isModalSubmit())return handleRobberyModal(i,cfg,site),true;if(cid.startsWith('pub:robbery:')&&i.isButton())return handleRobberyInteraction(i,cfg,site),true;if(cid.startsWith('pub:voice:rename-modal:')&&i.isModalSubmit())return handleVoiceModal(i,cfg,site),true;if(cid.startsWith('pub:voice:')&&i.isButton())return handleVoiceInteraction(i,cfg,site),true;return false;}

async function tick(){if(!client?.isReady?.())return;for(const guild of client.guilds.cache.values()){if(guild.id===String(getHomeGuildId()||''))continue;try{const [cfg,site]=await Promise.all([store.getConfig(guild.id),getSiteConfig()]);const gs=await gangState(guild.id);for(const g of Object.values(gs.gangs||{})){if(g.activeMission){if(Number(g.activeMission.expiresAt||0)<=Date.now())await completeMission(guild,g,gs,cfg,false,'انتهى الوقت قبل إكمال جميع المراحل.');else await evaluateMissionVoice(guild,cfg,gs,g);}}
      const rs=await robberyState(guild.id);if(featureOn(cfg,site,'bankRobbery')&&cfg.robbery?.enabled===true){await ensureRobberyLobby(guild,cfg,site,rs);if(rs.lobby&&Number(rs.lobby.expiresAt||0)<=Date.now())await finishRobbery(guild,cfg,rs,false,'انتهى الوقت قبل إكمال العملية.');}else if(rs.lobby)await closeRobbery(guild,cfg,rs,'تم إغلاق السرقة من Dashboard.');
    }catch(e){console.warn(`Public city tick ${guild.name}:`,e.message);}}}
function init(c,opts={}){client=c;getSiteConfig=opts.getSiteConfig||getSiteConfig;getHomeGuildId=opts.getHomeGuildId||getHomeGuildId;c.on('voiceStateUpdate',onVoiceState);if(tickTimer)clearInterval(tickTimer);tickTimer=setInterval(()=>tick().catch(e=>console.warn('Public city tick:',e.message)),10000);tickTimer.unref?.();setTimeout(()=>tick().catch(()=>{}),2500).unref?.();}

module.exports={init,handleGangCommand,handleInteraction,onMessage,gangState,saveGangState,deleteGangResources,ensureRobberyLobby,robberyState,missionTemplatesDefault,EQUIPMENT};
