'use strict';
const fs=require('fs');
const path=require('path');
const {GAME_DEFS,normalizePlans}=require('./planPolicy');
const {DEFAULT_GAME_CONTENT,normalizeGameContent}=require('./gameDefaults');

const BASE_DATA=process.env.ZOMBI_LOCAL_DATA_DIR?path.resolve(process.env.ZOMBI_LOCAL_DATA_DIR):path.join(__dirname,path.basename(__dirname)==='public'?'..':'.','data');
const ROOT=path.join(BASE_DATA,'guilds');
const CODES_FILE=path.join(BASE_DATA,'premium-codes.json');
const GLOBAL_FILE=path.join(BASE_DATA,'public-site.json');
const clone=v=>JSON.parse(JSON.stringify(v));
function ensureDir(d){fs.mkdirSync(d,{recursive:true});}
function writeJson(file,data){ensureDir(path.dirname(file));const tmp=`${file}.tmp`;fs.writeFileSync(tmp,JSON.stringify(data,null,2),'utf8');try{fs.renameSync(tmp,file);}catch{fs.writeFileSync(file,JSON.stringify(data,null,2),'utf8');try{fs.unlinkSync(tmp);}catch{}}}
function readJson(file,fallback){try{return JSON.parse(fs.readFileSync(file,'utf8'));}catch{return clone(fallback);}}
const snowflake=v=>/^[0-9]{15,25}$/.test(String(v||'').trim())?String(v).trim():'';
const text=(v='',max=200)=>String(v??'').trim().slice(0,max);
function integer(v,fallback,min=0,max=1e9){const n=Number(v);return Number.isFinite(n)?Math.max(min,Math.min(max,Math.round(n))):fallback;}
const bool=(v,fallback=true)=>typeof v==='boolean'?v:fallback;
function url(v=''){const s=text(v,1000);if(!s)return'';try{const u=new URL(s);return ['http:','https:'].includes(u.protocol)?u.toString():'';}catch{return'';}}
function gameRuleDefaults(id){const time=id==='speed'?15:(id==='truefalse'||id==='math'?20:25);return{rounds:5,roundTimeSeconds:time,winnerReward:300};}
function defaultGameSettings(){return Object.fromEntries(GAME_DEFS.map(g=>[g.id,gameRuleDefaults(g.id)]));}
function defaultGameEnabled(){return Object.fromEntries(GAME_DEFS.map(g=>[g.id,true]));}
function defaultTicketTypes(){return[{id:'general',label:'دعم عام',emoji:'🎫',description:'تذكرة دعم عامة',supportRoleIds:[]}];}
function defaultGangMissionTemplates(){return[
  {id:'intel',name:'جمع معلومات',description:'اجمعوا المعلومات ونفذوا مراحل المهمة داخل شات العصابة.',minParticipants:2,enabled:true},
  {id:'guard',name:'حراسة الموقع',description:'عضوان على الأقل ينفذان تحدي الشات ثم حراسة فويس مشتركة.',minParticipants:2,enabled:true},
  {id:'delivery',name:'توصيل الشحنة',description:'تنسيق بين أعضاء العصابة وإكمال رمز المهمة قبل انتهاء الوقت.',minParticipants:2,enabled:true}
];}
function defaults(guildId){return{
  guildId:String(guildId),plan:'free',premiumUntil:0,createdAt:Date.now(),updatedAt:Date.now(),setupComplete:false,
  system:{presenceText:'ZOM Economy | /help',presenceStatus:'online'},
  features:{economy:true,bank:true,games:true,tickets:true,store:true,rolePanel:true,levels:true,voiceRewards:true,voiceRooms:false,moderation:true,gangs:false,gangMissions:false,bankRobbery:false},
  branding:{color:'#7c3aed',name:'ZOMBI',footer:'Powered by ZOMBI',customName:'',customFooter:'',botNickname:'',avatarUrl:'',bannerUrl:'',bio:'',panelLogoUrl:'',panelBannerUrl:''},
  currency:{name:'ZOM',emoji:'🪙'},
  channels:{logs:'',gamePanel:'',ticketPanel:'',ticketCategory:'',storePanel:'',rolePanel:'',levelUp:'',bankPanel:'',centralBank:'',gangCategory:'',gangLogs:'',voiceCreate:'',voiceControl:'',voiceCategory:'',nameChangePanel:''},
  economy:{dailyAmount:500,dailyCooldownHours:24,messageEvery:15,messageReward:10,messageCooldownSeconds:60,transferCooldownSeconds:10,voiceEveryMinutes:10,voiceReward:10,messageChannelIds:[],voiceChannelIds:[]},
  bank:{heistEnabled:true,heistCooldownSeconds:300,heistTimeSeconds:25,depositEnabled:true,withdrawEnabled:true,maxTransaction:1000000000,title:'🏦 ZOMBI City Bank',description:'إيداع، سحب وتحويل رصيد البنك.',goldValue:100000,salaryCooldownHours:4,maxSalary:1000,tradeProfitPercent:15,tradeSessionMinutes:5,maxLoan:100000,loanInterestPercent:10,companyEmployeeStartSalary:4000,companyEmployeeSalaryIncrease:500,companyLevelUpHours:24,companyOwnerStartSalary:100000,companyOwnerSalaryIncrease:5000},
  moderation:{clearEnabled:true,kickEnabled:true,banEnabled:true,lockEnabled:true,logActions:true},
  warnings:{role1Id:'',role2Id:'',role3Id:''},
  games:{rounds:5,roundTimeSeconds:25,winnerReward:300,enabled:defaultGameEnabled(),quickGameSettings:defaultGameSettings(),wheelRewards:[50,75,100,150,200,300],rouletteEnabled:true,rouletteTurnSeconds:25,rouletteActionCosts:{revive:300,link:300,protect:300,freeze:500,double:500,curse:500,unlink:200,add:1000},chairs:{startCountdownSeconds:5,betweenRoundsMs:2500},lobby:{roulette:{minPlayers:2,maxPlayers:20},chairs:{minPlayers:2,maxPlayers:20},mafia:{minPlayers:4,maxPlayers:20}}},
  gangs:{maxMembers:7,maxDeputies:2,createCost:0,bankEnabled:true,missionsEnabled:true,minMissionParticipants:2,maxMissionSteps:5,puzzleMaxAttempts:2,chatMaxAttempts:2,relayMaxAttempts:2,missionCooldownMinutes:240,missionDurationMinutes:30,missionRewardMin:15000,missionRewardMax:35000,missionVoiceSeconds:60,roleColor:'#2b2d31'},
  robbery:{enabled:false,minParticipants:5,lobbyMinutes:10,missionMinutes:25,reward:50000,cooldownHours:12,equipment:{mask:1000,hacking:2500,drill:3000,radio:1500,car:5000},panelMessageId:''},
  voiceRooms:{enabled:false,roomName:'🎙️・{username}',userLimit:0,bitrate:64000,controlMessageId:''},
  nameChange:{enabled:false,title:'تغيير اسمك في السيرفر',description:'اضغط الزر لتغيير اسمك داخل السيرفر.',buttonLabel:'تغيير اسمي',buttonEmoji:'✏️',modalTitle:'تغيير اسمك في السيرفر',inputLabel:'ضع الاسم الجديد',inputPlaceholder:'اكتب اسمك الجديد هنا...',successMessage:'✅ تم تغيير اسمك بنجاح إلى **{name}**.',cooldownSeconds:30,color:'#8B5CF6',bannerUrl:'',panelMessageId:''},
  levels:{xpPerMessage:10,xpCooldownSeconds:30,baseXp:100,growth:50},
  tickets:{title:'🎫 ZOMBI Support',description:'اختر نوع التذكرة من الأزرار بالأسفل.',buttonLabel:'فتح تذكرة',buttonEmoji:'🎫',supportRoleIds:[],types:defaultTicketTypes(),panelMessageId:''},
  store:{title:'🏙️ ZOMBI CITY STORE',description:'اختر الرتبة لعرض تفاصيلها ثم شراءها باستخدام رصيدك.',footer:'ZOMBI • ZOM Store',accentColor:'#7c3aed',thumbnailUrl:'',bannerUrl:'',detailBannerUrl:'',products:[],panelMessageId:''},
  rolePanel:{title:'🔔 رتب الإشعارات',description:'اختر الرتب التي تريدها.',footer:'ZOMBI • ROLE CENTER',items:[],panelMessageId:''}
};}
function guildDir(gid){return path.join(ROOT,String(gid));}
function fileFor(gid,name){return path.join(guildDir(gid),name);}
function normalizeTicketTypes(types,fallbackSupport=[]){const src=Array.isArray(types)&&types.length?types:defaultTicketTypes(),seen=new Set(),out=[];for(const raw of src){let id=text(raw?.id,40).toLowerCase().replace(/[^a-z0-9_-]/g,'-').replace(/-+/g,'-').replace(/^-|-$/g,'');if(!id)id=`type-${out.length+1}`;if(seen.has(id))id=`${id}-${out.length+1}`;seen.add(id);const support=[...new Set((raw?.supportRoleIds||raw?.viewRoleIds||fallbackSupport||[]).map(snowflake).filter(Boolean))].slice(0,50),view=[...new Set((raw?.viewRoleIds||support).map(snowflake).filter(Boolean))].slice(0,50),open=[...new Set((raw?.openRoleIds||[]).map(snowflake).filter(Boolean))].slice(0,50);out.push({id,label:text(raw?.label||raw?.name||'دعم',80)||'دعم',name:text(raw?.name||raw?.label||'دعم',80)||'دعم',emoji:text(raw?.emoji||'🎫',32)||'🎫',description:text(raw?.description||'',300),welcomeMessage:text(raw?.welcomeMessage||'اشرح طلبك وسيتم الرد عليك من الإدارة.',1200),categoryId:snowflake(raw?.categoryId),supportRoleIds:support,viewRoleIds:view,openRoleIds:open,maxOpenPerUser:integer(raw?.maxOpenPerUser,1,1,10),enabled:bool(raw?.enabled,true)});if(out.length>=25)break;}return out.length?out:defaultTicketTypes();}
function normalizeStoreProducts(raw){const src=Array.isArray(raw)?raw:[],seen=new Set(),out=[];for(const p of src){const roleId=snowflake(p?.roleId);if(!roleId||seen.has(roleId))continue;seen.add(roleId);out.push({id:text(p?.id,80)||`product_${Date.now()}_${out.length}`,type:'role',roleId,name:text(p?.name||'رتبة',80)||'رتبة',price:integer(p?.price,1,1,1e9),category:text(p?.category||'رتب الأعضاء',80)||'رتب الأعضاء',emoji:text(p?.emoji||'🏷️',32)||'🏷️',description:text(p?.description||'رتبة مميزة يمكنك شراؤها باستخدام رصيد السيرفر.',1000),features:(Array.isArray(p?.features)?p.features:String(p?.features||'').split(/\r?\n/)).map(x=>text(x,180)).filter(Boolean).slice(0,8),imageUrl:url(p?.imageUrl),bannerUrl:url(p?.bannerUrl),enabled:bool(p?.enabled,true),sortOrder:integer(p?.sortOrder,out.length*10,0,9999),accessMode:['everyone','admins','roles'].includes(p?.accessMode)?p.accessMode:'everyone',allowedRoleIds:[...new Set((p?.allowedRoleIds||[]).map(snowflake).filter(Boolean))].slice(0,25)});if(out.length>=100)break;}return out.sort((a,b)=>a.sortOrder-b.sortOrder||a.name.localeCompare(b.name));}
function normalizeConfig(input,guildId){const d=defaults(guildId),x=input||{},premiumUntil=Number(x.premiumUntil||0),plan=(x.plan==='premium'&&premiumUntil>Date.now())?'premium':'free';const cfg={...d,...x,guildId:String(guildId),plan,premiumUntil:plan==='premium'?premiumUntil:0,system:{...d.system,...(x.system||{})},features:{...d.features,...(x.features||{})},branding:{...d.branding,...(x.branding||{})},currency:{...d.currency,...(x.currency||{})},channels:{...d.channels,...(x.channels||{})},economy:{...d.economy,...(x.economy||{})},bank:{...d.bank,...(x.bank||{})},moderation:{...d.moderation,...(x.moderation||{})},warnings:{...d.warnings,...(x.warnings||{})},games:{...d.games,...(x.games||{}),rouletteActionCosts:{...d.games.rouletteActionCosts,...(x.games?.rouletteActionCosts||{})},chairs:{...d.games.chairs,...(x.games?.chairs||{})},lobby:{...d.games.lobby,...(x.games?.lobby||{})}},gangs:{...d.gangs,...(x.gangs||{})},robbery:{...d.robbery,...(x.robbery||{}),equipment:{...d.robbery.equipment,...(x.robbery?.equipment||{})}},voiceRooms:{...d.voiceRooms,...(x.voiceRooms||{})},nameChange:{...d.nameChange,...(x.nameChange||{})},levels:{...d.levels,...(x.levels||{})},tickets:{...d.tickets,...(x.tickets||{})},store:{...d.store,...(x.store||{})},rolePanel:{...d.rolePanel,...(x.rolePanel||{})}};
  cfg.system.presenceText=text(cfg.system.presenceText||d.system.presenceText,128)||d.system.presenceText;cfg.system.presenceStatus=['online','idle','dnd','invisible'].includes(String(cfg.system.presenceStatus))?String(cfg.system.presenceStatus):d.system.presenceStatus;
  cfg.features=Object.fromEntries(Object.entries(d.features).map(([k,v])=>[k,bool(cfg.features[k],v)]));for(const k of Object.keys(cfg.channels))cfg.channels[k]=snowflake(cfg.channels[k]);
  cfg.branding.color=/^#[0-9a-f]{6}$/i.test(String(cfg.branding.color||''))?String(cfg.branding.color):d.branding.color;for(const k of ['customName','botNickname'])cfg.branding[k]=text(cfg.branding[k],80);cfg.branding.customFooter=text(cfg.branding.customFooter,160);cfg.branding.bio=text(cfg.branding.bio,190);for(const k of ['avatarUrl','bannerUrl','panelLogoUrl','panelBannerUrl'])cfg.branding[k]=url(cfg.branding[k]);
  cfg.currency.name=text(cfg.currency.name||'ZOM',20)||'ZOM';cfg.currency.emoji=text(cfg.currency.emoji||'🪙',16)||'🪙';
  cfg.economy.dailyAmount=integer(cfg.economy.dailyAmount,500,0,1e9);cfg.economy.dailyCooldownHours=integer(cfg.economy.dailyCooldownHours,24,1,720);cfg.economy.messageEvery=integer(cfg.economy.messageEvery,15,1,10000);cfg.economy.messageReward=integer(cfg.economy.messageReward,10,0,1e9);cfg.economy.messageCooldownSeconds=integer(cfg.economy.messageCooldownSeconds,60,0,86400);cfg.economy.transferCooldownSeconds=integer(cfg.economy.transferCooldownSeconds,10,0,86400);cfg.economy.voiceEveryMinutes=integer(cfg.economy.voiceEveryMinutes,10,1,1440);cfg.economy.voiceReward=integer(cfg.economy.voiceReward,10,0,1e9);cfg.economy.messageChannelIds=[...new Set((cfg.economy.messageChannelIds||[]).map(snowflake).filter(Boolean))].slice(0,50);cfg.economy.voiceChannelIds=[...new Set((cfg.economy.voiceChannelIds||[]).map(snowflake).filter(Boolean))].slice(0,50);
  cfg.bank.depositEnabled=bool(cfg.bank.depositEnabled,true);cfg.bank.withdrawEnabled=bool(cfg.bank.withdrawEnabled,true);cfg.bank.maxTransaction=integer(cfg.bank.maxTransaction,1e9,1,1e9);cfg.bank.title=text(cfg.bank.title,120)||d.bank.title;cfg.bank.description=text(cfg.bank.description,800)||d.bank.description;cfg.bank.goldValue=integer(cfg.bank.goldValue,d.bank.goldValue,1,1e9);cfg.bank.salaryCooldownHours=integer(cfg.bank.salaryCooldownHours,d.bank.salaryCooldownHours,0,720);cfg.bank.maxSalary=integer(cfg.bank.maxSalary,d.bank.maxSalary,0,1e9);cfg.bank.tradeProfitPercent=integer(cfg.bank.tradeProfitPercent,d.bank.tradeProfitPercent,0,1000);cfg.bank.tradeSessionMinutes=integer(cfg.bank.tradeSessionMinutes,d.bank.tradeSessionMinutes,1,1440);cfg.bank.maxLoan=integer(cfg.bank.maxLoan,d.bank.maxLoan,0,1e9);cfg.bank.loanInterestPercent=integer(cfg.bank.loanInterestPercent,d.bank.loanInterestPercent,0,1000);cfg.bank.companyEmployeeStartSalary=integer(cfg.bank.companyEmployeeStartSalary,d.bank.companyEmployeeStartSalary,0,1e9);cfg.bank.companyEmployeeSalaryIncrease=integer(cfg.bank.companyEmployeeSalaryIncrease,d.bank.companyEmployeeSalaryIncrease,0,1e9);cfg.bank.companyLevelUpHours=integer(cfg.bank.companyLevelUpHours,d.bank.companyLevelUpHours,1,8760);cfg.bank.companyOwnerStartSalary=integer(cfg.bank.companyOwnerStartSalary,d.bank.companyOwnerStartSalary,0,1e9);cfg.bank.companyOwnerSalaryIncrease=integer(cfg.bank.companyOwnerSalaryIncrease,d.bank.companyOwnerSalaryIncrease,0,1e9);
  for(const k of ['clearEnabled','kickEnabled','banEnabled','lockEnabled','logActions'])cfg.moderation[k]=bool(cfg.moderation[k],d.moderation[k]);for(const k of ['role1Id','role2Id','role3Id'])cfg.warnings[k]=snowflake(cfg.warnings[k]);
  cfg.games.rounds=integer(cfg.games.rounds,5,1,25);cfg.games.roundTimeSeconds=integer(cfg.games.roundTimeSeconds,25,5,300);cfg.games.winnerReward=integer(cfg.games.winnerReward,300,0,1e9);const enabled={...defaultGameEnabled(),...(cfg.games.enabled||{})};cfg.games.enabled=Object.fromEntries(GAME_DEFS.map(g=>[g.id,bool(enabled[g.id],true)]));const rules={...defaultGameSettings(),...(cfg.games.quickGameSettings||{})};cfg.games.quickGameSettings={};for(const g of GAME_DEFS){const r=rules[g.id]||{},f=gameRuleDefaults(g.id);cfg.games.quickGameSettings[g.id]={rounds:integer(r.rounds,f.rounds,1,25),roundTimeSeconds:integer(r.roundTimeSeconds,f.roundTimeSeconds,5,300),winnerReward:integer(r.winnerReward,f.winnerReward,0,1e9)};}cfg.games.wheelRewards=(Array.isArray(cfg.games.wheelRewards)?cfg.games.wheelRewards:String(cfg.games.wheelRewards||'').split(/[\s,]+/)).map(v=>integer(v,0,0,1e9)).filter(Number.isFinite).slice(0,30);if(!cfg.games.wheelRewards.length)cfg.games.wheelRewards=[...d.games.wheelRewards];cfg.games.rouletteEnabled=bool(cfg.games.rouletteEnabled,true);cfg.games.rouletteTurnSeconds=integer(cfg.games.rouletteTurnSeconds,25,10,120);for(const k of Object.keys(d.games.rouletteActionCosts))cfg.games.rouletteActionCosts[k]=integer(cfg.games.rouletteActionCosts[k],d.games.rouletteActionCosts[k],0,1e9);cfg.games.chairs.startCountdownSeconds=integer(cfg.games.chairs.startCountdownSeconds,d.games.chairs.startCountdownSeconds,1,60);cfg.games.chairs.betweenRoundsMs=integer(cfg.games.chairs.betweenRoundsMs,d.games.chairs.betweenRoundsMs,250,30000);for(const id of ['roulette','chairs','mafia']){const ld=d.games.lobby[id],raw=cfg.games.lobby[id]||{};cfg.games.lobby[id]={minPlayers:integer(raw.minPlayers,ld.minPlayers,id==='mafia'?4:2,25),maxPlayers:integer(raw.maxPlayers,ld.maxPlayers,id==='mafia'?4:2,25)};if(cfg.games.lobby[id].maxPlayers<cfg.games.lobby[id].minPlayers)cfg.games.lobby[id].maxPlayers=cfg.games.lobby[id].minPlayers;}
  cfg.gangs.maxMembers=integer(cfg.gangs.maxMembers,7,2,50);cfg.gangs.maxDeputies=integer(cfg.gangs.maxDeputies,2,0,10);cfg.gangs.createCost=integer(cfg.gangs.createCost,0,0,1e9);cfg.gangs.bankEnabled=bool(cfg.gangs.bankEnabled,true);cfg.gangs.missionsEnabled=bool(cfg.gangs.missionsEnabled,true);cfg.gangs.minMissionParticipants=integer(cfg.gangs.minMissionParticipants,2,2,25);cfg.gangs.maxMissionSteps=integer(cfg.gangs.maxMissionSteps,5,1,10);cfg.gangs.puzzleMaxAttempts=integer(cfg.gangs.puzzleMaxAttempts,2,1,20);cfg.gangs.chatMaxAttempts=integer(cfg.gangs.chatMaxAttempts,2,1,20);cfg.gangs.relayMaxAttempts=integer(cfg.gangs.relayMaxAttempts,2,1,20);cfg.gangs.missionCooldownMinutes=integer(cfg.gangs.missionCooldownMinutes,240,1,10080);cfg.gangs.missionDurationMinutes=integer(cfg.gangs.missionDurationMinutes,30,5,180);cfg.gangs.missionRewardMin=integer(cfg.gangs.missionRewardMin,15000,0,1e9);cfg.gangs.missionRewardMax=integer(cfg.gangs.missionRewardMax,35000,0,1e9);if(cfg.gangs.missionRewardMax<cfg.gangs.missionRewardMin)cfg.gangs.missionRewardMax=cfg.gangs.missionRewardMin;cfg.gangs.missionVoiceSeconds=integer(cfg.gangs.missionVoiceSeconds,60,10,3600);cfg.gangs.roleColor=/^#[0-9a-f]{6}$/i.test(String(cfg.gangs.roleColor||''))?String(cfg.gangs.roleColor):d.gangs.roleColor;
  cfg.robbery.enabled=bool(cfg.robbery.enabled,false);cfg.robbery.minParticipants=integer(cfg.robbery.minParticipants,5,2,25);cfg.robbery.lobbyMinutes=integer(cfg.robbery.lobbyMinutes,10,2,60);cfg.robbery.missionMinutes=integer(cfg.robbery.missionMinutes,25,5,180);cfg.robbery.reward=integer(cfg.robbery.reward,50000,1,1e9);cfg.robbery.cooldownHours=integer(cfg.robbery.cooldownHours,12,0,720);for(const k of Object.keys(d.robbery.equipment))cfg.robbery.equipment[k]=integer(cfg.robbery.equipment[k],d.robbery.equipment[k],0,1e9);cfg.robbery.panelMessageId=text(cfg.robbery.panelMessageId,30);
  cfg.voiceRooms.enabled=bool(cfg.voiceRooms.enabled,false);cfg.voiceRooms.roomName=text(cfg.voiceRooms.roomName,80)||d.voiceRooms.roomName;cfg.voiceRooms.userLimit=integer(cfg.voiceRooms.userLimit,0,0,99);cfg.voiceRooms.bitrate=integer(cfg.voiceRooms.bitrate,64000,8000,384000);cfg.voiceRooms.controlMessageId=text(cfg.voiceRooms.controlMessageId,30);cfg.nameChange.enabled=bool(cfg.nameChange.enabled,false);for(const k of ['title','description','buttonLabel','buttonEmoji','modalTitle','inputLabel','inputPlaceholder','successMessage'])cfg.nameChange[k]=text(cfg.nameChange[k],k==='description'||k==='successMessage'?1200:160)||d.nameChange[k];cfg.nameChange.cooldownSeconds=integer(cfg.nameChange.cooldownSeconds,30,0,86400);cfg.nameChange.color=/^#[0-9a-f]{6}$/i.test(String(cfg.nameChange.color||''))?String(cfg.nameChange.color):d.nameChange.color;cfg.nameChange.bannerUrl=url(cfg.nameChange.bannerUrl);cfg.nameChange.panelMessageId=text(cfg.nameChange.panelMessageId,30);
  cfg.levels.xpPerMessage=integer(cfg.levels.xpPerMessage,10,1,10000);cfg.levels.xpCooldownSeconds=integer(cfg.levels.xpCooldownSeconds,30,5,3600);cfg.levels.baseXp=integer(cfg.levels.baseXp,100,10,1e6);cfg.levels.growth=integer(cfg.levels.growth,50,0,1e6);
  cfg.tickets.title=text(cfg.tickets.title,256)||d.tickets.title;cfg.tickets.description=text(cfg.tickets.description,2000)||d.tickets.description;cfg.tickets.buttonLabel=text(cfg.tickets.buttonLabel,80)||d.tickets.buttonLabel;cfg.tickets.buttonEmoji=text(cfg.tickets.buttonEmoji,32)||'🎫';cfg.tickets.supportRoleIds=[...new Set((cfg.tickets.supportRoleIds||[]).map(snowflake).filter(Boolean))].slice(0,50);cfg.tickets.types=normalizeTicketTypes(cfg.tickets.types,cfg.tickets.supportRoleIds);cfg.tickets.panelMessageId=text(cfg.tickets.panelMessageId,30);
  cfg.store.title=text(cfg.store.title,256)||d.store.title;cfg.store.description=text(cfg.store.description,2000)||d.store.description;cfg.store.footer=text(cfg.store.footer||d.store.footer,160)||d.store.footer;cfg.store.accentColor=/^#[0-9a-f]{6}$/i.test(String(cfg.store.accentColor||''))?String(cfg.store.accentColor):d.store.accentColor;cfg.store.thumbnailUrl=url(cfg.store.thumbnailUrl);cfg.store.bannerUrl=url(cfg.store.bannerUrl);cfg.store.detailBannerUrl=url(cfg.store.detailBannerUrl);cfg.store.products=normalizeStoreProducts(cfg.store.products);cfg.store.panelMessageId=text(cfg.store.panelMessageId,30);
  cfg.rolePanel.title=text(cfg.rolePanel.title,256)||d.rolePanel.title;cfg.rolePanel.description=text(cfg.rolePanel.description,2000)||d.rolePanel.description;cfg.rolePanel.footer=text(cfg.rolePanel.footer||d.rolePanel.footer,160)||d.rolePanel.footer;cfg.rolePanel.items=(Array.isArray(cfg.rolePanel.items)?cfg.rolePanel.items:[]).map(p=>({roleId:snowflake(p.roleId),label:text(p.label,80),emoji:text(p.emoji||'🔔',32),style:['Primary','Secondary','Success','Danger'].includes(p.style)?p.style:'Primary'})).filter(p=>p.roleId).slice(0,100);cfg.rolePanel.panelMessageId=text(cfg.rolePanel.panelMessageId,30);
  cfg.bank.heistEnabled=bool(cfg.bank.heistEnabled,true);cfg.bank.heistCooldownSeconds=integer(cfg.bank.heistCooldownSeconds,300,30,86400);cfg.bank.heistTimeSeconds=integer(cfg.bank.heistTimeSeconds,25,10,120);cfg.updatedAt=Date.now();return cfg;
}
function getConfig(gid){const f=fileFor(gid,'config.json'),cfg=normalizeConfig(readJson(f,defaults(gid)),gid);writeJson(f,cfg);return clone(cfg);}function saveConfig(gid,input){const cfg=normalizeConfig(input,gid);writeJson(fileFor(gid,'config.json'),cfg);return clone(cfg);}function patchConfig(gid,patch){const c=getConfig(gid),n=clone(c);for(const [k,v] of Object.entries(patch||{}))n[k]=v&&typeof v==='object'&&!Array.isArray(v)?{...(n[k]||{}),...v}:v;return saveConfig(gid,n);}function data(gid,name,fallback={}){return readJson(fileFor(gid,name),fallback);}function saveData(gid,name,value){writeJson(fileFor(gid,name),value);return clone(value);}function getGameContent(gid){const raw=data(gid,'game-content.json',DEFAULT_GAME_CONTENT),n=normalizeGameContent(raw);saveData(gid,'game-content.json',n);return clone(n);}function saveGameContent(gid,input){return saveData(gid,'game-content.json',normalizeGameContent(input));}
function ensureUserShape(u={}){return{balance:Number(u.balance||0),bankBalance:Number(u.bankBalance||0),messageCount:Number(u.messageCount||0),lastDaily:Number(u.lastDaily||0),lastMessageReward:Number(u.lastMessageReward||0),lastTransfer:Number(u.lastTransfer||0),xp:Number(u.xp||0),level:Number(u.level||0),purchases:Array.isArray(u.purchases)?u.purchases:[]};}function getEconomy(gid){return data(gid,'economy.json',{});}function getUser(gid,uid){const e=getEconomy(gid);e[uid]=ensureUserShape(e[uid]);saveData(gid,'economy.json',e);return clone(e[uid]);}function updateUser(gid,uid,fn){const e=getEconomy(gid),u=ensureUserShape(e[uid]);fn(u,e);e[uid]=u;saveData(gid,'economy.json',e);return clone(u);}
function allGuildIds(){try{return fs.readdirSync(ROOT,{withFileTypes:true}).filter(x=>x.isDirectory()).map(x=>x.name);}catch{return[];}}function isPremium(cfg){return cfg?.plan==='premium'&&Number(cfg?.premiumUntil||0)>Date.now();}function setPremium(gid,days=30){const c=getConfig(gid),base=Math.max(Date.now(),Number(c.premiumUntil||0));c.plan='premium';c.premiumUntil=base+Math.max(1,Number(days||30))*86400000;return saveConfig(gid,c);}function removePremium(gid){const c=getConfig(gid);c.plan='free';c.premiumUntil=0;return saveConfig(gid,c);}
function globalDefaults(){return{premiumPrice:'4.99 JD / month',purchaseUrl:'',announcement:'',supportUrl:'',plans:normalizePlans({}),updatedAt:Date.now()};}function normalizeGlobalConfig(input={}){const d=globalDefaults();return{...d,...input,premiumPrice:text(input.premiumPrice??d.premiumPrice,80),purchaseUrl:url(input.purchaseUrl),announcement:text(input.announcement,500),supportUrl:url(input.supportUrl),plans:normalizePlans(input.plans||{}),updatedAt:Date.now()};}function getGlobalConfig(){return normalizeGlobalConfig(readJson(GLOBAL_FILE,globalDefaults()));}function saveGlobalConfig(input={}){const cur=getGlobalConfig(),merged={...cur,...input,plans:input.plans?{free:{...cur.plans.free,...input.plans.free,features:{...cur.plans.free.features,...(input.plans.free?.features||{})},games:{...cur.plans.free.games,...(input.plans.free?.games||{})},limits:{...cur.plans.free.limits,...(input.plans.free?.limits||{})}},premium:{...cur.plans.premium,...input.plans.premium,features:{...cur.plans.premium.features,...(input.plans.premium?.features||{})},games:{...cur.plans.premium.games,...(input.plans.premium?.games||{})},limits:{...cur.plans.premium.limits,...(input.plans.premium?.limits||{})}}}:cur.plans};const n=normalizeGlobalConfig(merged);writeJson(GLOBAL_FILE,n);return n;}function getCodes(){return readJson(CODES_FILE,[]);}function saveCodes(c){writeJson(CODES_FILE,c);return c;}function createCode(days=30){const chars='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';let s='ZOMBI-';for(let i=0;i<12;i++)s+=chars[Math.floor(Math.random()*chars.length)];const list=getCodes(),item={code:s,days:integer(days,30,1,3650),createdAt:Date.now(),usedAt:0,usedByGuildId:''};list.push(item);saveCodes(list);return item;}function redeemCode(gid,code){const list=getCodes(),item=list.find(x=>x.code===String(code||'').trim().toUpperCase());if(!item)throw new Error('كود التفعيل غير صحيح.');if(item.usedAt)throw new Error('هذا الكود مستخدم مسبقًا.');item.usedAt=Date.now();item.usedByGuildId=String(gid);saveCodes(list);return{item,config:setPremium(gid,item.days)};}
module.exports={BASE_DATA,defaults,normalizeConfig,getConfig,saveConfig,patchConfig,data,saveData,getGameContent,saveGameContent,getEconomy,getUser,updateUser,allGuildIds,isPremium,setPremium,removePremium,globalDefaults,normalizeGlobalConfig,getGlobalConfig,saveGlobalConfig,getCodes,createCode,redeemCode,defaultGangMissionTemplates};
