'use strict';
(()=>{
 const setup=document.querySelector('#ops-setup');let step=0;
 const show=()=>{if(!setup)return;setup.querySelectorAll('[data-stage]').forEach(el=>el.hidden=Number(el.dataset.stage)!==step);setup.querySelectorAll('[data-step]').forEach(el=>el.setAttribute('aria-current',Number(el.dataset.step)===step?'step':'false'));document.querySelector('#ops-prev').disabled=step===0;document.querySelector('#ops-next').hidden=step===2;};
 async function request(url,data){const r=await fetch(url,{method:'POST',body:new URLSearchParams(data),headers:{Accept:'application/json'}});const type=r.headers.get('content-type')||'';if(!type.includes('application/json'))throw new Error('تعذر تنفيذ الطلب. حدّث الصفحة وتحقق من تسجيل الدخول.');const j=await r.json();if(!r.ok||!j.ok){const e=new Error(j.error||'تعذر تنفيذ الطلب');e.checks=j.checks;throw e;}return j;}
 function results(target,checks,message){target.replaceChildren();if(message){const p=document.createElement('p');p.textContent=message;target.append(p);}for(const c of checks||[]){const p=document.createElement('article');p.className='ops-result '+(c.ok?'ok':'bad');p.textContent=(c.ok?'✓ ':'! ')+c.label+(c.fix?' — '+c.fix:'');target.append(p);}}
 if(setup){setup.querySelectorAll('[data-step]').forEach(b=>b.onclick=()=>{step=Number(b.dataset.step);show();});document.querySelector('#ops-prev').onclick=()=>{step=Math.max(0,step-1);show();};document.querySelector('#ops-next').onclick=()=>{step=Math.min(2,step+1);show();};setup.onreset=()=>setTimeout(()=>{step=0;show();results(document.querySelector('#ops-results'),[],'تمت إعادة التجربة.');},0);
 const run=async(save)=>{const out=document.querySelector('#ops-results');results(out,[],'جارٍ الفحص…');try{if(setup.dataset.demo==='true'){const data=new FormData(setup),checks=['bank','games','tickets','store','rolePanel'].filter(k=>data.has('feature_'+k)).map(k=>({ok:Boolean(data.get('channel_'+({bank:'bankPanel',games:'gamePanel',tickets:'ticketPanel',store:'storePanel',rolePanel:'rolePanel'}[k]))),label:'اختيار روم '+({bank:'البنك',games:'الألعاب',tickets:'التذاكر',store:'المتجر',rolePanel:'الرتب'}[k]),fix:'اختر رومًا في الخطوة الثانية.'}));results(out,checks,save?'تم تطبيق اختياراتك داخل هذه التجربة فقط.':'فحص تجريبي لا يتصل بديسكورد.');return;}const j=await request(setup.action+(save?'':'/check'),new FormData(setup));results(out,j.checks,j.message||'اكتمل الفحص.');}catch(e){results(out,e.checks,e.message);}};
 document.querySelector('#ops-check').onclick=()=>run(false);setup.onsubmit=e=>{e.preventDefault();run(true);};show();}
 const editor=document.querySelector('#ops-editor');
 function render(payload){const target=document.querySelector('#ops-panel');target.replaceChildren();for(const e of payload.embeds||[]){const card=document.createElement('article');card.style.borderInlineStart='4px solid #'+Number(e.color||0x7c3aed).toString(16).padStart(6,'0');const h=document.createElement('h3');h.textContent=e.title||'';const p=document.createElement('p');p.style.whiteSpace='pre-wrap';p.textContent=e.description||'';card.append(h,p);if(e.image?.url&&/^https:\/\//i.test(e.image.url)){const img=document.createElement('img');img.src=e.image.url;img.alt='صورة اللوحة';img.referrerPolicy='no-referrer';card.append(img);}target.append(card);}for(const row of payload.components||[]){const group=document.createElement('div');group.className='ops-buttons';for(const b of row.components||[]){const button=document.createElement('button');button.type='button';button.textContent=b.label||b.placeholder||'قائمة';button.disabled=true;group.append(button);}target.append(group);}}
 if(editor){editor.onsubmit=async e=>{e.preventDefault();const out=document.querySelector('#ops-editor-status'),data=new FormData(editor);data.set('action',e.submitter?.value||'preview');out.textContent='جارٍ تجهيز المعاينة…';try{let j;if(editor.dataset.demo==='true'){j={payload:{embeds:[{title:data.get('title')||'🏦 بنك ZOMBI',description:data.get('description')||'إدارة الرصيد والتحويلات',image:{url:data.get('image')}}],components:[{components:String(data.get('buttons')||'حسابي\nإيداع\nسحب').split('\n').map(label=>({label}))}]},message:'معاينة تجريبية؛ لا تُحفظ على سيرفر حقيقي.'};}else j=await request(editor.action,data);render(j.payload);out.textContent=j.message;}catch(err){out.textContent=err.message;}};}
 const gid=location.pathname.match(/^\/dashboard\/(\d+)$/)?.[1];if(gid){const bar=document.createElement('nav');bar.className='ops-toolbar';for(const [url,label] of [['setup','إعداد أول تشغيل'],['permissions','فحص صلاحيات البوت'],['panels/bank','معاينة البنك'],['panels/tickets','معاينة التذاكر'],['panels/games','معاينة الألعاب'],['panels/store','معاينة المتجر'],['panels/roles','معاينة الرتب'],['panels/name','معاينة تغيير الاسم']]){const a=document.createElement('a');a.className='btn';a.href=`/dashboard/${gid}/${url}`;a.textContent=label;bar.append(a);}document.querySelector('main')?.prepend(bar);}
 if(document.querySelector('#plans')){const refresh=async()=>{try{const r=await fetch('/api/public/plans',{cache:'no-store'});if(!r.ok)return;const j=await r.json(),current=document.querySelector('#plans'),open=current?.querySelector('details')?.open;if(current){const template=document.createElement('template');template.innerHTML=j.html;const next=template.content.firstElementChild;if(next?.id==='plans'){if(open)next.querySelector('details').open=true;current.replaceWith(next);}}}catch{}};setInterval(()=>{if(!document.hidden)refresh();},30000);}
})();
