'use strict';
(()=>{
 const setup=document.querySelector('#ops-setup');let step=0;
 const show=()=>{if(!setup)return;setup.querySelectorAll('[data-stage]').forEach(el=>el.hidden=Number(el.dataset.stage)!==step);setup.querySelectorAll('[data-step]').forEach(el=>el.setAttribute('aria-current',Number(el.dataset.step)===step?'step':'false'));document.querySelector('#ops-prev').disabled=step===0;document.querySelector('#ops-next').hidden=step===2;};
 async function request(url,data){const r=await fetch(url,{method:'POST',body:new URLSearchParams(data),headers:{Accept:'application/json'}});const type=r.headers.get('content-type')||'';if(!type.includes('application/json'))throw new Error('تعذر تنفيذ الطلب. حدّث الصفحة وتحقق من تسجيل الدخول.');const j=await r.json();if(!r.ok||!j.ok){const e=new Error(j.error||'تعذر تنفيذ الطلب');e.checks=j.checks;throw e;}return j;}
 function results(target,checks,message){target.replaceChildren();if(message){const p=document.createElement('p');p.textContent=message;target.append(p);}for(const c of checks||[]){const p=document.createElement('article');p.className='ops-result '+(c.ok?'ok':'bad');p.textContent=(c.ok?'✓ ':'! ')+c.label+(c.fix?' — '+c.fix:'');target.append(p);}}
 if(setup){setup.querySelectorAll('[data-step]').forEach(b=>b.onclick=()=>{step=Number(b.dataset.step);show();});document.querySelector('#ops-prev').onclick=()=>{step=Math.max(0,step-1);show();};document.querySelector('#ops-next').onclick=()=>{step=Math.min(2,step+1);show();};setup.onreset=()=>setTimeout(()=>{step=0;show();results(document.querySelector('#ops-results'),[],'تمت إعادة التجربة.');},0);
 const run=async(save)=>{const out=document.querySelector('#ops-results');results(out,[],'جارٍ الفحص…');try{if(setup.dataset.demo==='true'){const data=new FormData(setup),checks=['bank','games','tickets','store','rolePanel'].filter(k=>data.has('feature_'+k)).map(k=>({ok:Boolean(data.get('channel_'+({bank:'bankPanel',games:'gamePanel',tickets:'ticketPanel',store:'storePanel',rolePanel:'rolePanel'}[k]))),label:'اختيار روم '+({bank:'البنك',games:'الألعاب',tickets:'التذاكر',store:'المتجر',rolePanel:'الرتب'}[k]),fix:'اختر رومًا في الخطوة الثانية.'}));results(out,checks,save?'تم تطبيق اختياراتك داخل هذه التجربة فقط.':'فحص تجريبي لا يتصل بديسكورد.');return;}const j=await request(setup.action+(save?'':'/check'),new FormData(setup));results(out,j.checks,j.message||'اكتمل الفحص.');}catch(e){results(out,e.checks,e.message);}};
 document.querySelector('#ops-check').onclick=()=>run(false);setup.onsubmit=e=>{e.preventDefault();run(true);};show();}

 const editor=document.querySelector('#ops-editor');
 if(editor){
   const status=document.querySelector('#ops-editor-status');
   const preview=document.querySelector('#ops-panel');
   const hidden={buttons:editor.querySelector('textarea[name="buttons"]'),menus:editor.querySelector('textarea[name="menus"]')};
   const lists={buttons:editor.querySelector('[data-label-list="buttons"]'),menus:editor.querySelector('[data-label-list="menus"]')};
   let timer=null,busy=false,pending=false,seeded={buttons:false,menus:false};
   const styleName=n=>({1:'أزرق',2:'رمادي',3:'أخضر',4:'أحمر',5:'رابط'})[n]||'زر';
   const componentEmoji=c=>c?.emoji?.name?String(c.emoji.name)+' ':'';
   const lines=name=>String(hidden[name]?.value||'').split(/\r?\n/).map(x=>x.trim()).filter(Boolean);
   function syncHidden(name){if(!hidden[name]||!lists[name])return;hidden[name].value=[...lists[name].querySelectorAll('input[data-label-value]')].map(x=>x.value.trim()).filter(Boolean).join('\n');}
   function makeRow(name,value,index){const row=document.createElement('div');row.className='ops-label-row';const num=document.createElement('span');num.className='ops-label-number';num.textContent=String(index+1);const input=document.createElement('input');input.type='text';input.dataset.labelValue='1';input.value=value||'';input.maxLength=name==='buttons'?80:150;input.placeholder=name==='buttons'?`اسم الزر ${index+1}`:`اسم القائمة ${index+1}`;input.addEventListener('input',()=>{syncHidden(name);schedule();});const del=document.createElement('button');del.type='button';del.className='ops-mini-delete';del.textContent='×';del.title='حذف الاسم المخصص';del.onclick=()=>{row.remove();renumber(name);syncHidden(name);schedule();};row.append(num,input,del);return row;}
   function renumber(name){[...lists[name].children].forEach((row,i)=>{row.querySelector('.ops-label-number').textContent=String(i+1);const input=row.querySelector('input');input.placeholder=name==='buttons'?`اسم الزر ${i+1}`:`اسم القائمة ${i+1}`;});}
   function setRows(name,values,{force=false}={}){if(!lists[name]||(!force&&lists[name].children.length))return;lists[name].replaceChildren();values.forEach((v,i)=>lists[name].append(makeRow(name,v,i)));seeded[name]=values.length>0;}
   for(const name of ['buttons','menus']){setRows(name,lines(name),{force:true});editor.querySelector(`[data-add-label="${name}"]`)?.addEventListener('click',()=>{const i=lists[name].children.length;lists[name].append(makeRow(name,'',i));lists[name].lastElementChild.querySelector('input').focus();});}

   function imageBox(kind){const input=editor.querySelector(`[data-image-input="${kind}"]`),box=editor.querySelector(`[data-image-box="${kind}"]`);if(!input||!box)return;const refresh=()=>{const url=input.value.trim();box.querySelectorAll('img').forEach(x=>x.remove());const old=box.querySelector('.ops-image-status');if(old)old.remove();if(!url){box.classList.remove('has-image','bad-image');return;}const img=document.createElement('img');img.alt=kind==='logo'?'Logo preview':'Banner preview';img.referrerPolicy='no-referrer';const st=document.createElement('span');st.className='ops-image-status';st.textContent='جارٍ تحميل الصورة…';img.onload=()=>{box.classList.add('has-image');box.classList.remove('bad-image');st.textContent='✅ الرابط يعمل والصورة جاهزة.';};img.onerror=()=>{box.classList.remove('has-image');box.classList.add('bad-image');st.textContent='❌ لم أستطع عرض الصورة. استخدم رابط HTTPS مباشر للصورة.';};img.src=url;box.prepend(img);box.append(st);};input.addEventListener('input',()=>{refresh();schedule();});refresh();}
   imageBox('logo');imageBox('banner');
   const colorText=editor.querySelector('input[name="color"]'),colorPicker=editor.querySelector('[data-color-picker]');
   if(colorText&&colorPicker){colorPicker.addEventListener('input',()=>{colorText.value=colorPicker.value;schedule();});colorText.addEventListener('input',()=>{if(/^#[0-9a-f]{6}$/i.test(colorText.value))colorPicker.value=colorText.value;schedule();});}

   function render(payload){preview.replaceChildren();const wrap=document.createElement('div');wrap.className='ops-discord-message';const avatar=document.createElement('div');avatar.className='ops-discord-avatar';avatar.textContent='Z';const body=document.createElement('div');body.className='ops-discord-body';const meta=document.createElement('div');meta.className='ops-discord-meta';meta.innerHTML='<b>ZOMBI</b><span>APP</span><small>الآن</small>';body.append(meta);for(const e of payload.embeds||[]){const card=document.createElement('article');card.className='ops-discord-embed';card.style.borderInlineStartColor='#'+Number(e.color||0x7c3aed).toString(16).padStart(6,'0');if(e.thumbnail?.url&&/^https:\/\//i.test(e.thumbnail.url)){const thumb=document.createElement('img');thumb.src=e.thumbnail.url;thumb.alt='Logo اللوحة';thumb.referrerPolicy='no-referrer';thumb.className='ops-discord-thumb';card.append(thumb);}const h=document.createElement('h3');h.textContent=e.title||'';const p=document.createElement('p');p.textContent=e.description||'';card.append(h,p);if(e.image?.url&&/^https:\/\//i.test(e.image.url)){const img=document.createElement('img');img.src=e.image.url;img.alt='Banner اللوحة';img.referrerPolicy='no-referrer';img.className='ops-discord-banner';card.append(img);}if(e.footer?.text){const f=document.createElement('small');f.textContent=e.footer.text;card.append(f);}body.append(card);}const found={buttons:[],menus:[]};for(const row of payload.components||[]){const group=document.createElement('div');group.className='ops-discord-components';for(const c of row.components||[]){if(c.type===2){const button=document.createElement('button');button.type='button';button.disabled=true;button.className=`discord-btn style-${c.style||2}`;button.textContent=componentEmoji(c)+(c.label||'زر');button.title=styleName(c.style);group.append(button);found.buttons.push(c.label||'زر');}else{const select=document.createElement('button');select.type='button';select.disabled=true;select.className='discord-select';select.textContent=componentEmoji(c)+(c.placeholder||'اختر من القائمة')+'⌄';group.append(select);found.menus.push(c.placeholder||'اختر من القائمة');}}body.append(group);}wrap.append(avatar,body);preview.append(wrap);for(const name of ['buttons','menus']){if(!seeded[name]&&!lines(name).length&&found[name].length){setRows(name,found[name],{force:true});syncHidden(name);seeded[name]=true;}}}
   function demoPayload(data){const rawColor=String(data.get('color')||'#7c3aed').replace('#','');const bs=String(data.get('buttons')||'حسابي\nإيداع\nسحب').split('\n').filter(Boolean),ms=String(data.get('menus')||'اختر من القائمة').split('\n').filter(Boolean);return{embeds:[{title:data.get('title')||'🏦 بنك ZOMBI',description:data.get('description')||'إدارة الرصيد والتحويلات',color:parseInt(rawColor,16)||0x7c3aed,...(data.get('thumbnail')?{thumbnail:{url:data.get('thumbnail')}}:{}),...(data.get('image')?{image:{url:data.get('image')}}:{}),...(data.get('footer')?{footer:{text:data.get('footer')}}:{})}],components:[{components:bs.map(label=>({type:2,style:1,label}))},{components:ms.map(placeholder=>({type:3,placeholder}))}]};}
   async function run(action='preview'){if(busy){pending=true;return;}busy=true;status.textContent=action==='preview'?'جارٍ تحديث المعاينة…':'جارٍ الحفظ…';try{for(const n of ['buttons','menus'])syncHidden(n);const data=new FormData(editor);data.set('action',action);let j;if(editor.dataset.demo==='true'){j={ok:true,payload:demoPayload(data),message:'معاينة تجريبية؛ لا تُحفظ على سيرفر حقيقي.'};}else j=await request(editor.action,data);render(j.payload);status.textContent=j.message||'تم.';status.className='ops-editor-status ok';if(j.reset){editor.reset();for(const n of ['buttons','menus']){lists[n].replaceChildren();hidden[n].value='';seeded[n]=false;}editor.querySelectorAll('[data-image-input]').forEach(x=>x.dispatchEvent(new Event('input')));}}catch(err){status.textContent='❌ '+err.message;status.className='ops-editor-status bad';}finally{busy=false;if(pending){pending=false;run('preview');}}}
   function schedule(){clearTimeout(timer);timer=setTimeout(()=>run('preview'),450);}
   editor.querySelectorAll('input:not([data-label-value]):not([data-image-input]),textarea:not([hidden])').forEach(el=>el.addEventListener('input',schedule));
   editor.addEventListener('submit',e=>{e.preventDefault();const action=e.submitter?.value||'preview';if(action==='reset'&&!confirm('ترجع تصميم هذه اللوحة للوضع الافتراضي؟'))return;run(action);});
   run('preview');
 }

 const gid=location.pathname.match(/^\/dashboard\/(\d+)$/)?.[1];if(gid){const bar=document.createElement('nav');bar.className='ops-toolbar';for(const [url,label] of [['setup','إعداد أول تشغيل'],['permissions','فحص صلاحيات البوت'],['panels/bank','💎 تخصيص البنك'],['panels/games','💎 تخصيص الألعاب'],['panels/tickets','💎 تخصيص التذاكر'],['panels/store','💎 تخصيص المتجر'],['panels/roles','💎 تخصيص الرتب'],['panels/name','💎 تخصيص تغيير الاسم']]){const a=document.createElement('a');a.className='btn';a.href=`/dashboard/${gid}/${url}`;a.textContent=label;bar.append(a);}document.querySelector('main')?.prepend(bar);}
 if(document.querySelector('#plans')){const refresh=async()=>{try{const r=await fetch('/api/public/plans',{cache:'no-store'});if(!r.ok)return;const j=await r.json(),current=document.querySelector('#plans'),open=current?.querySelector('details')?.open;if(current){const template=document.createElement('template');template.innerHTML=j.html;const next=template.content.firstElementChild;if(next?.id==='plans'){if(open)next.querySelector('details').open=true;current.replaceWith(next);}}}catch{}};setInterval(()=>{if(!document.hidden)refresh();},30000);}
})();
