'use strict';
const crypto=require('crypto');
const {FEATURE_DEFS,featureAllowed,limitFor}=require('./planPolicy');
const SYSTEMS={heist:'النهب',bank:'البنك',games:'الألعاب',tickets:'التذاكر',store:'متجر الرتب',rolePanel:'رتب الإشعارات'};
const CHANNELS={logs:['سجل الإدارة',0],bankPanel:['لوحة البنك',0],gamePanel:['لوحة الألعاب',0],ticketPanel:['لوحة التذاكر',0],ticketCategory:['فئة التذاكر',4],storePanel:['لوحة المتجر',0],rolePanel:['لوحة الرتب',0]};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const field=(name,label,value='')=>`<label>${label}<input name="${name}" value="${esc(value)}"></label>`;
function permissions(bundle,member,channel){
 const roles=bundle.roles.filter(r=>r.id===bundle.guild.id||member.roles.includes(r.id));let p=roles.reduce((n,r)=>n|BigInt(r.permissions||0),0n);
 if(p&8n)return (1n<<53n)-1n;
 const ow=channel?.permission_overwrites||[],everyone=ow.find(o=>o.id===bundle.guild.id);if(everyone)p=(p&~BigInt(everyone.deny||0))|BigInt(everyone.allow||0);
 const rs=ow.filter(o=>Number(o.type)===0&&member.roles.includes(o.id));p=(p&~rs.reduce((n,o)=>n|BigInt(o.deny||0),0n))|rs.reduce((n,o)=>n|BigInt(o.allow||0),0n);
 const own=ow.find(o=>Number(o.type)===1&&o.id===member.user.id);if(own)p=(p&~BigInt(own.deny||0))|BigInt(own.allow||0);return p;
}
function inspect(bundle,member,cfg){
 const results=[];const add=(ok,label,fix='')=>results.push({ok,label,fix:ok?'':fix});
 const required={bankPanel:'bank',gamePanel:'games',ticketPanel:'tickets',ticketCategory:'tickets',storePanel:'store',rolePanel:'rolePanel'};
 for(const [key,[label,type]] of Object.entries(CHANNELS)){
  if(!cfg.channels[key]&&!cfg.features[required[key]])continue;
  const c=bundle.channels.find(c=>c.id===cfg.channels[key]);add(Boolean(c),label,cfg.channels[key]?'الروم محذوف أو غير متاح؛ اختر رومًا آخر.':'حدد الروم من إعداد أول تشغيل.');if(!c)continue;
  add(type===4?c.type===4:[0,5].includes(c.type),`نوع ${label}`,'اختر نوع الروم المناسب.');const p=permissions(bundle,member,c);
  for(const [bit,name] of (type===4?[[1024n,'مشاهدة الروم'],[16n,'إدارة الرومات']]:[[1024n,'مشاهدة الروم'],[2048n,'إرسال الرسائل'],[16384n,'إرفاق الروابط']]))add(Boolean(p&bit),`${label}: ${name}`,`افتح صلاحيات ${label} واسمح للبوت بـ ${name}، وراجع منع الصلاحية على رتبته.`);
 }
 const highest=Math.max(0,...bundle.roles.filter(r=>member.roles.includes(r.id)).map(r=>r.position));
 const targets=[...(cfg.rolePanel?.items||[]),...(cfg.store?.products||[])];
 for(const item of targets){const r=bundle.roles.find(r=>r.id===item.roleId);add(Boolean(r&&!r.managed&&r.id!==bundle.guild.id&&r.position<highest),`إدارة رتبة ${r?.name||item.roleId}`,'ضع رتبة البوت أعلى من الرتبة المستهدفة؛ لا تستخدم رتبة بوت أو everyone.');}
 if(targets.length)add(Boolean(permissions(bundle,member)&268435456n),'صلاحية إدارة الرتب','فعّل Manage Roles لرتبة البوت.');return results;
}
function setupView(cfg,bundle,site,token,demo=false){return `<section class="ops"><div class="ops-head"><span class="badge">${demo?'تجربة ببيانات وهمية':'إعداد السيرفر'}</span><h1>جهّز سيرفرك مع ZOMBI</h1><p>اختر الأنظمة، اربط الرومات والرتب، ثم افحص الإعدادات قبل الحفظ.</p></div><form id="ops-setup" action="${demo?'#':`/dashboard/${cfg.guildId}/setup`}" method="post" data-demo="${demo}"><input type="hidden" name="_csrf" value="${esc(token)}"><nav class="ops-steps"><button type="button" data-step="0">1 · الأنظمة</button><button type="button" data-step="1">2 · الرومات والرتب</button><button type="button" data-step="2">3 · فحص وحفظ</button></nav><fieldset data-stage="0"><legend>الأنظمة المطلوبة</legend><div class="ops-grid">${Object.entries(SYSTEMS).filter(([k])=>k!=='heist').map(([k,v])=>`<label class="ops-choice"><input type="checkbox" name="feature_${k}" ${cfg.features[k]?'checked':''} ${!featureAllowed(site,cfg,k)?'disabled':''}>${v}${!featureAllowed(site,cfg,k)?' · يحتاج ترقية':''}</label>`).join('')}</div></fieldset><fieldset data-stage="1" hidden><legend>الرومات والرتب</legend><div class="ops-grid">${Object.entries(CHANNELS).map(([k,[label,type]])=>`<label>${label}<select name="channel_${k}"><option value="">بدون اختيار</option>${bundle.channels.filter(c=>type===4?c.type===4:[0,5].includes(c.type)).map(c=>`<option value="${c.id}" ${cfg.channels[k]===c.id?'selected':''}>${esc(c.name)}</option>`).join('')}</select></label>`).join('')}<label>رتب بدء الألعاب<select name="startRoleIds" multiple>${bundle.roles.filter(r=>r.id!==bundle.guild.id&&!r.managed).map(r=>`<option value="${r.id}" ${cfg.games.startRoleIds.includes(r.id)?'selected':''}>${esc(r.name)}</option>`).join('')}</select></label><label>رتب دعم التذاكر<select name="supportRoleIds" multiple>${bundle.roles.filter(r=>r.id!==bundle.guild.id&&!r.managed).map(r=>`<option value="${r.id}" ${(cfg.tickets.supportRoleIds||[]).includes(r.id)?'selected':''}>${esc(r.name)}</option>`).join('')}</select></label></div><p>إذا لم تحدد رتبة ألعاب، تبقى البداية للإدارة حسب إعدادات البوت.</p></fieldset><fieldset data-stage="2" hidden><legend>اختبر الإعدادات</legend><p>الفحص يقرأ صلاحيات البوت والرومات دون إرسال رسائل.</p><button type="button" class="btn" id="ops-check">فحص الإعدادات</button><div id="ops-results" role="status" aria-live="polite"></div><button class="btn primary" type="submit">حفظ وتطبيق</button></fieldset><div class="actions"><button type="button" class="btn" id="ops-prev">السابق</button><button type="button" class="btn primary" id="ops-next">التالي</button>${demo?'<button type="reset" class="btn">إعادة التجربة</button>':`<a class="btn" href="/dashboard/${cfg.guildId}">رجوع للداشبورد</a>`}</div></form></section>`;}
function candidate(cfg,body,bundle,site){
 const next=structuredClone(cfg);for(const k of Object.keys(SYSTEMS).filter(k=>k!=='heist')){const enabled=body[`feature_${k}`]==='on';if(enabled&&!featureAllowed(site,cfg,k))throw new Error('هذه الميزة تحتاج ترقية الاشتراك.');next.features[k]=enabled;}
 for(const [k,[,type]] of Object.entries(CHANNELS)){const id=String(body[`channel_${k}`]||'');if(id&&!bundle.channels.some(c=>c.id===id&&(type===4?c.type===4:[0,5].includes(c.type))))throw new Error('اختيار روم غير صالح.');next.channels[k]=id;}
 for(const [name,target,key] of [['startRoleIds','games','startRoleIds'],['supportRoleIds','tickets','supportRoleIds']]){const ids=[...new Set([body[name]||[]].flat())];if(ids.length>(name==='supportRoleIds'?limitFor(site,cfg,'ticketSupportRoles'):25)||ids.some(id=>!bundle.roles.some(r=>r.id===id&&!r.managed&&r.id!==bundle.guild.id)))throw new Error('اختيار رتبة غير صالح.');next[target][key]=ids;}
 next.tickets.types=(next.tickets.types||[]).map(t=>({...t,supportRoleIds:next.tickets.supportRoleIds,viewRoleIds:next.tickets.supportRoleIds}));return next;
}
function install(app,ctx){
 const {store,layout,requireLogin,requireOwner,requireGuildAccess,checkCsrf,csrf,botFetch,requireBotSync,pricing,publicSiteConfig,previewPanel}=ctx;
 const events=[];let writeQueue=Promise.resolve();
 const record=(kind,status,guildId='')=>{events.unshift({at:Date.now(),kind,status,guildId});events.splice(100);};ctx.record=record;
 // Log status codes, never request bodies, payment proofs, tokens or raw errors.
 app.use((req,res,next)=>{res.on('finish',()=>{if(res.statusCode>=400&&/^\/(dashboard|owner|api\/bot-sync)/.test(req.path))record(req.path.includes('/send/')?'إرسال لوحة':req.path.includes('redeem')||req.path.includes('payment')?'الاشتراكات':req.method==='POST'?'حفظ الإعدادات':'طلب النظام',res.statusCode,req.params?.guildId||'');});next();});
 app.use((req,res,next)=>{if(req.method!=='GET'||!['/','/premium','/demo','/privacy','/terms'].includes(req.path)||/bot|crawler|spider|preview|headless/i.test(req.get('user-agent')||'')||req.get('purpose')==='prefetch')return next();
 const match=String(req.get('cookie')||'').match(/(?:^|;\s*)zombi_visit=([a-f0-9]{32})\.([a-f0-9]{64})(?:;|$)/);const secret=process.env.SESSION_SECRET||'local-analytics';const sign=id=>crypto.createHmac('sha256',secret).update(id).digest('hex');let id=match&&sign(match[1])===match[2]?match[1]:crypto.randomBytes(16).toString('hex');if(!match||match[1]!==id)res.cookie('zombi_visit',id+'.'+sign(id),{httpOnly:true,sameSite:'lax',secure:req.secure,maxAge:365*86400000});
 const hash=crypto.createHmac('sha256',secret).update('visitor:'+id).digest('hex'),day=new Date().toISOString().slice(0,10);
 writeQueue=writeQueue.then(async()=>{const a=await store.data('site','visitors.json',{views:0,visitors:{},days:{}});a.views++;a.visitors[hash]=Date.now();const d=a.days[day]||(a.days[day]={views:0,visitors:{}});d.views++;d.visitors[hash]=true;for(const key of Object.keys(a.days))if(Date.now()-Date.parse(key)>31*86400000)delete a.days[key];await store.saveData('site','visitors.json',a);}).catch(()=>record('إحصائيات الزيارات',500));next();});
 app.get('/api/public/plans',async(_req,res,next)=>{try{res.set('Cache-Control','no-store').json({html:pricing(publicSiteConfig(await store.getGlobalConfig()))});}catch(e){next(e);}});
 app.get('/demo',async(req,res,next)=>{try{const cfg=require('./guildStore').defaults('demo'),site=await store.getGlobalConfig(),bundle={guild:{id:'demo'},channels:[{id:'100000000000000001',name:'البنك',type:0},{id:'100000000000000002',name:'الألعاب',type:0},{id:'100000000000000003',name:'الدعم',type:0},{id:'100000000000000004',name:'التذاكر',type:4}],roles:[{id:'100000000000000005',name:'الإدارة'},{id:'100000000000000006',name:'فريق الدعم'}]};res.send(layout('تجربة الداشبورد',setupView(cfg,bundle,site,'',true)+`<section class="ops"><h2>جرّب تصميم لوحة</h2>${editor('demo','bank',{},'',true)}</section>`,req.user));}catch(e){next(e);}});
 const base='/dashboard/:guildId';
 app.get(base+'/setup',requireLogin,requireGuildAccess,async(req,res,next)=>{try{res.send(layout('إعداد أول تشغيل',setupView(await store.getConfig(req.params.guildId),req.bundle,await store.getGlobalConfig(),csrf(req)),req.user));}catch(e){next(e);}});
 const check=async(req)=>{const cfg=await store.getConfig(req.params.guildId),site=await store.getGlobalConfig(),next=candidate(cfg,req.body,req.bundle,site),me=await botFetch('/users/@me'),member=await botFetch(`/guilds/${req.params.guildId}/members/${me.id}`);return{cfg:next,checks:inspect(req.bundle,member,next)};};
 app.post(base+'/setup/check',requireLogin,requireGuildAccess,checkCsrf,async(req,res)=>{try{res.json({ok:true,...await check(req)});}catch(e){res.status(400).json({ok:false,error:e.message});}});
 app.post(base+'/setup',requireLogin,requireGuildAccess,checkCsrf,async(req,res)=>{try{const {cfg,checks}=await check(req);if(checks.some(x=>!x.ok))return res.status(400).json({ok:false,error:'عالج مشاكل الصلاحيات قبل الحفظ.',checks});cfg.setupComplete=true;await store.saveConfig(req.params.guildId,cfg);res.json({ok:true,message:'تم حفظ إعدادات السيرفر وتطبيقها.'});}catch(e){res.status(400).json({ok:false,error:e.message});}});
 app.get(base+'/permissions',requireLogin,requireGuildAccess,async(req,res,next)=>{try{const me=await botFetch('/users/@me'),member=await botFetch(`/guilds/${req.params.guildId}/members/${me.id}`),checks=inspect(req.bundle,member,await store.getConfig(req.params.guildId));res.send(layout('صلاحيات البوت',`<section class="ops"><h1>فحص صلاحيات البوت</h1>${checks.map(c=>`<article class="ops-result ${c.ok?'ok':'bad'}">${c.ok?'✓':'!'} ${esc(c.label)}${c.fix?`<p>${esc(c.fix)}</p>`:''}</article>`).join('')}<a class="btn" href="/dashboard/${req.params.guildId}/setup">تعديل الرومات والرتب</a></section>`,req.user));}catch(e){next(e);}});
 app.get(base+'/panels/:which',requireLogin,requireGuildAccess,async(req,res,next)=>{try{if(!Object.keys(SYSTEMS).includes(req.params.which)&&!['roles','name'].includes(req.params.which))return res.sendStatus(404);res.send(layout('معاينة اللوحة',`<section class="ops"><h1>تصميم ومعاينة اللوحة</h1>${editor(req.params.guildId,req.params.which,(await store.getConfig(req.params.guildId)).panelDesigns?.[req.params.which]||{},csrf(req))}</section>`,req.user));}catch(e){next(e);}});
 app.post(base+'/panels/:which',requireLogin,requireGuildAccess,checkCsrf,async(req,res)=>{try{const cfg=await store.getConfig(req.params.guildId),site=await store.getGlobalConfig(),which=req.params.which,key=which==='roles'?'rolePanel':which;if(!['bank','games','tickets','store','roles','name'].includes(which))throw new Error('لوحة غير صالحة.');if(which!=='name'&&!featureAllowed(site,cfg,key))throw new Error('الميزة تحتاج ترقية.');const design=cleanDesign(req.body);if(design.image&&!featureAllowed(site,cfg,'customBotProfile'))throw new Error('تخصيص صورة اللوحة يحتاج اشتراكًا يسمح بتغيير الصور.');cfg.panelDesigns={...(cfg.panelDesigns||{}),[which]:design};const payload=await previewPanel(which,req.params.guildId,req.bundle,cfg);if(req.body.action==='save')await store.saveConfig(req.params.guildId,cfg);res.json({ok:true,payload,message:req.body.action==='save'?'تم حفظ التصميم. استخدم إرسال اللوحة من قسمها في الداشبورد.':'هذه معاينة؛ لم تُرسل رسالة.'});}catch(e){res.status(400).json({ok:false,error:e.message});}});
 app.post('/api/bot-sync/heartbeat',requireBotSync,async(req,res,next)=>{try{await store.saveData('site','heartbeat.json',{at:Date.now(),ready:req.body.ready===true,ping:Math.max(0,Number(req.body.ping)||0),version:String(req.body.version||'').slice(0,20)});res.json({ok:true});}catch(e){next(e);}});
 app.get('/owner/health',requireLogin,requireOwner,async(req,res,next)=>{try{await writeQueue;const [health,beat,site,a]=await Promise.all([store.health(),store.data('site','heartbeat.json',{}),store.getGlobalConfig(),store.data('site','visitors.json',{views:0,visitors:{},days:{}})]);const count=n=>{const ids=new Set();for(const [day,d] of Object.entries(a.days))if(Date.parse(day)>=Date.parse(new Date().toISOString().slice(0,10))-(n-1)*86400000)Object.keys(d.visitors).forEach(id=>ids.add(id));return ids.size;};const live=Date.now()-Number(beat.at||0)<90000;res.send(layout('صحة الأنظمة',`<section class="ops"><h1>صحة الأنظمة وزوار الموقع</h1><div class="ops-grid">${[['زوار فريدون منذ بدء العد',Object.keys(a.visitors).length],['مشاهدات الصفحات',a.views],['زوار اليوم (UTC)',count(1)],['آخر 7 أيام',count(7)],['آخر 30 يوم',count(30)],['اتصال البوت',live?(beat.ready?'متصل':'غير جاهز'):'منقطع أو لا توجد إشارة حديثة'],['حفظ البيانات',health.ok?'متاح':'يوجد خلل']].map(([k,v])=>`<article class="ops-stat"><span>${k}</span><strong>${esc(v)}</strong></article>`).join('')}</div><p>الزائر يُحسب حسب المتصفح بملف تعريف ارتباط. تُستبعد الطلبات الآلية المعروفة وصفحات الإدارة. يبدأ العد بعد تثبيت التحديث.</p><p>آخر إشارة: ${beat.at?esc(new Date(beat.at).toISOString()):'لم تصل بعد'}. السجل أدناه يغطي أخطاء هذه العملية منذ تشغيل الموقع.</p><h2>آخر أخطاء الأنظمة</h2>${events.length?events.map(e=>`<p>${esc(new Date(e.at).toISOString())} · ${esc(e.kind)} · ${e.status}</p>`).join(''):'<p>لا توجد أخطاء مسجلة في هذه الجلسة.</p>'}<h2>إيقاف نظام للطوارئ</h2><p>يمنع الطلبات الجديدة بعد وصول الإعداد للبوت. لا يلغي المعاملات المنفذة ولا يعكس جوائز جولات بدأت سابقًا.</p>${Object.entries(SYSTEMS).map(([k,v])=>`<form method="post" action="/owner/emergency" class="ops-emergency"><input type="hidden" name="_csrf" value="${csrf(req)}"><input type="hidden" name="system" value="${k}"><strong>${v} · ${site.emergency?.[k]?.disabled?'متوقف':'يعمل'}</strong>${field('reason','سبب التوقف',site.emergency?.[k]?.reason||'صيانة مؤقتة')}<button class="btn" name="disabled" value="${site.emergency?.[k]?.disabled?'false':'true'}">${site.emergency?.[k]?.disabled?'إعادة التشغيل':'إيقاف النظام'}</button></form>`).join('')}</section>`,req.user));}catch(e){next(e);}});
 app.post('/owner/emergency',requireLogin,requireOwner,checkCsrf,async(req,res,next)=>{try{if(!Object.hasOwn(SYSTEMS,req.body.system))return res.sendStatus(400);const site=await store.getGlobalConfig();await store.saveGlobalConfig({emergency:{...(site.emergency||{}),[req.body.system]:{disabled:req.body.disabled==='true',reason:String(req.body.reason||'صيانة مؤقتة').slice(0,200),at:Date.now(),by:req.user.id}}});res.redirect('/owner/health');}catch(e){next(e);}});
}
function cleanDesign(b){const image=String(b.image||'').trim();if(image&&!/^https:\/\//i.test(image))throw new Error('رابط الصورة يجب أن يبدأ بـ https://');return{title:String(b.title||'').slice(0,256),description:String(b.description||'').slice(0,2000),image:image.slice(0,1000),buttons:String(b.buttons||'').split(/\r?\n/).map(x=>x.trim().slice(0,80)).slice(0,25)};}
function applyDesign(payload,cfg,which){const d=cfg.panelDesigns?.[which];if(!d)return payload;payload=structuredClone(payload);const e=payload.embeds?.[0];if(e){if(d.title)e.title=d.title;if(d.description)e.description=d.description;if(d.image)e.image={url:d.image};}let n=0;for(const row of payload.components||[])for(const b of row.components||[])if(b.type===2){if(d.buttons?.[n])b.label=d.buttons[n];n++;}return payload;}
function editor(gid,which,d,token,demo=false){return `<form id="ops-editor" method="post" action="/dashboard/${gid}/panels/${which}" data-demo="${demo}"><input type="hidden" name="_csrf" value="${esc(token)}"><div class="ops-grid"><div>${field('title','العنوان (فارغ = الافتراضي)',d.title)}<label>الوصف<textarea name="description" rows="5">${esc(d.description||'')}</textarea></label>${field('image','رابط صورة HTTPS',d.image)}<label>تسميات الأزرار بالترتيب، كل زر بسطر<textarea name="buttons" rows="5">${esc((d.buttons||[]).join('\n'))}</textarea></label><p>تغيير التسميات يحافظ على وظائف الأزرار. الصور تخضع لصلاحيات الخطة.</p><button class="btn" name="action" value="preview">معاينة</button><button class="btn primary" name="action" value="save">حفظ التصميم</button></div><div><div id="ops-panel" class="ops-panel"><p>اضغط معاينة لعرض اللوحة.</p></div><div id="ops-editor-status" role="status" aria-live="polite"></div></div></div></form>`;}
module.exports={install,permissions,inspect,candidate,applyDesign,cleanDesign,SYSTEMS};
