(() => {
  'use strict';
  const root=document.getElementById('z-role-manager'); if(!root)return;
  const gid=root.dataset.guildId,csrf=root.dataset.csrf;
  const $=s=>root.querySelector(s),$$=s=>[...root.querySelectorAll(s)];
  const roleSelect=$('#z-rm-role'),statusEl=$('#z-rm-status'),serverBox=$('#z-rm-server-permissions'),channelsBox=$('#z-rm-channels'),protectBox=$('#z-rm-protection'),adminWarning=$('#z-rm-admin-warning');
  let state=null,currentRole=null,serverDirty=false,securityDirty=false;const dirtyChannels=new Set(),dirtyContent=new Set();
  const groupsOrder=['خطير','الإدارة','القنوات','النص','الصوت','الأعضاء','عام'];
  const safeKeys=new Set(['KickMembers','BanMembers','ManageChannels','ManageGuild','ViewAuditLog','ViewChannel','SendMessages','ManageMessages','EmbedLinks','AttachFiles','ReadMessageHistory','Connect','Speak','MuteMembers','DeafenMembers','MoveMembers','ManageNicknames','ManageRoles','ManageWebhooks','UseApplicationCommands','ManageEvents','ManageThreads','ModerateMembers','CreateEvents','PinMessages','BypassSlowmode']);
  const channelKeys=['ViewChannel','SendMessages','ReadMessageHistory','AttachFiles','EmbedLinks','AddReactions','ManageMessages','MentionEveryone','CreatePublicThreads','CreatePrivateThreads','SendMessagesInThreads','ManageThreads','ManageChannels','PinMessages','BypassSlowmode','Connect','Speak','Stream','MuteMembers','DeafenMembers','MoveMembers'];
  const contentKinds=[['links','🔗 الروابط','أي رابط URL داخل نص الرسالة.'],['videos','🎬 الفيديو','ملفات الفيديو مثل MP4/MOV/WebM.'],['images','🖼️ الصور','ملفات الصور المرفوعة.'],['files','📎 الملفات','الملفات الأخرى غير الصور والفيديو.']];
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  const bitHas=(raw,bit)=>(BigInt(String(raw||'0'))&(1n<<BigInt(bit)))!==0n;
  const perm=k=>state.permissions.find(x=>x.key===k);
  const roleById=id=>state.roles.find(r=>r.id===id);
  const currentOverwrite=(ch,roleId)=>(ch.overwrites||[]).find(o=>o.id===roleId&&o.type===0)||{allow:'0',deny:'0'};
  function overwriteState(ch,key){const p=perm(key);if(!p)return'inherit';const o=currentOverwrite(ch,currentRole.id),b=1n<<BigInt(p.bit);if((BigInt(o.allow)&b)!==0n)return'allow';if((BigInt(o.deny)&b)!==0n)return'deny';return'inherit';}
  function setStatus(text,kind=''){statusEl.textContent=text;statusEl.className=kind?`z-rm-status ${kind}`:'z-rm-status';}
  function markDirty(){setStatus('لديك تغييرات غير محفوظة.','dirty');}
  function roleOptions(selected=''){roleSelect.innerHTML=state.roles.map(r=>`<option value="${r.id}" ${r.id===selected?'selected':''} ${r.managed?'disabled':''}>${r.name}${r.managed?' • Managed':''}</option>`).join('');}
  function renderServer(){if(!currentRole)return;const groups=new Map();for(const p of state.permissions){if(!groups.has(p.group))groups.set(p.group,[]);groups.get(p.group).push(p);}serverBox.innerHTML=groupsOrder.filter(g=>groups.has(g)).map(g=>`<section class="z-rm-perm-group ${g==='خطير'?'danger-zone':''}"><h4>${g}</h4><div class="z-rm-perm-grid">${groups.get(g).map(p=>`<label class="z-rm-perm-item ${p.key==='Administrator'?'admin-perm':''}"><input type="checkbox" data-server-perm="${p.key}" ${bitHas(currentRole.permissions,p.bit)?'checked':''}><span><b>${esc(p.label)}</b><small>${esc(p.desc)}</small></span></label>`).join('')}</div></section>`).join('');serverBox.querySelectorAll('[data-server-perm]').forEach(x=>x.addEventListener('change',()=>{serverDirty=true;markDirty();updateAdminWarning();}));updateAdminWarning();}
  function updateAdminWarning(){const box=serverBox.querySelector('[data-server-perm="Administrator"]');adminWarning.hidden=!(box?.checked);}
  function chType(ch){if(ch.type===4)return'category';if([2,13].includes(ch.type))return'voice';return'text';}
  function chIcon(ch){return ch.type===4?'📁':([2,13].includes(ch.type)?'🔊':'#️⃣');}
  function channelLabel(ch){const parent=state.channels.find(x=>x.id===ch.parentId);return `${chIcon(ch)} ${ch.name}${parent&&ch.type!==4?` · ${parent.name}`:''}`;}
  function presetStates(name){if(name==='hidden')return{ViewChannel:'deny'};if(name==='read')return{ViewChannel:'allow',SendMessages:'deny',ReadMessageHistory:'allow'};if(name==='write')return{ViewChannel:'allow',SendMessages:'allow',ReadMessageHistory:'allow',AttachFiles:'allow',EmbedLinks:'allow',AddReactions:'allow'};if(name==='manage')return{ViewChannel:'allow',SendMessages:'allow',ReadMessageHistory:'allow',AttachFiles:'allow',EmbedLinks:'allow',AddReactions:'allow',ManageMessages:'allow',ManageChannels:'allow',ManageThreads:'allow',PinMessages:'allow'};return{};}
  function renderChannels(){if(!currentRole)return;const q=String($('#z-rm-channel-search')?.value||'').trim().toLowerCase(),filter=$('#z-rm-channel-filter')?.value||'all';const rows=state.channels.filter(ch=>(filter==='all'||chType(ch)===filter)&&(!q||channelLabel(ch).toLowerCase().includes(q)));channelsBox.innerHTML=rows.map(ch=>`<details class="z-rm-channel" data-channel-id="${ch.id}"><summary><span>${esc(channelLabel(ch))}</span><span class="z-rm-channel-summary"><button type="button" data-preset="hidden">مخفي</button><button type="button" data-preset="read">قراءة فقط</button><button type="button" data-preset="write">كتابة</button><button type="button" data-preset="manage">إدارة</button></span></summary><div class="z-rm-channel-grid">${channelKeys.filter(k=>perm(k)?.channel).map(k=>{const p=perm(k),cur=overwriteState(ch,k);return`<label><span><b>${esc(p.label)}</b><small>${esc(p.desc)}</small></span><select data-ch-perm="${k}"><option value="inherit" ${cur==='inherit'?'selected':''}>➖ وراثة</option><option value="allow" ${cur==='allow'?'selected':''}>✅ سماح</option><option value="deny" ${cur==='deny'?'selected':''}>❌ منع</option></select></label>`}).join('')}</div></details>`).join('')||'<div class="hint">لا توجد قنوات مطابقة.</div>';channelsBox.querySelectorAll('[data-ch-perm]').forEach(sel=>sel.addEventListener('change',()=>{dirtyChannels.add(sel.closest('[data-channel-id]').dataset.channelId);markDirty();}));channelsBox.querySelectorAll('[data-preset]').forEach(btn=>btn.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();const row=btn.closest('[data-channel-id]'),map=presetStates(btn.dataset.preset);for(const [key,val] of Object.entries(map)){const sel=row.querySelector(`[data-ch-perm="${key}"]`);if(sel)sel.value=val;}dirtyChannels.add(row.dataset.channelId);markDirty();}));}
  function roleMulti(selected=[]){const set=new Set(selected||[]);return state.roles.map(r=>`<option value="${r.id}" ${set.has(r.id)?'selected':''}>${esc(r.name)}</option>`).join('');}
  function channelMulti(selected=[]){const set=new Set(selected||[]);return state.channels.map(ch=>`<option value="${ch.id}" ${set.has(ch.id)?'selected':''}>${esc(channelLabel(ch))}</option>`).join('');}
  function contentRule(ch,kind){const r=(state.security.channelRules||[]).find(x=>x.roleId===currentRole.id&&x.channelId===ch.id);return r?.[kind]||'inherit';}
  function renderProtection(){if(!currentRole)return;const sec=state.security;protectBox.innerHTML=`<section class="z-rm-security-global"><div class="z-rm-security-head"><div><h3>🧱 الحماية العامة للسيرفر</h3><p>Administrator لا يتجاوز هذه الفلاتر لأنها مطبقة من ZOMBI على الرسائل نفسها.</p></div><label class="z-switch"><input type="checkbox" id="z-sec-enabled" ${sec.enabled!==false?'checked':''}><span>تشغيل الحماية</span></label></div><label class="z-switch"><input type="checkbox" id="z-sec-owner" ${sec.ownerBypass!==false?'checked':''}><span>استثناء مالك السيرفر</span></label><div class="z-rm-content-cards">${contentKinds.map(([kind,title,desc])=>{const c=sec.content[kind]||{};return`<article class="z-rm-content-card" data-content-kind="${kind}"><h4>${title}</h4><p>${desc}</p><label><input type="checkbox" data-sec-enabled ${c.enabled?'checked':''}> تفعيل المنع العام</label><label>الرتب المسموح لها<select multiple data-sec-roles>${roleMulti(c.allowedRoleIds)}</select></label><label>شاتات مستثناة<select multiple data-sec-channels>${channelMulti(c.exemptChannelIds)}</select></label>${kind==='links'?`<label><input type="checkbox" data-sec-discord ${c.allowDiscordLinks?'checked':''}> السماح بروابط Discord الداخلية</label>`:''}</article>`}).join('')}</div></section><section class="z-rm-per-channel-content"><h3>🎯 قواعد خاصة للرتبة: ${esc(currentRole.name)}</h3><p class="hint">المنع الخاص بالرتبة أقوى من السماح. اختر وراثة لاستخدام الحماية العامة.</p><div class="z-rm-content-channel-list">${state.channels.filter(ch=>ch.type!==4).map(ch=>`<div class="z-rm-content-channel" data-content-channel="${ch.id}"><b>${esc(channelLabel(ch))}</b>${contentKinds.map(([kind,title])=>`<label><span>${title}</span><select data-content-rule="${kind}"><option value="inherit" ${contentRule(ch,kind)==='inherit'?'selected':''}>➖ وراثة</option><option value="allow" ${contentRule(ch,kind)==='allow'?'selected':''}>✅ سماح</option><option value="deny" ${contentRule(ch,kind)==='deny'?'selected':''}>❌ منع</option></select></label>`).join('')}</div>`).join('')}</div></section>`;protectBox.querySelectorAll('#z-sec-enabled,#z-sec-owner,[data-sec-enabled],[data-sec-roles],[data-sec-channels],[data-sec-discord]').forEach(x=>x.addEventListener('change',()=>{securityDirty=true;markDirty();}));protectBox.querySelectorAll('[data-content-rule]').forEach(x=>x.addEventListener('change',()=>{dirtyContent.add(x.closest('[data-content-channel]').dataset.contentChannel);markDirty();}));}
  function chooseRole(id){currentRole=roleById(id)||state.roles.find(r=>!r.managed)||null;if(!currentRole)return;roleSelect.value=currentRole.id;serverDirty=false;dirtyChannels.clear();dirtyContent.clear();renderServer();renderChannels();renderProtection();setStatus(`جاهز لتعديل رتبة ${currentRole.name}.`);}
  async function load(preserve=true){setStatus('جاري قراءة الصلاحيات الحالية من Discord...');const old=preserve?currentRole?.id:'';const res=await fetch(`/dashboard/${gid}/role-manager/state`,{headers:{Accept:'application/json'}}),data=await res.json();if(!res.ok||!data.ok)throw new Error(data.message||'تعذر تحميل الصلاحيات.');state=data;roleOptions(old);chooseRole((old&&roleById(old)&&!roleById(old).managed)?old:(state.roles.find(r=>!r.managed)?.id||''));}
  function collectSecurity(){const out={enabled:$('#z-sec-enabled')?.checked!==false,ownerBypass:$('#z-sec-owner')?.checked!==false,content:{}};protectBox.querySelectorAll('[data-content-kind]').forEach(card=>{const kind=card.dataset.contentKind;out.content[kind]={enabled:card.querySelector('[data-sec-enabled]')?.checked===true,allowedRoleIds:[...(card.querySelector('[data-sec-roles]')?.selectedOptions||[])].map(o=>o.value),exemptChannelIds:[...(card.querySelector('[data-sec-channels]')?.selectedOptions||[])].map(o=>o.value),...(kind==='links'?{allowDiscordLinks:card.querySelector('[data-sec-discord]')?.checked===true}:{})};});return out;}
  async function save(){if(!currentRole)return;const btn=$('#z-rm-save');btn.disabled=true;setStatus('جاري تطبيق التغييرات على Discord...');const serverPermissions=[...serverBox.querySelectorAll('[data-server-perm]:checked')].map(x=>x.dataset.serverPerm);const channelChanges=[...dirtyChannels].map(id=>{const row=channelsBox.querySelector(`[data-channel-id="${CSS.escape(id)}"]`);const states={};row?.querySelectorAll('[data-ch-perm]').forEach(x=>states[x.dataset.chPerm]=x.value);return{channelId:id,states};});const contentChanges=[...dirtyContent].map(id=>{const row=protectBox.querySelector(`[data-content-channel="${CSS.escape(id)}"]`),x={channelId:id};row?.querySelectorAll('[data-content-rule]').forEach(s=>x[s.dataset.contentRule]=s.value);return x;});try{const res=await fetch(`/dashboard/${gid}/role-manager/apply`,{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':csrf,Accept:'application/json'},body:JSON.stringify({roleId:currentRole.id,serverPermissionsDirty:serverDirty,serverPermissions,channelChanges,contentChanges,security:collectSecurity()})}),data=await res.json();if(!res.ok&&!data.partial)throw new Error(data.message||'فشل الحفظ.');const msg=[data.message,data.channelsUpdated?`تم تحديث ${data.channelsUpdated} قناة.`:'',data.warning||'',...(data.errors||[])].filter(Boolean).join(' ');await load(true);setStatus(msg,data.partial?'warn':'ok');}catch(e){setStatus(`❌ ${e.message}`,'bad');}finally{btn.disabled=false;}}
  $$('.z-rm-tabs [data-rm-tab]').forEach(btn=>btn.addEventListener('click',()=>{$$('.z-rm-tabs [data-rm-tab]').forEach(x=>x.classList.toggle('active',x===btn));$$('[data-rm-view]').forEach(x=>x.hidden=x.dataset.rmView!==btn.dataset.rmTab);}));
  roleSelect.addEventListener('change',()=>chooseRole(roleSelect.value));$('#z-rm-reload').addEventListener('click',()=>load(true).catch(e=>setStatus(`❌ ${e.message}`,'bad')));$('#z-rm-save').addEventListener('click',save);$('#z-rm-safe-preset').addEventListener('click',()=>{if(!currentRole)return;serverBox.querySelectorAll('[data-server-perm]').forEach(x=>x.checked=safeKeys.has(x.dataset.serverPerm));serverDirty=true;updateAdminWarning();markDirty();});$('#z-rm-channel-search').addEventListener('input',renderChannels);$('#z-rm-channel-filter').addEventListener('change',renderChannels);
  load(false).catch(e=>setStatus(`❌ ${e.message}`,'bad'));
})();
