'use strict';
const local = require('./guildStore');
const { normalizeGameContent, DEFAULT_GAME_CONTENT } = require('./gameDefaults');
const {
  normalizePlans, mergePlans, applySubscription, planNameForConfig,
  configuredPlanForConfig, premiumUntilForConfig, normalizePlanId
} = require('./planPolicy');
let pool=null; let readyPromise=null;
function dbEnabled(){return Boolean(String(process.env.DATABASE_URL||'').trim());}
function clone(v){return JSON.parse(JSON.stringify(v));}
function jsonParam(v){return JSON.stringify(v ?? {});}
function stableJson(v){if(Array.isArray(v))return v.map(stableJson);if(v&&typeof v==='object'){const out={};for(const k of Object.keys(v).sort())out[k]=stableJson(v[k]);return out;}return v;}
function sameJson(a,b){try{return JSON.stringify(stableJson(a))===JSON.stringify(stableJson(b));}catch{return false;}}
function planRank(p){return normalizePlanId(p)==='premium_plus'?2:normalizePlanId(p)==='premium'?1:0;}
function activeUntil(v){const n=Number(v||0);return Number.isFinite(n)&&n>0?n:0;}
function explicitLegacyLifetime(cfg){const p=configuredPlanForConfig(cfg);return p!=='free'&&!premiumUntilForConfig(cfg)?Number.MAX_SAFE_INTEGER:0;}
function entitlementFromConfig(cfg){const plan=planNameForConfig(cfg);if(plan==='free')return null;return{plan,premiumUntil:premiumUntilForConfig(cfg)||explicitLegacyLifetime(cfg)};}
function bestEntitlement(items=[]){const now=Date.now();let best=null;for(const raw of items){const plan=normalizePlanId(raw?.plan),until=activeUntil(raw?.premiumUntil);if(plan==='free'||until<=now)continue;const cur={plan,premiumUntil:until};if(!best||planRank(cur.plan)>planRank(best.plan)||(planRank(cur.plan)===planRank(best.plan)&&cur.premiumUntil>best.premiumUntil))best=cur;}return best;}
async function ensureDb(){
  if(!dbEnabled()) return null;
  if(pool) return pool;
  const { Pool } = require('pg');
  const rawUrl = String(process.env.DATABASE_URL || '').trim();
  const sslDisabled = String(process.env.DATABASE_SSL || '').toLowerCase() === 'false';
  const dbUrl = new URL(rawUrl);dbUrl.searchParams.delete('sslmode');dbUrl.searchParams.delete('channel_binding');
  pool = new Pool({connectionString:dbUrl.toString(),max:8,ssl:sslDisabled?false:{rejectUnauthorized:false}});
  readyPromise=(async()=>{
    await pool.query(`CREATE TABLE IF NOT EXISTS zombi_guild_config (guild_id TEXT PRIMARY KEY, config JSONB NOT NULL, updated_at BIGINT NOT NULL)`);
    await pool.query(`CREATE TABLE IF NOT EXISTS zombi_guild_data (guild_id TEXT NOT NULL, name TEXT NOT NULL, data JSONB NOT NULL, updated_at BIGINT NOT NULL, PRIMARY KEY (guild_id, name))`);
    await pool.query(`CREATE TABLE IF NOT EXISTS zombi_global_config (id INTEGER PRIMARY KEY, data JSONB NOT NULL, updated_at BIGINT NOT NULL)`);
    await pool.query(`CREATE TABLE IF NOT EXISTS zombi_premium_codes (code TEXT PRIMARY KEY, days INTEGER NOT NULL, created_at BIGINT NOT NULL, used_at BIGINT NOT NULL DEFAULT 0, used_by_guild_id TEXT NOT NULL DEFAULT '')`);
    await pool.query(`ALTER TABLE zombi_premium_codes ADD COLUMN IF NOT EXISTS plan TEXT NOT NULL DEFAULT 'premium'`);
    await pool.query(`CREATE TABLE IF NOT EXISTS zombi_web_sessions (sid TEXT PRIMARY KEY, sess JSONB NOT NULL, expire_at BIGINT NOT NULL)`);
    await pool.query(`CREATE TABLE IF NOT EXISTS zombi_subscription_entitlements (guild_id TEXT PRIMARY KEY, plan TEXT NOT NULL, premium_until BIGINT NOT NULL DEFAULT 0, updated_at BIGINT NOT NULL)`);
  })();
  await readyPromise;return pool;
}
async function entitlementRow(p,gid){const r=await p.query('SELECT plan,premium_until,updated_at FROM zombi_subscription_entitlements WHERE guild_id=$1',[String(gid)]);return r.rows[0]||null;}
async function putEntitlement(p,gid,plan,until,updatedAt=Date.now()){plan=normalizePlanId(plan);until=plan==='free'?0:activeUntil(until);const stamp=Math.max(1,Number(updatedAt)||Date.now());await p.query(`INSERT INTO zombi_subscription_entitlements(guild_id,plan,premium_until,updated_at) VALUES($1,$2,$3,$4) ON CONFLICT(guild_id) DO UPDATE SET plan=EXCLUDED.plan,premium_until=EXCLUDED.premium_until,updated_at=CASE WHEN zombi_subscription_entitlements.plan IS DISTINCT FROM EXCLUDED.plan OR zombi_subscription_entitlements.premium_until IS DISTINCT FROM EXCLUDED.premium_until THEN EXCLUDED.updated_at ELSE zombi_subscription_entitlements.updated_at END`,[String(gid),plan,until,stamp]);}
async function relationExists(p,name){try{const r=await p.query('SELECT to_regclass($1) AS name',[`public.${name}`]);return Boolean(r.rows[0]?.name);}catch{return false;}}
async function recoverHistoricalEntitlement(p,gid){
  const candidates=[];const day=86400000;
  try{if(await relationExists(p,'zombi_payment_requests')){const r=await p.query(`SELECT plan,days,created_at,reviewed_at FROM zombi_payment_requests WHERE guild_id=$1 AND status='approved' ORDER BY COALESCE(NULLIF(reviewed_at,0),created_at) DESC LIMIT 20`,[String(gid)]);for(const x of r.rows){const start=Number(x.reviewed_at||x.created_at||0),days=Math.max(1,Number(x.days||30));if(start)candidates.push({plan:x.plan,premiumUntil:start+days*day});}}}catch{}
  try{const r=await p.query(`SELECT plan,days,used_at FROM zombi_premium_codes WHERE used_by_guild_id=$1 AND used_at>0 ORDER BY used_at DESC LIMIT 20`,[String(gid)]);for(const x of r.rows){const start=Number(x.used_at||0),days=Math.max(1,Number(x.days||30));if(start)candidates.push({plan:x.plan,premiumUntil:start+days*day});}}catch{}
  return bestEntitlement(candidates);
}
async function resolveEntitlement(p,gid,rawCfg){
  const row=await entitlementRow(p,gid);
  // A Free row is an explicit Owner cancellation: never resurrect an older payment/code after that.
  if(row&&normalizePlanId(row.plan)==='free')return null;
  const rowEnt=row?{plan:normalizePlanId(row.plan),premiumUntil:Number(row.premium_until||0)}:null;
  const fromCfg=entitlementFromConfig(rawCfg||{});
  const historical=await recoverHistoricalEntitlement(p,gid);
  const best=bestEntitlement([rowEnt,fromCfg,historical]);
  if(best){await putEntitlement(p,gid,best.plan,best.premiumUntil,Number(row?.updated_at||0)||Date.now());return best;}
  return null;
}
function applyRecovered(cfg,ent){if(!ent)return cfg;const current=planNameForConfig(cfg),until=premiumUntilForConfig(cfg)||explicitLegacyLifetime(cfg);if(planRank(ent.plan)>planRank(current)||(planRank(ent.plan)===planRank(current)&&Number(ent.premiumUntil)>Number(until))){cfg.plan=normalizePlanId(ent.plan);cfg.premiumUntil=Number(ent.premiumUntil);}return cfg;}
async function getConfig(guildId){if(!dbEnabled())return local.getConfig(guildId);const p=await ensureDb(),id=String(guildId),r=await p.query('SELECT config FROM zombi_guild_config WHERE guild_id=$1',[id]),raw=r.rows[0]?.config||local.defaults(id),ent=await resolveEntitlement(p,id,raw),cfg=local.normalizeConfig(applyRecovered(local.normalizeConfig(raw,id),ent),id);if(!sameJson(raw,cfg))await p.query(`INSERT INTO zombi_guild_config(guild_id,config,updated_at) VALUES($1,$2::jsonb,$3) ON CONFLICT(guild_id) DO UPDATE SET config=EXCLUDED.config,updated_at=EXCLUDED.updated_at`,[id,jsonParam(cfg),Date.now()]);const e=entitlementFromConfig(cfg);if(e)await putEntitlement(p,id,e.plan,e.premiumUntil,Number(cfg.subscriptionUpdatedAt||0)||Date.now());return clone(cfg);}
async function saveConfig(guildId,input){if(!dbEnabled())return local.saveConfig(guildId,input);const p=await ensureDb(),id=String(guildId),cfg=local.normalizeConfig(input,id);await p.query(`INSERT INTO zombi_guild_config(guild_id,config,updated_at) VALUES($1,$2::jsonb,$3) ON CONFLICT(guild_id) DO UPDATE SET config=EXCLUDED.config,updated_at=EXCLUDED.updated_at`,[id,jsonParam(cfg),Date.now()]);const e=entitlementFromConfig(cfg);if(e)await putEntitlement(p,id,e.plan,e.premiumUntil,Number(cfg.subscriptionUpdatedAt||0)||Date.now());return clone(cfg);}
async function patchConfig(guildId,patch){const current=await getConfig(guildId),next=clone(current);for(const [section,value] of Object.entries(patch||{}))next[section]=(value&&typeof value==='object'&&!Array.isArray(value))?{...(next[section]||{}),...value}:value;return saveConfig(guildId,next);}
async function data(guildId,name,fallback={}){if(!dbEnabled())return local.data(guildId,name,fallback);const p=await ensureDb(),r=await p.query('SELECT data FROM zombi_guild_data WHERE guild_id=$1 AND name=$2',[String(guildId),String(name)]);return clone(r.rows[0]?.data??fallback);}
async function saveData(guildId,name,value){if(!dbEnabled())return local.saveData(guildId,name,value);const p=await ensureDb();await p.query(`INSERT INTO zombi_guild_data(guild_id,name,data,updated_at) VALUES($1,$2,$3::jsonb,$4) ON CONFLICT(guild_id,name) DO UPDATE SET data=EXCLUDED.data,updated_at=EXCLUDED.updated_at`,[String(guildId),String(name),jsonParam(value),Date.now()]);return clone(value);}
async function getGameContent(guildId){if(!dbEnabled())return local.getGameContent(guildId);const raw=await data(guildId,'game-content.json',DEFAULT_GAME_CONTENT);const normalized=normalizeGameContent(raw);if(JSON.stringify(raw)!==JSON.stringify(normalized))await saveData(guildId,'game-content.json',normalized);return clone(normalized);}
async function saveGameContent(guildId,input){const normalized=normalizeGameContent(input);if(!dbEnabled())return local.saveGameContent(guildId,normalized);return saveData(guildId,'game-content.json',normalized);}
function ensureUserShape(u={}){return{balance:Number(u.balance||0),bankBalance:Number(u.bankBalance||0),messageCount:Number(u.messageCount||0),lastDaily:Number(u.lastDaily||0),lastMessageReward:Number(u.lastMessageReward||0),lastTransfer:Number(u.lastTransfer||0),xp:Number(u.xp||0),level:Number(u.level||0),purchases:Array.isArray(u.purchases)?u.purchases:[]};}
async function getEconomy(guildId){return data(guildId,'economy.json',{});} async function getUser(guildId,userId){if(!dbEnabled())return local.getUser(guildId,userId);return updateUser(guildId,userId,()=>{});}
async function updateUser(guildId,userId,fn){if(!dbEnabled())return local.updateUser(guildId,userId,fn);const p=await ensureDb(),c=await p.connect();try{await c.query('BEGIN');const gid=String(guildId),name='economy.json',r=await c.query('SELECT data FROM zombi_guild_data WHERE guild_id=$1 AND name=$2 FOR UPDATE',[gid,name]),econ=clone(r.rows[0]?.data||{}),u=ensureUserShape(econ[String(userId)]);await fn(u,econ);econ[String(userId)]=u;await c.query(`INSERT INTO zombi_guild_data(guild_id,name,data,updated_at) VALUES($1,$2,$3::jsonb,$4) ON CONFLICT(guild_id,name) DO UPDATE SET data=EXCLUDED.data,updated_at=EXCLUDED.updated_at`,[gid,name,jsonParam(econ),Date.now()]);await c.query('COMMIT');return clone(u);}catch(e){await c.query('ROLLBACK').catch(()=>{});throw e;}finally{c.release();}}
async function transferBalance(guildId,fromId,toId,amount){amount=Math.max(1,Math.round(Number(amount)||0));if(!dbEnabled()){const e=local.getEconomy(guildId),from=ensureUserShape(e[fromId]),to=ensureUserShape(e[toId]);if(from.balance<amount)return{ok:false};from.balance-=amount;to.balance+=amount;e[fromId]=from;e[toId]=to;local.saveData(guildId,'economy.json',e);return{ok:true,from,to};}const p=await ensureDb(),c=await p.connect();try{await c.query('BEGIN');const gid=String(guildId),name='economy.json',r=await c.query('SELECT data FROM zombi_guild_data WHERE guild_id=$1 AND name=$2 FOR UPDATE',[gid,name]),e=clone(r.rows[0]?.data||{}),from=ensureUserShape(e[String(fromId)]),to=ensureUserShape(e[String(toId)]);if(from.balance<amount){await c.query('ROLLBACK');return{ok:false};}from.balance-=amount;to.balance+=amount;e[String(fromId)]=from;e[String(toId)]=to;await c.query(`INSERT INTO zombi_guild_data(guild_id,name,data,updated_at) VALUES($1,$2,$3::jsonb,$4) ON CONFLICT(guild_id,name) DO UPDATE SET data=EXCLUDED.data,updated_at=EXCLUDED.updated_at`,[gid,name,jsonParam(e),Date.now()]);await c.query('COMMIT');return{ok:true,from:clone(from),to:clone(to)};}catch(e){await c.query('ROLLBACK').catch(()=>{});throw e;}finally{c.release();}}
async function allGuildIds(){if(!dbEnabled())return local.allGuildIds();const p=await ensureDb(),r=await p.query('SELECT guild_id FROM zombi_guild_config ORDER BY updated_at DESC');return r.rows.map(x=>x.guild_id);}
function isPremium(cfg){return local.isPremium(cfg);}
async function setPremium(guildId,days=30,plan='premium'){const cfg=await saveConfig(guildId,applySubscription(await getConfig(guildId),days,plan));if(dbEnabled()){const p=await ensureDb(),e=entitlementFromConfig(cfg);if(e)await putEntitlement(p,guildId,e.plan,e.premiumUntil,Number(cfg.subscriptionUpdatedAt||0)||Date.now());}return cfg;}
async function removePremium(guildId){const cfg=await getConfig(guildId);cfg.plan='free';cfg.premiumUntil=0;cfg.subscriptionUpdatedAt=Date.now();if(!dbEnabled())return local.saveConfig(guildId,cfg);const p=await ensureDb(),id=String(guildId),normalized=local.normalizeConfig(cfg,id);await p.query(`INSERT INTO zombi_guild_config(guild_id,config,updated_at) VALUES($1,$2::jsonb,$3) ON CONFLICT(guild_id) DO UPDATE SET config=EXCLUDED.config,updated_at=EXCLUDED.updated_at`,[id,jsonParam(normalized),Date.now()]);await putEntitlement(p,id,'free',0,cfg.subscriptionUpdatedAt);return clone(normalized);}
function normalizeGlobal(input={}){return local.normalizeGlobalConfig?local.normalizeGlobalConfig(input):{...input,plans:normalizePlans(input.plans||{})};}
async function getGlobalConfig(){if(!dbEnabled())return local.getGlobalConfig();const p=await ensureDb(),r=await p.query('SELECT data FROM zombi_global_config WHERE id=1');return normalizeGlobal(r.rows[0]?.data||{});}
async function saveGlobalConfig(input={}){if(!dbEnabled())return local.saveGlobalConfig(input);const p=await ensureDb(),current=await getGlobalConfig(),merged={...current,...input,plans:input.plans?mergePlans(current.plans,input.plans):current.plans},next=normalizeGlobal(merged);await p.query(`INSERT INTO zombi_global_config(id,data,updated_at) VALUES(1,$1::jsonb,$2) ON CONFLICT(id) DO UPDATE SET data=EXCLUDED.data,updated_at=EXCLUDED.updated_at`,[jsonParam(next),Date.now()]);return clone(next);}
async function getCodes(){if(!dbEnabled())return local.getCodes();const p=await ensureDb(),r=await p.query('SELECT code,plan,days,created_at,used_at,used_by_guild_id FROM zombi_premium_codes ORDER BY created_at ASC');return r.rows.map(x=>({code:x.code,plan:x.plan||'premium',days:Number(x.days),createdAt:Number(x.created_at),usedAt:Number(x.used_at),usedByGuildId:x.used_by_guild_id}));}
async function createCode(days=30,plan='premium'){plan=normalizePlanId(plan);if(!['premium','premium_plus'].includes(plan))throw new Error('خطة غير صالحة.');if(!dbEnabled())return local.createCode(days,plan);const p=await ensureDb(),chars='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';let code='';for(let tries=0;tries<10;tries++){let s='ZOMBI-';for(let i=0;i<12;i++)s+=chars[Math.floor(Math.random()*chars.length)];try{await p.query(`INSERT INTO zombi_premium_codes(code,days,created_at,used_at,used_by_guild_id,plan) VALUES($1,$2,$3,0,'',$4)`,[s,Math.max(1,Math.min(3650,Math.round(Number(days)||30))),Date.now(),plan]);code=s;break;}catch(e){if(e.code!=='23505')throw e;}}if(!code)throw new Error('تعذر إنشاء كود.');return{code,plan,days:Math.max(1,Math.min(3650,Math.round(Number(days)||30))),createdAt:Date.now(),usedAt:0,usedByGuildId:''};}
async function redeemCode(guildId,code){if(!dbEnabled())return local.redeemCode(guildId,code);const p=await ensureDb(),c=await p.connect();try{await c.query('BEGIN');const r=await c.query('SELECT * FROM zombi_premium_codes WHERE code=$1 FOR UPDATE',[String(code||'').trim().toUpperCase()]),row=r.rows[0];if(!row)throw new Error('كود التفعيل غير صحيح.');if(Number(row.used_at||0))throw new Error('هذا الكود مستخدم مسبقًا.');await c.query('SELECT pg_advisory_xact_lock(hashtext($1))',[String(guildId)]);const cr=await c.query('SELECT config FROM zombi_guild_config WHERE guild_id=$1 FOR UPDATE',[String(guildId)]),cfg=local.normalizeConfig(cr.rows[0]?.config||{},String(guildId));if(planNameForConfig(cfg)==='premium_plus'&&normalizePlanId(row.plan)==='premium')throw new Error('لديك Premium+ فعّال؛ استخدم هذا الكود بعد انتهاء اشتراكك.');const normalized=local.normalizeConfig(applySubscription(cfg,Number(row.days),row.plan||'premium'),String(guildId));await c.query(`INSERT INTO zombi_guild_config(guild_id,config,updated_at) VALUES($1,$2::jsonb,$3) ON CONFLICT(guild_id) DO UPDATE SET config=EXCLUDED.config,updated_at=EXCLUDED.updated_at`,[String(guildId),jsonParam(normalized),Date.now()]);const now=Date.now();await c.query('UPDATE zombi_premium_codes SET used_at=$1,used_by_guild_id=$2 WHERE code=$3',[now,String(guildId),row.code]);const e=entitlementFromConfig(normalized);if(e)await c.query(`INSERT INTO zombi_subscription_entitlements(guild_id,plan,premium_until,updated_at) VALUES($1,$2,$3,$4) ON CONFLICT(guild_id) DO UPDATE SET plan=EXCLUDED.plan,premium_until=EXCLUDED.premium_until,updated_at=EXCLUDED.updated_at`,[String(guildId),e.plan,e.premiumUntil,now]);await c.query('COMMIT');return{item:{code:row.code,plan:row.plan||'premium',days:Number(row.days),createdAt:Number(row.created_at),usedAt:now,usedByGuildId:String(guildId)},config:normalized};}catch(e){await c.query('ROLLBACK').catch(()=>{});throw e;}finally{c.release();}}
async function health(){if(!dbEnabled())return{mode:'local-json',ok:true};try{const p=await ensureDb();await p.query('SELECT 1');return{mode:'postgres',ok:true};}catch(e){return{mode:'postgres',ok:false,error:e.message};}}
module.exports={dbEnabled,ensureDb,getConfig,saveConfig,patchConfig,data,saveData,getGameContent,saveGameContent,getEconomy,getUser,updateUser,transferBalance,allGuildIds,isPremium,setPremium,removePremium,getGlobalConfig,saveGlobalConfig,getCodes,createCode,redeemCode,health};
