'use strict';

// Templates are data-only. Permissions use Discord permission names and are
// converted to bitfields by the executor; no destructive operations are used.
const role = (name, color, permissions = []) => ({ name, color, permissions });
const text = (name, allow = [], deny = []) => ({ name, type: 0, allow, deny });
const voice = (name, allow = [], deny = []) => ({ name, type: 2, allow, deny });
const cat = (name, channels, roleAccess = {}) => ({ name, channels, roleAccess });
const staff = ['Owner','Co Owner','Management','Admin','Moderator'];
const adminView = ['Owner','Co Owner','Management','Admin'];
const memberRead = ['Member','Friends','Customer','Gamer','Student','Participant','Employee','VIP'];
const commonRoles = [role('Owner','#e74c3c',['Administrator']),role('Admin','#e67e22',['ManageChannels','ManageMessages','KickMembers','BanMembers','ViewAuditLog']),role('Moderator','#3498db',['ManageMessages','KickMembers']),role('VIP','#9b59b6'),role('Member','#95a5a6'),role('Bots','#5865f2')];

const templates = [
 {id:'friends',name:'سيرفر أصدقاء',category:'بسيطة',plan:'free',icon:'🎮',description:'سيرفر خفيف للأصدقاء مع قنوات عامة وألعاب وفويسات.',features:['رتب بسيطة','فويسات للألعاب','قنوات اقتراحات'],roles:[role('Owner','#e74c3c',['Administrator']),role('Admin','#e67e22',['ManageChannels','ManageMessages']),role('Friends','#3498db'),role('VIP','#9b59b6'),role('Bots','#5865f2')],categories:[cat('📌・المعلومات',[text('القوانين',[],['SendMessages']),text('الإعلانات',[],['SendMessages'])]),cat('💬・المجتمع',[text('العام',['ViewChannel','SendMessages']),text('الاقتراحات',['ViewChannel','SendMessages'])]),cat('🎮・الألعاب',[voice('فويس عام'),voice('فويس ألعاب')]),cat('🔒・الإدارة',[text('شات الإدارة',[],['ViewChannel']),text('سجلات الإدارة',[],['ViewChannel'])],{Owner:['ViewChannel'],Admin:['ViewChannel']})]},
 {id:'simple',name:'سيرفر بسيط جدًا',category:'بسيطة',plan:'free',icon:'✨',description:'هيكل أساسي جدًا مناسب للبدء السريع.',features:['قنوات أساسية','رتب قليلة','إدارة خاصة'],roles:[role('Owner','#e74c3c',['Administrator']),role('Admin','#e67e22',['ManageChannels','ManageMessages']),role('Member','#3498db'),role('Bots','#5865f2')],categories:[cat('📌・البداية',[text('القوانين',[],['SendMessages']),text('الإعلانات',[],['SendMessages'])]),cat('💬・الشات',[text('العام'),text('الصور'),voice('فويس عام'),voice('فويس 2')]),cat('🔒・الإدارة',[text('شات الإدارة',[],['ViewChannel'])],{Owner:['ViewChannel'],Admin:['ViewChannel']})]},
 {id:'community-small',name:'مجتمع صغير',category:'بسيطة',plan:'free',icon:'🏡',description:'مجتمع صغير مع اقتراحات ومساعدة وفويسات.',features:['مجتمع','اقتراحات','مساعدة'],roles:[role('Owner','#e74c3c',['Administrator']),role('Moderator','#3498db',['ManageMessages']),role('Member','#95a5a6'),role('Bots','#5865f2')],categories:[cat('📌・المعلومات',[text('القوانين',[],['SendMessages']),text('الإعلانات',[],['SendMessages'])]),cat('🌍・المجتمع',[text('العام'),text('الصور-والمقاطع'),text('الاقتراحات'),text('المساعدة'),voice('فويس عام'),voice('فويس 2')]),cat('🔒・الفريق',[text('شات الفريق',[],['ViewChannel'])],{Owner:['ViewChannel'],Moderator:['ViewChannel']})]},
 {id:'fivem-general',name:'FiveM عام وRoleplay',category:'FiveM وRoleplay',plan:'premium_plus',icon:'🚔',description:'هيكل RP متكامل مع أقسام الشرطة والإسعاف والعصابات والإدارة.',features:['رتب وظائف','قنوات خاصة حسب الرتبة','دعم وتقارير'],roles:[role('Owner','#e74c3c',['Administrator']),role('Co Owner','#c0392b',['ManageGuild','ManageChannels','ManageRoles']),role('Management','#8e44ad',['ManageChannels','ManageMessages','ViewAuditLog']),role('Admin','#e67e22',['ManageChannels','ManageMessages','KickMembers']),role('Moderator','#3498db',['ManageMessages','KickMembers']),role('Police','#2980b9'),role('EMS','#2ecc71'),role('Gang','#8e44ad'),role('VIP','#f1c40f'),role('Member','#95a5a6'),role('Bots','#5865f2')],categories:[cat('📌・معلومات السيرفر',[text('القوانين',[],['SendMessages']),text('الإعلانات',[],['SendMessages']),text('الأخبار'),text('التحديثات')]),cat('💬・المجتمع',[text('العام'),text('الشاتات'),text('الصور-والمقاطع'),voice('انتظار'),voice('فويس عام 1'),voice('فويس عام 2')]),cat('🎮・FiveM',[text('معلومات الدخول'),text('مشاكل اللعبة'),text('تقديمات الوظائف')]),cat('🚔・الشرطة',[text('إعلانات الشرطة',[],['ViewChannel']),text('نقاشات الشرطة',[],['ViewChannel']),text('تقارير الشرطة',[],['ViewChannel']),voice('فويس الشرطة',[],['ViewChannel'])],{Owner:['ViewChannel'],'Co Owner':['ViewChannel'],Management:['ViewChannel'],Admin:['ViewChannel'],Police:['ViewChannel']}),cat('🚑・الإسعاف',[text('إعلانات الإسعاف',[],['ViewChannel']),text('تقارير الإسعاف',[],['ViewChannel']),voice('فويس الإسعاف',[],['ViewChannel'])],{Owner:['ViewChannel'],'Co Owner':['ViewChannel'],Management:['ViewChannel'],Admin:['ViewChannel'],EMS:['ViewChannel']}),cat('🔫・العصابات',[text('إعلانات العصابات',[],['ViewChannel']),text('تنسيق العصابات',[],['ViewChannel']),voice('فويس العصابات',[],['ViewChannel'])],{Owner:['ViewChannel'],'Co Owner':['ViewChannel'],Management:['ViewChannel'],Admin:['ViewChannel'],Gang:['ViewChannel']}),cat('🎫・الدعم',[text('فتح-تذكرة'),text('الشكاوى'),text('المساعدة')]),cat('🔒・الإدارة',[text('شات الإدارة',[],['ViewChannel']),text('سجلات الإدارة',[],['ViewChannel']),voice('فويس الإدارة',[],['ViewChannel']),voice('اجتماعات خاصة',[],['ViewChannel'])],{Owner:['ViewChannel'],'Co Owner':['ViewChannel'],Management:['ViewChannel'],Admin:['ViewChannel'],Moderator:['ViewChannel']})]},
 {id:'fivem-friends',name:'FiveM للأصدقاء',category:'FiveM وRoleplay',plan:'premium',icon:'🚗',description:'قنوات FiveM خاصة بمجموعة أصدقاء صغيرة.',features:['معلومات دخول','تجارب لعب','فويسات'],roles:[role('Owner','#e74c3c',['Administrator']),role('Admin','#e67e22',['ManageChannels','ManageMessages']),role('Driver','#3498db'),role('Friends','#2ecc71'),role('Bots','#5865f2')],categories:[cat('📌・المعلومات',[text('القوانين',[],['SendMessages']),text('معلومات-الدخول')]),cat('🚗・FiveM',[text('العام'),text('الاقتراحات'),text('مشاكل-اللعبة'),voice('فويس عام'),voice('فويس قيادة')]),cat('🔒・الإدارة',[text('شات الإدارة',[],['ViewChannel'])],{Owner:['ViewChannel'],Admin:['ViewChannel']})]},
 {id:'gaming',name:'مجتمع ألعاب متكامل',category:'الألعاب',plan:'premium',icon:'🕹️',description:'مجتمع ألعاب عام مع البحث عن لاعبين وأقسام الألعاب والفعاليات.',features:['Minecraft وRoblox وValorant وFortnite','فعاليات','فويسات جماعية'],roles:[role('Owner','#e74c3c',['Administrator']),role('Admin','#e67e22',['ManageChannels','ManageMessages','KickMembers']),role('Moderator','#3498db',['ManageMessages']),role('Event Manager','#16a085',['ManageEvents','ManageMessages']),role('VIP','#9b59b6'),role('Gamer','#2ecc71'),role('Member','#95a5a6'),role('Bots','#5865f2')],categories:[cat('📌・المعلومات',[text('القوانين',[],['SendMessages']),text('الإعلانات',[],['SendMessages'])]),cat('💬・المجتمع',[text('العام'),text('البحث-عن-لاعبين'),text('المقاطع'),text('الاقتراحات')]),cat('🎮・الألعاب',[text('Minecraft'),text('Roblox'),text('Valorant'),text('Fortnite'),voice('ألعاب 1'),voice('ألعاب 2'),voice('ألعاب 3')]),cat('🏆・الفعاليات',[text('الفعاليات'),text('النتائج'),voice('فويس فعاليات')]),cat('🔒・الإدارة',[text('شات الإدارة',[],['ViewChannel']),voice('فويس الإدارة',[],['ViewChannel'])],{Owner:['ViewChannel'],Admin:['ViewChannel'],Moderator:['ViewChannel']})]},
 {id:'minecraft',name:'Minecraft',category:'الألعاب',plan:'premium',icon:'⛏️',description:'سيرفر مجتمع Minecraft للتحديثات والسيرفرات والبناء والبحث عن لاعبين.',features:['أقسام لعب','دعم تقني','فويسات'],roles:[role('Owner','#e74c3c',['Administrator']),role('Admin','#e67e22',['ManageChannels','ManageMessages']),role('Builder','#2ecc71'),role('VIP','#9b59b6'),role('Player','#3498db'),role('Bots','#5865f2')],categories:[cat('📌・المعلومات',[text('القوانين',[],['SendMessages']),text('الإعلانات',[],['SendMessages']),text('معلومات-السيرفر')]),cat('⛏️・Minecraft',[text('العام'),text('البناء'),text('المودات'),text('المشاكل-التقنية'),text('البحث-عن-لاعبين'),voice('Survival'),voice('Creative'),voice('مجموعة لعب')]),cat('🔒・الإدارة',[text('شات الإدارة',[],['ViewChannel'])],{Owner:['ViewChannel'],Admin:['ViewChannel']})]},
 {id:'store',name:'متجر إلكتروني وخدمات رقمية',category:'المتاجر والأعمال',plan:'premium_plus',icon:'🛒',description:'قنوات المنتجات والطلبات والتقييمات والدعم مع أقسام خاصة للموظفين.',features:['عملاء وموظفون','طلبات وتقييمات','قنوات داخلية'],roles:[role('Owner','#e74c3c',['Administrator']),role('Manager','#8e44ad',['ManageChannels','ManageMessages','ViewAuditLog']),role('Admin','#e67e22',['ManageChannels','ManageMessages']),role('Support','#3498db',['ManageMessages']),role('Customer','#95a5a6'),role('VIP','#f1c40f'),role('Bots','#5865f2')],categories:[cat('📌・المعلومات',[text('القوانين',[],['SendMessages']),text('الإعلانات',[],['SendMessages']),text('الأسعار'),text('المنتجات')]),cat('🛍️・الطلبات',[text('الطلبات'),text('التقييمات'),text('الدعم-الفني'),text('الشكاوى')]),cat('🎧・الدعم',[text('طلب-مساعدة'),voice('انتظار الدعم'),voice('دعم فني')]),cat('🔒・الموظفون',[text('شات الإدارة',[],['ViewChannel']),text('سجلات الطلبات',[],['ViewChannel']),voice('اجتماعات الموظفين',[],['ViewChannel']),voice('الإدارة',[],['ViewChannel'])],{Owner:['ViewChannel'],Manager:['ViewChannel'],Admin:['ViewChannel'],Support:['ViewChannel']})]},
 {id:'support',name:'سيرفر دعم فني',category:'المتاجر والأعمال',plan:'premium',icon:'🎫',description:'بوابة دعم وشكاوى ومتابعة الحالات مع فريق دعم خاص.',features:['طلبات مساعدة','شكاوى','إدارة خاصة'],roles:[role('Owner','#e74c3c',['Administrator']),role('Manager','#8e44ad',['ManageChannels','ManageMessages']),role('Support','#3498db',['ManageMessages']),role('Customer','#95a5a6'),role('Bots','#5865f2')],categories:[cat('📌・ابدأ هنا',[text('القوانين',[],['SendMessages']),text('الإعلانات',[],['SendMessages']),text('كيفية-الحصول-على-الدعم')]),cat('🎫・مركز الدعم',[text('فتح-طلب'),text('الأسئلة-الشائعة'),text('الشكاوى'),text('حالة-الطلبات'),voice('انتظار الدعم'),voice('دعم فني')]),cat('🔒・الفريق',[text('شات الفريق',[],['ViewChannel']),text('سجل الحالات',[],['ViewChannel'])],{Owner:['ViewChannel'],Manager:['ViewChannel'],Support:['ViewChannel']})]},
 {id:'events',name:'فعاليات وبطولات',category:'الفعاليات',plan:'premium',icon:'🏆',description:'تسجيل المشاركين وتنظيم البطولات وإعلان النتائج.',features:['تسجيل','تنظيم وحكام','نتائج'],roles:[role('Owner','#e74c3c',['Administrator']),role('Organizer','#8e44ad',['ManageChannels','ManageMessages','ManageEvents']),role('Judge','#e67e22',['ManageMessages']),role('Participant','#3498db'),role('VIP','#f1c40f'),role('Bots','#5865f2')],categories:[cat('📌・المعلومات',[text('القوانين',[],['SendMessages']),text('الإعلانات',[],['SendMessages']),text('جدول-الفعاليات')]),cat('📝・التسجيل',[text('التسجيل'),text('الفرق'),text('الأسئلة')]),cat('🏆・البطولات',[text('البطولات'),text('النتائج'),text('الفائزون'),voice('انتظار المشاركين'),voice('ساحة البطولة')]),cat('🔒・المنظمون',[text('شات المنظمين',[],['ViewChannel']),text('تقارير الحكام',[],['ViewChannel']),voice('اجتماع الحكام',[],['ViewChannel'])],{Owner:['ViewChannel'],Organizer:['ViewChannel'],Judge:['ViewChannel']})]},
 {id:'education',name:'تعليم ودورات',category:'التعليم',plan:'premium',icon:'📚',description:'منصة تعليمية مصغرة للدورات والطلاب والأسئلة والدراسة الجماعية.',features:['دروس','أسئلة','قنوات طلاب خاصة'],roles:[role('Owner','#e74c3c',['Administrator']),role('Teacher','#2980b9',['ManageMessages']),role('Assistant','#16a085',['ManageMessages']),role('Student','#3498db'),role('VIP Student','#9b59b6'),role('Bots','#5865f2')],categories:[cat('📌・المعلومات',[text('القوانين',[],['SendMessages']),text('الإعلانات',[],['SendMessages']),text('جدول-الدروس')]),cat('📚・التعلم',[text('الدورات'),text('المصادر'),text('الأسئلة'),text('البرمجة-والشروحات')]),cat('👥・الدراسة',[text('نقاش الطلاب'),voice('دراسة جماعية'),voice('مراجعة'),voice('شرح مباشر')]),cat('🔒・المدرسون',[text('غرفة المدرسين',[],['ViewChannel']),text('تقارير الطلاب',[],['ViewChannel']),voice('اجتماع المدرسين',[],['ViewChannel'])],{Owner:['ViewChannel'],Teacher:['ViewChannel'],Assistant:['ViewChannel']})]},
 {id:'team',name:'فريق عمل وإدارة',category:'الإدارة',plan:'premium_plus',icon:'🧑‍💼',description:'تنظيم فريق العمل والاجتماعات والمهام والتقارير مع مساحة خاصة للإدارة.',features:['قنوات مشاريع','مهام وتقارير','اجتماعات خاصة'],roles:[role('Owner','#e74c3c',['Administrator']),role('Director','#8e44ad',['ManageChannels','ManageMessages','ViewAuditLog']),role('Manager','#e67e22',['ManageChannels','ManageMessages']),role('Employee','#3498db'),role('Contractor','#95a5a6'),role('Bots','#5865f2')],categories:[cat('📌・الشركة',[text('القوانين',[],['SendMessages']),text('الإعلانات',[],['SendMessages']),text('دليل-الفريق')]),cat('💼・العمل',[text('العام'),text('المهام'),text('المشاريع'),text('التقارير'),text('الموارد')]),cat('🎙️・الاجتماعات',[text('جدول-الاجتماعات'),voice('اجتماع عام'),voice('اجتماع مشروع')]),cat('🔒・الإدارة',[text('إدارة الفريق',[],['ViewChannel']),text('تقارير الإدارة',[],['ViewChannel']),voice('اجتماع الإدارة',[],['ViewChannel'])],{Owner:['ViewChannel'],Director:['ViewChannel'],Manager:['ViewChannel']})]},
 {id:'arabic-community',name:'مجتمع عربي عام',category:'المجتمعات',plan:'free',icon:'🌐',description:'مجتمع عربي متوازن للقوانين والنقاشات والصور والاقتراحات.',features:['قنوات مجتمع','مساعدة','إدارة خاصة'],roles:[role('Owner','#e74c3c',['Administrator']),role('Admin','#e67e22',['ManageChannels','ManageMessages']),role('Moderator','#3498db',['ManageMessages']),role('VIP','#9b59b6'),role('Member','#95a5a6'),role('Bots','#5865f2')],categories:[cat('📌・المعلومات',[text('القوانين',[],['SendMessages']),text('الإعلانات',[],['SendMessages']),text('الأخبار')]),cat('🌍・المجتمع',[text('العام'),text('النقاشات'),text('الصور-والمقاطع'),text('الاقتراحات'),text('المساعدة'),voice('فويس عام'),voice('فويس نقاش')]),cat('🔒・الإدارة',[text('شات الإدارة',[],['ViewChannel']),text('سجلات الإدارة',[],['ViewChannel'])],{Owner:['ViewChannel'],Admin:['ViewChannel'],Moderator:['ViewChannel']})]}
];

const byId = new Map(templates.map(t => [t.id, t]));
function cloneTemplate(id) { const t = byId.get(String(id)); return t ? JSON.parse(JSON.stringify(t)) : null; }
module.exports = { templates, cloneTemplate };
