'use strict';

// Templates are data-only. Permissions use Discord permission names and are
// converted to bitfields by the executor; no destructive operations are used.
const role = (name, color, permissions = []) => ({ name, color, permissions });
const text = (name, allow = [], deny = []) => ({ name, type: 0, allow, deny });
const voice = (name, allow = [], deny = []) => ({ name, type: 2, allow, deny });
const cat = (name, channels, roleAccess = {}) => ({ name, channels, roleAccess });
const staff = ['Owner','Co Owner','Management','Admin','Moderator'];
const adminView = ['Owner','Co Owner','Management','Admin'];
const memberRead = ['Member','Friends','Customer','Gamer','Student','Participant','Employee','VIP'];
const commonRoles = [role('Owner','#e74c3c',['Administrator']),role('Admin','#e67e22',['ManageChannels','ManageMessages','KickMembers','BanMembers','ViewAuditLog']),role('Moderator','#3498db',['ManageMessages','KickMembers']),role('VIP','#9b59b6'),role('Member','#95a5a6'),role('Bots','#5865f2')];

const templates = [
 {id:'friends',name:'سيرفر أصدقاء',category:'بسيطة',plan:'free',icon:'🎮',description:'سيرفر خفيف للأصدقاء بدون زحمة قنوات.',features:['قوانين وإعلانات','شات الأصدقاء','فويس واحد للألعاب'],roles:[role('Owner','#e74c3c',['Administrator']),role('Admin','#e67e22',['ManageChannels','ManageMessages']),role('Friends','#3498db'),role('VIP','#9b59b6'),role('Bots','#5865f2')],categories:[cat('📌・ابدأ هنا',[text('القوانين',[],['SendMessages']),text('الإعلانات',[],['SendMessages'])]),cat('💬・الأصدقاء',[text('الشات العام'),text('الاقتراحات')]),cat('🎮・اللعب',[voice('فويس الأصدقاء'),voice('فويس ألعاب')]),cat('🔒・الإدارة',[text('شات الإدارة',[],['ViewChannel']),text('سجلات الإدارة',[],['ViewChannel'])],{Owner:['ViewChannel'],Admin:['ViewChannel']})]},
 {id:'simple',name:'سيرفر بسيط جدًا',category:'بسيطة',plan:'free',icon:'✨',description:'أساسيات مرتبة للبدء بدون أقسام زائدة.',features:['معلومات','شات عام','إدارة خاصة'],roles:[role('Owner','#e74c3c',['Administrator']),role('Admin','#e67e22',['ManageChannels','ManageMessages']),role('Member','#3498db'),role('Bots','#5865f2')],categories:[cat('📌・المعلومات',[text('القوانين',[],['SendMessages']),text('الإعلانات',[],['SendMessages'])]),cat('💬・التواصل',[text('العام'),text('الصور')]),cat('🔊・الصوتيات',[voice('فويس عام')]),cat('🔒・الإدارة',[text('شات الإدارة',[],['ViewChannel'])],{Owner:['ViewChannel'],Admin:['ViewChannel']})]},
 {id:'community-small',name:'مجتمع صغير',category:'بسيطة',plan:'free',icon:'🏡',description:'مجتمع صغير للنقاش والمساعدة والاقتراحات.',features:['نقاشات','مساعدة','فويس عام'],roles:[role('Owner','#e74c3c',['Administrator']),role('Moderator','#3498db',['ManageMessages']),role('Member','#95a5a6'),role('Bots','#5865f2')],categories:[cat('📌・المعلومات',[text('القوانين',[],['SendMessages']),text('الإعلانات',[],['SendMessages'])]),cat('🌍・المجتمع',[text('العام'),text('الاقتراحات'),text('المساعدة')]),cat('🔊・الصوتيات',[voice('فويس المجتمع')]),cat('🔒・الفريق',[text('شات الفريق',[],['ViewChannel'])],{Owner:['ViewChannel'],Moderator:['ViewChannel']})]},
 {id:'fivem-general',name:'FiveM عام وRoleplay',category:'FiveM وRoleplay',plan:'premium_plus',icon:'🚔',description:'سيرفر RP بأقسام واضحة للمعلومات والمدينة والوظائف.',features:['وظائف RP','قنوات خاصة','دعم وتقارير'],roles:[role('Owner','#e74c3c',['Administrator']),role('Co Owner','#c0392b',['ManageGuild','ManageChannels','ManageRoles']),role('Management','#8e44ad',['ManageChannels','ManageMessages','ViewAuditLog']),role('Admin','#e67e22',['ManageChannels','ManageMessages','KickMembers']),role('Moderator','#3498db',['ManageMessages','KickMembers']),role('Police','#2980b9'),role('EMS','#2ecc71'),role('Gang','#8e44ad'),role('VIP','#f1c40f'),role('Member','#95a5a6'),role('Bots','#5865f2')],categories:[cat('📌・معلومات المدينة',[text('القوانين',[],['SendMessages']),text('الإعلانات',[],['SendMessages']),text('تحديثات المدينة')]),cat('🌆・حياة المدينة',[text('الشات العام'),text('معلومات الدخول'),text('المشاكل التقنية')]),cat('🧾・التقديمات والدعم',[text('تقديم الوظائف'),text('الشكاوى'),text('طلب مساعدة')]),cat('🚔・الشرطة',[text('إعلانات الشرطة',[],['ViewChannel']),text('تقارير الشرطة',[],['ViewChannel']),voice('فويس الشرطة',[],['ViewChannel'])],{Owner:['ViewChannel'],'Co Owner':['ViewChannel'],Management:['ViewChannel'],Admin:['ViewChannel'],Police:['ViewChannel']}),cat('🚑・الإسعاف',[text('تقارير الإسعاف',[],['ViewChannel']),voice('فويس الإسعاف',[],['ViewChannel'])],{Owner:['ViewChannel'],'Co Owner':['ViewChannel'],Management:['ViewChannel'],Admin:['ViewChannel'],EMS:['ViewChannel']}),cat('🔫・العصابات',[text('تنسيق العصابات',[],['ViewChannel']),voice('فويس العصابات',[],['ViewChannel'])],{Owner:['ViewChannel'],'Co Owner':['ViewChannel'],Management:['ViewChannel'],Admin:['ViewChannel'],Gang:['ViewChannel']}),cat('🔒・الإدارة',[text('شات الإدارة',[],['ViewChannel']),text('سجلات الإدارة',[],['ViewChannel']),voice('اجتماع الإدارة',[],['ViewChannel'])],{Owner:['ViewChannel'],'Co Owner':['ViewChannel'],Management:['ViewChannel'],Admin:['ViewChannel'],Moderator:['ViewChannel']})]},
 {id:'fivem-friends',name:'FiveM للأصدقاء',category:'FiveM وRoleplay',plan:'premium',icon:'🚗',description:'مجموعة صغيرة للعب FiveM مع الأصدقاء.',features:['معلومات دخول','شات اللعبة','فويسات قليلة'],roles:[role('Owner','#e74c3c',['Administrator']),role('Admin','#e67e22',['ManageChannels','ManageMessages']),role('Driver','#3498db'),role('Friends','#2ecc71'),role('Bots','#5865f2')],categories:[cat('📌・المعلومات',[text('القوانين',[],['SendMessages']),text('معلومات الدخول')]),cat('🚗・FiveM',[text('شات FiveM'),text('الاقتراحات'),text('مشاكل اللعبة')]),cat('🔊・الصوتيات',[voice('فويس عام'),voice('فويس القيادة')]),cat('🔒・الإدارة',[text('شات الإدارة',[],['ViewChannel'])],{Owner:['ViewChannel'],Admin:['ViewChannel']})]},
 {id:'gaming',name:'مجتمع ألعاب متكامل',category:'الألعاب',plan:'premium',icon:'🕹️',description:'مجتمع ألعاب بأقسام للألعاب والبحث عن لاعبين والفعاليات.',features:['أقسام ألعاب','بحث عن لاعبين','فعاليات'],roles:[role('Owner','#e74c3c',['Administrator']),role('Admin','#e67e22',['ManageChannels','ManageMessages','KickMembers']),role('Moderator','#3498db',['ManageMessages']),role('Event Manager','#16a085',['ManageEvents','ManageMessages']),role('VIP','#9b59b6'),role('Gamer','#2ecc71'),role('Member','#95a5a6'),role('Bots','#5865f2')],categories:[cat('📌・المعلومات',[text('القوانين',[],['SendMessages']),text('الإعلانات',[],['SendMessages'])]),cat('💬・مجتمع اللاعبين',[text('الشات العام'),text('البحث عن لاعبين'),text('المقاطع واللقطات')]),cat('🎮・الألعاب',[text('Minecraft'),text('Roblox'),text('Valorant'),text('Fortnite')]),cat('🔊・غرف اللعب',[voice('فويس ألعاب 1'),voice('فويس ألعاب 2')]),cat('🏆・الفعاليات',[text('الفعاليات والبطولات'),text('النتائج')]),cat('🔒・الإدارة',[text('شات الإدارة',[],['ViewChannel']),voice('فويس الإدارة',[],['ViewChannel'])],{Owner:['ViewChannel'],Admin:['ViewChannel'],Moderator:['ViewChannel']})]},
 {id:'minecraft',name:'Minecraft',category:'الألعاب',plan:'premium',icon:'⛏️',description:'كل ما يخص Minecraft من معلومات وبناء ومجموعات لعب.',features:['معلومات السيرفر','البناء والمودات','غرف لعب'],roles:[role('Owner','#e74c3c',['Administrator']),role('Admin','#e67e22',['ManageChannels','ManageMessages']),role('Builder','#2ecc71'),role('VIP','#9b59b6'),role('Player','#3498db'),role('Bots','#5865f2')],categories:[cat('📌・معلومات السيرفر',[text('القوانين',[],['SendMessages']),text('الإعلانات',[],['SendMessages']),text('معلومات السيرفر')]),cat('⛏️・عالم Minecraft',[text('الشات العام'),text('البناء والأفكار'),text('المودات'),text('المشاكل التقنية')]),cat('👥・العب مع الآخرين',[text('البحث عن لاعبين'),voice('Survival'),voice('Creative')]),cat('🔒・الإدارة',[text('شات الإدارة',[],['ViewChannel'])],{Owner:['ViewChannel'],Admin:['ViewChannel']})]},
 {id:'store',name:'متجر إلكتروني وخدمات رقمية',category:'المتاجر والأعمال',plan:'premium_plus',icon:'🛒',description:'متجر منظم للمنتجات والطلبات وخدمة العملاء.',features:['عرض المنتجات','طلبات العملاء','فريق خاص'],roles:[role('Owner','#e74c3c',['Administrator']),role('Manager','#8e44ad',['ManageChannels','ManageMessages','ViewAuditLog']),role('Admin','#e67e22',['ManageChannels','ManageMessages']),role('Support','#3498db',['ManageMessages']),role('Customer','#95a5a6'),role('VIP','#f1c40f'),role('Bots','#5865f2')],categories:[cat('📌・واجهة المتجر',[text('القوانين',[],['SendMessages']),text('الإعلانات',[],['SendMessages']),text('المنتجات والأسعار')]),cat('🛍️・الطلبات والعملاء',[text('طريقة الطلب'),text('تقييمات العملاء'),text('الشكاوى')]),cat('🎧・خدمة العملاء',[text('طلب مساعدة'),voice('انتظار الدعم')]),cat('🔒・فريق المتجر',[text('شات الموظفين',[],['ViewChannel']),text('سجل الطلبات',[],['ViewChannel']),voice('اجتماع الموظفين',[],['ViewChannel'])],{Owner:['ViewChannel'],Manager:['ViewChannel'],Admin:['ViewChannel'],Support:['ViewChannel']})]},
 {id:'support',name:'سيرفر دعم فني',category:'المتاجر والأعمال',plan:'premium',icon:'🎫',description:'مركز دعم واضح لاستقبال المشاكل ومتابعة الحلول.',features:['إرشادات الدعم','طلبات مساعدة','فريق دعم'],roles:[role('Owner','#e74c3c',['Administrator']),role('Manager','#8e44ad',['ManageChannels','ManageMessages']),role('Support','#3498db',['ManageMessages']),role('Customer','#95a5a6'),role('Bots','#5865f2')],categories:[cat('📌・ابدأ هنا',[text('القوانين',[],['SendMessages']),text('كيفية الحصول على الدعم'),text('الأسئلة الشائعة')]),cat('🎫・طلبات الدعم',[text('فتح طلب'),text('الشكاوى'),text('متابعة الطلب')]),cat('🔊・الدعم الصوتي',[voice('انتظار الدعم'),voice('مكالمة دعم')]),cat('🔒・فريق الدعم',[text('شات الفريق',[],['ViewChannel']),text('سجل الحالات',[],['ViewChannel'])],{Owner:['ViewChannel'],Manager:['ViewChannel'],Support:['ViewChannel']})]},
 {id:'events',name:'فعاليات وبطولات',category:'الفعاليات',plan:'premium',icon:'🏆',description:'تنظيم التسجيل والبطولات والنتائج في أقسام مستقلة.',features:['تسجيل المشاركين','إدارة البطولات','نتائج الفعاليات'],roles:[role('Owner','#e74c3c',['Administrator']),role('Organizer','#8e44ad',['ManageChannels','ManageMessages','ManageEvents']),role('Judge','#e67e22',['ManageMessages']),role('Participant','#3498db'),role('VIP','#f1c40f'),role('Bots','#5865f2')],categories:[cat('📌・دليل الفعاليات',[text('القوانين',[],['SendMessages']),text('الإعلانات',[],['SendMessages']),text('جدول الفعاليات')]),cat('📝・المشاركة',[text('التسجيل'),text('الفرق والأسئلة')]),cat('🏆・البطولات والنتائج',[text('البطولات الحالية'),text('النتائج والفائزون')]),cat('🔊・غرف المنافسة',[voice('انتظار المشاركين'),voice('ساحة البطولة')]),cat('🔒・المنظمون',[text('شات المنظمين',[],['ViewChannel']),text('تقارير الحكام',[],['ViewChannel']),voice('اجتماع الحكام',[],['ViewChannel'])],{Owner:['ViewChannel'],Organizer:['ViewChannel'],Judge:['ViewChannel']})]},
 {id:'education',name:'تعليم ودورات',category:'التعليم',plan:'premium',icon:'📚',description:'تنظيم الدروس والمصادر والأسئلة والدراسة الجماعية.',features:['محتوى تعليمي','أسئلة الطلاب','غرف دراسة'],roles:[role('Owner','#e74c3c',['Administrator']),role('Teacher','#2980b9',['ManageMessages']),role('Assistant','#16a085',['ManageMessages']),role('Student','#3498db'),role('VIP Student','#9b59b6'),role('Bots','#5865f2')],categories:[cat('📌・معلومات الدورة',[text('القوانين',[],['SendMessages']),text('الإعلانات',[],['SendMessages']),text('جدول الدروس')]),cat('📚・المحتوى التعليمي',[text('الدروس والمصادر'),text('البرمجة والشروحات')]),cat('🙋・أسئلة ونقاش',[text('أسئلة الطلاب'),text('نقاش الطلاب')]),cat('🔊・غرف الدراسة',[voice('دراسة جماعية'),voice('شرح مباشر')]),cat('🔒・المدرسون',[text('غرفة المدرسين',[],['ViewChannel']),text('متابعة الطلاب',[],['ViewChannel']),voice('اجتماع المدرسين',[],['ViewChannel'])],{Owner:['ViewChannel'],Teacher:['ViewChannel'],Assistant:['ViewChannel']})]},
 {id:'team',name:'فريق عمل وإدارة',category:'الإدارة',plan:'premium_plus',icon:'🧑‍💼',description:'مساحة عمل منظمة للمهام والمشاريع والاجتماعات.',features:['مهام ومشاريع','اجتماعات','تقارير داخلية'],roles:[role('Owner','#e74c3c',['Administrator']),role('Director','#8e44ad',['ManageChannels','ManageMessages','ViewAuditLog']),role('Manager','#e67e22',['ManageChannels','ManageMessages']),role('Employee','#3498db'),role('Contractor','#95a5a6'),role('Bots','#5865f2')],categories:[cat('📌・دليل الفريق',[text('القوانين',[],['SendMessages']),text('الإعلانات',[],['SendMessages']),text('دليل الفريق')]),cat('💼・العمل اليومي',[text('المهام'),text('المشاريع'),text('الموارد')]),cat('📊・التقارير والاجتماعات',[text('التقارير'),text('جدول الاجتماعات'),voice('اجتماع عام')]),cat('🔒・الإدارة',[text('إدارة الفريق',[],['ViewChannel']),text('تقارير الإدارة',[],['ViewChannel']),voice('اجتماع الإدارة',[],['ViewChannel'])],{Owner:['ViewChannel'],Director:['ViewChannel'],Manager:['ViewChannel']})]},
 {id:'arabic-community',name:'مجتمع عربي عام',category:'المجتمعات',plan:'free',icon:'🌐',description:'مجتمع عربي متوازن للنقاش والمحتوى والمساعدة.',features:['نقاشات عربية','محتوى ومقاطع','مساعدة واقتراحات'],roles:[role('Owner','#e74c3c',['Administrator']),role('Admin','#e67e22',['ManageChannels','ManageMessages']),role('Moderator','#3498db',['ManageMessages']),role('VIP','#9b59b6'),role('Member','#95a5a6'),role('Bots','#5865f2')],categories:[cat('📌・إعلانات ومعلومات',[text('القوانين',[],['SendMessages']),text('الإعلانات',[],['SendMessages']),text('الأخبار')]),cat('🌍・النقاش العربي',[text('الشات العام'),text('النقاشات'),text('الاقتراحات')]),cat('🖼️・المحتوى',[text('الصور والمقاطع'),text('المساعدة')]),cat('🔊・المجتمع الصوتي',[voice('فويس عام'),voice('فويس نقاش')]),cat('🔒・الإدارة',[text('شات الإدارة',[],['ViewChannel']),text('سجلات الإدارة',[],['ViewChannel'])],{Owner:['ViewChannel'],Admin:['ViewChannel'],Moderator:['ViewChannel']})]}
];
const byId = new Map(templates.map(t => [t.id, t]));
function cloneTemplate(id) { const t = byId.get(String(id)); return t ? JSON.parse(JSON.stringify(t)) : null; }
module.exports = { templates, cloneTemplate };
