'use strict';

// Templates are data-only. Permissions use Discord permission names and are
// converted to bitfields by the executor; no destructive operations are used.
const role = (name, color, permissions = []) => ({ name, color, permissions });
const text = (name, allow = [], deny = []) => ({ name, type: 0, allow, deny });
const voice = (name, allow = [], deny = []) => ({ name, type: 2, allow, deny });
const cat = (name, channels, roleAccess = {}) => ({ name, channels, roleAccess });
const staff = ['Owner','Co Owner','Management','Admin','Moderator'];
const adminView = ['Owner','Co Owner','Management','Admin'];
const memberRead = ['Member','Friends','Customer','Gamer','Student','Participant','Employee','VIP'];
const commonRoles = [role('Owner','#e74c3c',['Administrator']),role('Admin','#e67e22',['ManageChannels','ManageMessages','KickMembers','BanMembers','ViewAuditLog']),role('Moderator','#3498db',['ManageMessages','KickMembers']),role('VIP','#9b59b6'),role('Member','#95a5a6'),role('Bots','#5865f2')];

const templates = [
 {id:'friends',name:'سيرفر أصدقاء',category:'بسيطة',plan:'free',icon:'🎮',description:'سيرفر خفيف للأصدقاء مع قنوات عامة وألعاب وفويسات.',features:['رتب بسيطة','فويسات للألعاب','قنوات اقتراحات'],roles:[role('Owner','#e74c3c',['Administrator']),role('Admin','#e67e22',['ManageChannels','ManageMessages']),role('Friends','#3498db'),role('VIP','#9b59b6'),role('Bots','#5865f2')],categories:[cat('📌・المعلومات',[text('القوانين',[],['SendMessages']),text('الإعلانات',[],['SendMessages'])]),cat('💬・المجتمع',[text('العام',['ViewChannel','SendMessages']),text('الصور-والمقاطع',['ViewChannel','SendMessages']),text('الميمز',['ViewChannel','SendMessages']),text('الاقتراحات',['ViewChannel','SendMessages'])]),cat('🎮・الألعاب',[text('الألعاب',['ViewChannel','SendMessages']),voice('فويس عام'),voice('فويس ألعاب 1'),voice('فويس ألعاب 2'),voice('فويس خاص'),voice('فويس AFK')]),cat('🔒・الإدارة',[text('شات الإدارة',[],['ViewChannel']),text('سجلات الإدارة',[],['ViewChannel'])],{Owner:['ViewChannel'],Admin:['ViewChannel']})]},
 {id:'simple',name:'سيرفر بسيط جدًا',category:'بسيطة',plan:'free',icon:'✨',description:'هيكل أساسي جدًا مناسب للبدء السريع.',features:['قنوات أساسية','رتب قليلة','إدارة خاصة'],roles:[role('Owner','#e74c3c',['Administrator']),role('Admin','#e67e22',['ManageChannels','ManageMessages']),role('Member','#3498db'),role('Bots','#5865f2')],categories:[cat('📌・البداية',[text('القوانين',[],['SendMessages']),text('الإعلانات',[],['SendMessages'])]),cat('💬・الشات',[text('العام'),text('الصور'),voice('فويس عام'),voice('فويس 2')]),cat('🔒・الإدارة',[text('شات الإدارة',[],['ViewChannel'])],{Owner:['ViewChannel'],Admin:['ViewChannel']})]},
 {id:'community-small',name:'مجتمع صغير',category:'بسيطة',plan:'free',icon:'🏡',description:'مجتمع صغير مع اقتراحات ومساعدة وفويسات.',features:['مجتمع','اقتراحات','مساعدة'],roles:[role('Owner','#e74c3c',['Administrator']),role('Moderator','#3498db',['ManageMessages']),role('Member','#95a5a6'),role('Bots','#5865f2')],categories:[cat('📌・المعلومات',[text('القوانين',[],['SendMessages']),text('الإعلانات',[],['SendMessages'])]),cat('🌍・المجتمع',[text('العام'),text('الصور-والمقاطع'),text('الاقتراحات'),text('المساعدة'),voice('فويس عام'),voice('فويس 2')]),cat('🔒・الفريق',[text('شات الفريق',[],['ViewChannel'])],{Owner:['ViewChannel'],Moderator:['ViewChannel']})]},
 {id:'fivem-general',name:'FiveM عام وRoleplay',category:'FiveM وRoleplay',plan:'premium_plus',icon:'🚔',description:'هيكل RP متكامل مع أقسام الشرطة والإسعاف والعصابات والإدارة.',features:['رتب وظائف','قنوات خاصة حسب الرتبة','دعم وتقارير'],roles:[role('Owner','#e74c3c',['Administrator']),role('Co Owner','#c0392b',['ManageGuild','ManageChannels','ManageRoles']),role('Management','#8e44ad',['ManageChannels','ManageMessages','ViewAuditLog']),role('Admin','#e67e22',['ManageChannels','ManageMessages','KickMembers']),role('Moderator','#3498db',['ManageMessages','KickMembers']),role('Police','#2980b9'),role('EMS','#2ecc71'),role('Gang','#8e44ad'),role('VIP','#f1c40f'),role('Member','#95a5a6'),role('Bots','#5865f2')],categories:[cat('📌・معلومات السيرفر',[text('القوانين',[],['SendMessages']),text('الإعلانات',[],['SendMessages']),text('الأخبار'),text('التحديثات')]),cat('💬・المجتمع',[text('العام'),text('الشاتات'),text('الصور-والمقاطع'),voice('انتظار'),voice('فويس عام 1'),voice('فويس عام 2')]),cat('🎮・FiveM',[text('معلومات الدخول'),text('مشاكل اللعبة'),text('تقديمات الوظائف')]),cat('🚔・الشرطة',[text('إعلانات الشرطة',[],['ViewChannel']),text('نقاشات الشرطة',[],['ViewChannel']),text('تقارير الشرطة',[],['ViewChannel']),voice('فويس الشرطة',[],['ViewChannel'])],{Owner:['ViewChannel'],'Co Owner':['ViewChannel'],Management:['ViewChannel'],Admin:['ViewChannel'],Police:['ViewChannel']}),cat('🚑・الإسعاف',[text('إعلانات الإسعاف',[],['ViewChannel']),text('تقارير الإسعاف',[],['ViewChannel']),voice('فويس الإسعاف',[],['ViewChannel'])],{Owner:['ViewChannel'],'Co Owner':['ViewChannel'],Management:['ViewChannel'],Admin:['ViewChannel'],EMS:['ViewChannel']}),cat('🔫・العصابات',[text('إعلانات العصابات',[],['ViewChannel']),text('تنسيق العصابات',[],['ViewChannel']),voice('فويس العصابات',[],['ViewChannel'])],{Owner:['ViewChannel'],'Co Owner':['ViewChannel'],Management:['ViewChannel'],Admin:['ViewChannel'],Gang:['ViewChannel']}),cat('🎫・الدعم',[text('فتح-تذكرة'),text('الشكاوى'),text('المساعدة')]),cat('🔒・الإدارة',[text('شات الإدارة',[],['ViewChannel']),text('سجلات الإدارة',[],['ViewChannel']),voice('فويس الإدارة',[],['ViewChannel']),voice('اجتماعات خاصة',[],['ViewChannel'])],{Owner:['ViewChannel'],'Co Owner':['ViewChannel'],Management:['ViewChannel'],Admin:['ViewChannel'],Moderator:['ViewChannel']})]},
 {id:'fivem-friends',name:'FiveM للأصدقاء',category:'FiveM وRoleplay',plan:'premium',icon:'🚗',description:'قنوات FiveM خاصة بمجموعة أصدقاء صغيرة.',features:['معلومات دخول','تجارب لعب','فويسات'],roles:[role('Owner','#e74c3c',['Administrator']),role('Admin','#e67e22',['ManageChannels','ManageMessages']),role('Driver','#3498db'),role('Friends','#2ecc71'),role('Bots','#5865f2')],categories:[cat('📌・المعلومات',[text('القوانين',[],['SendMessages']),text('معلومات-الدخول')]),cat('🚗・FiveM',[text('العام'),text('الاقتراحات'),text('مشاكل-اللعبة'),voice('فويس عام'),voice('فويس قيادة')]),cat('🔒・الإدارة',[text('شات الإدارة',[],['ViewChannel'])],{Owner:['ViewChannel'],Admin:['ViewChannel']})]},
 {id:'gaming',name:'مجتمع ألعاب متكامل',category:'الألعاب',plan:'premium',icon:'🕹️',description:'مجتمع ألعاب عام مع البحث عن لاعبين وأقسام الألعاب والفعاليات.',features:['Minecraft وRoblox وValorant وFortnite','فعاليات','فويسات جماعية'],roles:[role('Owner','#e74c3c',['Administrator']),role('Admin','#e67e22',['ManageChannels','ManageMessages','KickMembers']),role('Moderator','#3498db',['ManageMessages']),role('Event Manager','#16a085',['ManageEvents','ManageMessages']),role('VIP','#9b59b6'),role('Gamer','#2ecc71'),role('Member','#95a5a6'),role('Bots','#5865f2')],categories:[cat('📌・المعلومات',[text('القوانين',[],['SendMessages']),text('الإعلانات',[],['SendMessages'])]),cat('💬・المجتمع',[text('العام'),text('البحث-عن-لاعبين'),text('المقاطع'),text('الاقتراحات')]),cat('🎮・الألعاب',[text('Minecraft'),text('Roblox'),text('Valorant'),text('Fortnite'),voice('ألعاب 1'),voice('ألعاب 2'),voice('ألعاب 3')]),cat('🏆・الفعاليات',[text('الفعاليات'),text('النتائج'),voice('فويس فعاليات')]),cat('🔒・الإدارة',[text('شات الإدارة',[],['ViewChannel']),voice('فويس الإدارة',[],['ViewChannel'])],{Owner:['ViewChannel'],Admin:['ViewChannel'],Moderator:['ViewChannel']})]},
 {id:'minecraft',name:'Minecraft',category:'الألعاب',plan:'premium',icon:'⛏️',description:'سيرفر مجتمع Minecraft للتحديثات والسيرفرات والبناء والبحث عن لاعبين.',features:['أقسام لعب','دعم تقني','فويسات'],roles:[role('Owner','#e74c3c',['Administrator']),role('Admin','#e67e22',['ManageChannels','ManageMessages']),role('Builder','#2ecc71'),role('VIP','#9b59b6'),role('Player','#3498db'),role('Bots','#5865f2')],categories:[cat('📌・المعلومات',[text('القوانين',[],['SendMessages']),text('الإعلانات',[],['SendMessages']),text('معلومات-السيرفر')]),cat('⛏️・Minecraft',[text('العام'),text('البناء'),text('المودات'),text('المشاكل-التقنية'),text('البحث-عن-لاعبين'),voice('Survival'),voice('Creative'),voice('مجموعة لعب')]),cat('🔒・الإدارة',[text('شات الإدارة',[],['ViewChannel'])],{Owner:['ViewChannel'],Admin:['ViewChannel']})]},
 {id:'store',name:'متجر إلكتروني وخدمات رقمية',category:'المتاجر والأعمال',plan:'premium_plus',icon:'🛒',description:'قنوات المنتجات والطلبات والتقييمات والدعم مع أقسام خاصة للموظفين.',features:['عملاء وموظفون','طلبات وتقييمات','قنوات داخلية'],roles:[role('Owner','#e74c3c',['Administrator']),role('Manager','#8e44ad',['ManageChannels','ManageMessages','ViewAuditLog']),role('Admin','#e67e22',['ManageChannels','ManageMessages']),role('Support','#3498db',['ManageMessages']),role('Customer','#95a5a6'),role('VIP','#f1c40f'),role('Bots','#5865f2')],categories:[cat('📌・المعلومات',[text('القوانين',[],['SendMessages']),text('الإعلانات',[],['SendMessages']),text('الأسعار'),text('المنتجات')]),cat('🛍️・الطلبات',[text('الطلبات'),text('التقييمات'),text('الدعم-الفني'),text('الشكاوى')]),cat('🎧・الدعم',[text('طلب-مساعدة'),voice('انتظار الدعم'),voice('دعم فني')]),cat('🔒・الموظفون',[text('شات الإدارة',[],['ViewChannel']),text('سجلات الطلبات',[],['ViewChannel']),voice('اجتماعات الموظفين',[],['ViewChannel']),voice('الإدارة',[],['ViewChannel'])],{Owner:['ViewChannel'],Manager:['ViewChannel'],Admin:['ViewChannel'],Support:['ViewChannel']})]},
 {id:'support',name:'سيرفر دعم فني',category:'المتاجر والأعمال',plan:'premium',icon:'🎫',description:'بوابة دعم وشكاوى ومتابعة الحالات مع فريق دعم خاص.',features:['طلبات مساعدة','شكاوى','إدارة خاصة'],roles:[role('Owner','#e74c3c',['Administrator']),role('Manager','#8e44ad',['ManageChannels','ManageMessages']),role('Support','#3498db',['ManageMessages']),role('Customer','#95a5a6'),role('Bots','#5865f2')],categories:[cat('📌・ابدأ هنا',[text('القوانين',[],['SendMessages']),text('الإعلانات',[],['SendMessages']),text('كيفية-الحصول-على-الدعم')]),cat('🎫・مركز الدعم',[text('فتح-طلب'),text('الأسئلة-الشائعة'),text('الشكاوى'),text('حالة-الطلبات'),voice('انتظار الدعم'),voice('دعم فني')]),cat('🔒・الفريق',[text('شات الفريق',[],['ViewChannel']),text('سجل الحالات',[],['ViewChannel'])],{Owner:['ViewChannel'],Manager:['ViewChannel'],Support:['ViewChannel']})]},
 {id:'events',name:'فعاليات وبطولات',category:'الفعاليات',plan:'premium',icon:'🏆',description:'تسجيل المشاركين وتنظيم البطولات وإعلان النتائج.',features:['تسجيل','تنظيم وحكام','نتائج'],roles:[role('Owner','#e74c3c',['Administrator']),role('Organizer','#8e44ad',['ManageChannels','ManageMessages','ManageEvents']),role('Judge','#e67e22',['ManageMessages']),role('Participant','#3498db'),role('VIP','#f1c40f'),role('Bots','#5865f2')],categories:[cat('📌・المعلومات',[text('القوانين',[],['SendMessages']),text('الإعلانات',[],['SendMessages']),text('جدول-الفعاليات')]),cat('📝・التسجيل',[text('التسجيل'),text('الفرق'),text('الأسئلة')]),cat('🏆・البطولات',[text('البطولات'),text('النتائج'),text('الفائزون'),voice('انتظار المشاركين'),voice('ساحة البطولة')]),cat('🔒・المنظمون',[text('شات المنظمين',[],['ViewChannel']),text('تقارير الحكام',[],['ViewChannel']),voice('اجتماع الحكام',[],['ViewChannel'])],{Owner:['ViewChannel'],Organizer:['ViewChannel'],Judge:['ViewChannel']})]},
 {id:'education',name:'تعليم ودورات',category:'التعليم',plan:'premium',icon:'📚',description:'منصة تعليمية مصغرة للدورات والطلاب والأسئلة والدراسة الجماعية.',features:['دروس','أسئلة','قنوات طلاب خاصة'],roles:[role('Owner','#e74c3c',['Administrator']),role('Teacher','#2980b9',['ManageMessages']),role('Assistant','#16a085',['ManageMessages']),role('Student','#3498db'),role('VIP Student','#9b59b6'),role('Bots','#5865f2')],categories:[cat('📌・المعلومات',[text('القوانين',[],['SendMessages']),text('الإعلانات',[],['SendMessages']),text('جدول-الدروس')]),cat('📚・التعلم',[text('الدورات'),text('المصادر'),text('الأسئلة'),text('البرمجة-والشروحات')]),cat('👥・الدراسة',[text('نقاش الطلاب'),voice('دراسة جماعية'),voice('مراجعة'),voice('شرح مباشر')]),cat('🔒・المدرسون',[text('غرفة المدرسين',[],['ViewChannel']),text('تقارير الطلاب',[],['ViewChannel']),voice('اجتماع المدرسين',[],['ViewChannel'])],{Owner:['ViewChannel'],Teacher:['ViewChannel'],Assistant:['ViewChannel']})]},
 {id:'team',name:'فريق عمل وإدارة',category:'الإدارة',plan:'premium_plus',icon:'🧑‍💼',description:'تنظيم فريق العمل والاجتماعات والمهام والتقارير مع مساحة خاصة للإدارة.',features:['قنوات مشاريع','مهام وتقارير','اجتماعات خاصة'],roles:[role('Owner','#e74c3c',['Administrator']),role('Director','#8e44ad',['ManageChannels','ManageMessages','ViewAuditLog']),role('Manager','#e67e22',['ManageChannels','ManageMessages']),role('Employee','#3498db'),role('Contractor','#95a5a6'),role('Bots','#5865f2')],categories:[cat('📌・الشركة',[text('القوانين',[],['SendMessages']),text('الإعلانات',[],['SendMessages']),text('دليل-الفريق')]),cat('💼・العمل',[text('العام'),text('المهام'),text('المشاريع'),text('التقارير'),text('الموارد')]),cat('🎙️・الاجتماعات',[text('جدول-الاجتماعات'),voice('اجتماع عام'),voice('اجتماع مشروع')]),cat('🔒・الإدارة',[text('إدارة الفريق',[],['ViewChannel']),text('تقارير الإدارة',[],['ViewChannel']),voice('اجتماع الإدارة',[],['ViewChannel'])],{Owner:['ViewChannel'],Director:['ViewChannel'],Manager:['ViewChannel']})]},
 {id:'arabic-community',name:'مجتمع عربي عام',category:'المجتمعات',plan:'free',icon:'🌐',description:'مجتمع عربي متوازن للقوانين والنقاشات والصور والاقتراحات.',features:['قنوات مجتمع','مساعدة','إدارة خاصة'],roles:[role('Owner','#e74c3c',['Administrator']),role('Admin','#e67e22',['ManageChannels','ManageMessages']),role('Moderator','#3498db',['ManageMessages']),role('VIP','#9b59b6'),role('Member','#95a5a6'),role('Bots','#5865f2')],categories:[cat('📌・المعلومات',[text('القوانين',[],['SendMessages']),text('الإعلانات',[],['SendMessages']),text('الأخبار')]),cat('🌍・المجتمع',[text('العام'),text('النقاشات'),text('الصور-والمقاطع'),text('الاقتراحات'),text('المساعدة'),voice('فويس عام'),voice('فويس نقاش')]),cat('🔒・الإدارة',[text('شات الإدارة',[],['ViewChannel']),text('سجلات الإدارة',[],['ViewChannel'])],{Owner:['ViewChannel'],Admin:['ViewChannel'],Moderator:['ViewChannel']})]}
];


// Expanded specialist templates (kept data-only so they remain editable).
const specialistTemplates = [
 {id:'police-security',name:'الشرطة والأمن',category:'Roleplay',plan:'premium_plus',icon:'🚓',description:'قيادة وعمليات ودوريات وتدريب وقضايا سرية.',roles:[['Police Commissioner','#8e44ad',['ManageChannels']],['Deputy Commissioner','#9b59b6',[]],['Chief of Police','#c0392b',[]],['Captain','#d35400',[]],['Lieutenant','#e67e22',[]],['Sergeant','#2980b9',[]],['Senior Officer','#3498db',[]],['Officer','#2ecc71',[]],['Recruit','#95a5a6',[]],['Internal Affairs','#34495e',[]],['Detective','#16a085',[]],['Training Officer','#1abc9c',[]],['Dispatcher','#f1c40f',[]],['Civilian','#7f8c8d',[]],['Suspended','#555555',[]],['Muted','#555555',[]],['Bots','#5865f2',[]]], cats:[['معلومات القسم','welcome rules announcements department-news duty-requirements rank-structure'],['العمليات','operations patrol-planning active-incidents incident-reports wanted-list evidence-room case-files dispatch-updates'],['التدريب','academy-information training-schedule training-materials exam-results promotion-requests'],['شؤون الأفراد','leave-requests shift-reports performance-reviews internal-affairs'],['التقديمات والدعم','applications appeals support-tickets'],['القيادة السرية','command-staff officer-evaluations disciplinary-records confidential-cases staff-logs'],['الفويسات','Dispatch Patrol-1 Patrol-2 Training-Room Command-Meeting Interview-Room AFK']]},
 {id:'hospital-ems',name:'الإسعاف والمستشفى',category:'Roleplay',plan:'premium_plus',icon:'🚑',description:'طاقم طبي ومناوبات وتدريب وتقارير محمية.',roles:[['Medical Director','#8e44ad',[]],['Deputy Director','#9b59b6',[]],['Chief Physician','#c0392b',[]],['Physician','#e74c3c',[]],['Surgeon','#d35400',[]],['Emergency Doctor','#e67e22',[]],['Paramedic','#2980b9',[]],['Nurse','#16a085',[]],['Trainee','#95a5a6',[]],['Dispatcher','#f1c40f',[]],['Medical Trainer','#1abc9c',[]],['Member','#7f8c8d',[]],['Muted','#555555',[]],['Bots','#5865f2',[]]], cats:[['معلومات المستشفى','welcome rules announcements medical-guidelines duty-schedule hospital-news'],['الطاقم الطبي','medical-chat emergency-cases patient-reports ambulance-dispatch medical-equipment shift-handover'],['التدريب','training medical-courses exams certifications training-results'],['التقديمات','medical-applications interviews promotion-requests leave-requests'],['الإدارة السرية','management-chat confidential-reports staff-evaluations disciplinary-actions medical-logs'],['الدعم','help-desk complaints appeals'],['الفويسات','Emergency-Dispatch Medical-Team-1 Medical-Team-2 Training-Room Interviews Management-Meeting']]},
 {id:'gangs-wars',name:'العصابات والحروب',category:'Roleplay',plan:'premium',icon:'⚔️',description:'تجنيد وخطط وحروب وتحالفات مع قنوات قيادة خاصة.',roles:[['Gang Director','#8e44ad',[]],['Gang Leader','#c0392b',[]],['Deputy Leader','#e74c3c',[]],['War Commander','#d35400',[]],['Recruiter','#e67e22',[]],['Senior Member','#2980b9',[]],['Member','#3498db',[]],['Recruit','#95a5a6',[]],['Diplomat','#16a085',[]],['Ally','#2ecc71',[]],['Guest','#7f8c8d',[]],['Muted','#555555',[]],['Bots','#5865f2',[]]], cats:[['البداية','welcome rules announcements gang-information recruitment'],['العصابة','gang-chat gang-media gang-plans member-roster training achievements'],['الحروب','war-announcements war-planning battle-reports alliances diplomacy event-results'],['القيادة السرية','leadership-chat recruitment-review disciplinary-reports internal-logs'],['الفويسات','General Squad-1 Squad-2 War-Room Leadership Diplomacy']]},
 {id:'roblox',name:'Roblox',category:'الألعاب',plan:'premium',icon:'🧱',description:'مجتمع Roblox والتطوير والتداول والفعاليات.',roles:[['Community Manager','#8e44ad',[]],['Game Developer','#2980b9',[]],['Builder','#16a085',[]],['Tester','#1abc9c',[]],['Event Host','#d35400',[]],['Content Creator','#e67e22',[]],['VIP','#f1c40f',[]],['Verified Player','#3498db',[]],['Member','#95a5a6',[]],['New Member','#7f8c8d',[]],['Muted','#555555',[]],['Bots','#5865f2',[]]], cats:[['البداية','welcome rules announcements roblox-profile game-updates'],['الألعاب','general-roblox brookhaven blox-fruits adopt-me arsenal tower-defense other-games trade-chat looking-for-players'],['صناعة الألعاب','game-development building scripting bug-reports testing developer-showcase'],['الفعاليات','events event-registration winners'],['الدعم والإدارة','support scam-reports appeals staff-chat moderation-logs'],['الفويسات','Lobby Roblox-1 Roblox-2 Trading Developers Events Staff-Room']]},
 {id:'valorant-competitive',name:'Valorant والتنافس',category:'الألعاب',plan:'premium',icon:'🎯',description:'فرق تنافسية وتدريب وبطولات ونتائج.',roles:[['Competitive Director','#8e44ad',[]],['Tournament Manager','#c0392b',[]],['Team Captain','#d35400',[]],['Coach','#2980b9',[]],['Analyst','#16a085',[]],['Player','#3498db',[]],['Substitute','#95a5a6',[]],['Recruit','#7f8c8d',[]],['VIP','#f1c40f',[]],['Member','#bdc3c7',[]],['Muted','#555555',[]],['Bots','#5865f2',[]]], cats:[['البداية','welcome rules announcements valorant-news rank-verification'],['اللاعبون','general looking-for-team ranked-queue agent-discussion maps-and-strategies clips patch-notes'],['الفرق','team-recruitment team-rosters scrim-schedule match-planning team-results'],['البطولات','tournament-announcements registration brackets match-results disputes'],['الإدارة','staff-chat team-review tournament-staff player-reports moderation-logs'],['الفويسات','Lobby Ranked-Duo Ranked-Squad Team-Alpha Team-Bravo Tournament-Room Coaching Staff-Room']]},
 {id:'digital-services',name:'الخدمات الرقمية',category:'المتاجر والأعمال',plan:'premium',icon:'💻',description:'بيع الخدمات والطلبات والدعم مع فصل بيانات العملاء عن الفريق.',roles:[['Business Manager','#8e44ad',[]],['Technical Manager','#2980b9',[]],['Sales Manager','#c0392b',[]],['Support Lead','#16a085',[]],['Support Agent','#3498db',[]],['Developer','#1abc9c',[]],['Designer','#e67e22',[]],['Sales Agent','#d35400',[]],['Verified Buyer','#2ecc71',[]],['VIP Buyer','#f1c40f',[]],['Buyer','#95a5a6',[]],['Visitor','#7f8c8d',[]],['Muted','#555555',[]],['Bots','#5865f2',[]]], cats:[['المتجر','welcome rules announcements service-list pricing how-to-buy payment-methods delivery-policy'],['الخدمات','digital-products design-services development-services subscriptions custom-orders offers portfolio customer-reviews'],['الطلبات والدعم','new-request order-status delivery-support refund-policy complaints open-ticket'],['الفريق الخاص','sales-team technical-team design-team work-queue staff-announcements staff-logs'],['الفويسات','Sales-Consultation Technical-Support Design-Meeting Team-Meeting']]},
 {id:'design-store',name:'متجر التصاميم',category:'المتاجر والأعمال',plan:'premium',icon:'🎨',description:'طلبات تصاميم ومراجعة جودة وإدارة فريق المصممين.',roles:[['Creative Director','#8e44ad',[]],['Store Manager','#c0392b',[]],['Senior Designer','#2980b9',[]],['Designer','#3498db',[]],['Animator','#16a085',[]],['Video Editor','#1abc9c',[]],['Sales Team','#d35400',[]],['Support Team','#e67e22',[]],['Verified Customer','#2ecc71',[]],['VIP Customer','#f1c40f',[]],['Customer','#95a5a6',[]],['Muted','#555555',[]],['Bots','#5865f2',[]]], cats:[['المتجر','welcome rules announcements design-catalog logo-designs banners profile-icons animated-designs video-editing custom-designs pricing offers'],['الطلبات','order-instructions submit-design-request order-progress completed-work customer-reviews complaints support-tickets'],['المصممون','designer-chat creative-discussion design-references work-queue quality-review'],['الإدارة الخاصة','staff-chat orders-management customer-cases staff-logs'],['الفويسات','Customer-Consultation Design-Review Designers-Room Management-Room']]}
];
for (const spec of specialistTemplates) {
 const roles = [role('Owner','#e74c3c',['Administrator']), role('Co Owner','#c0392b',['ManageGuild','ManageChannels','ManageRoles']), ...spec.roles.map(([n,c,p])=>role(n,c,p)), role('Bots','#5865f2',[])];
 const cats = spec.cats.map(([label, names])=>{
   const isPrivate = /سرية|خاص|القيادة|الإدارة/.test(label);
   const channels = names.split(/\s+/).map(n=> /^(AFK|Lobby|Dispatch|Patrol-|Squad-|Team-|Medical-Team|Emergency-|Training-Room|Command-|Interview|General$|Staff-Room|War-Room|Leadership$|Diplomacy$|Roblox-|Trading$|Developers$|Events$|Ranked-|Tournament-Room|Coaching$|Sales-Consultation|Technical-Support|Design-Meeting|Team-Meeting|Customer-Consultation|Design-Review|Designers-Room|Management-Room)/i.test(n) ? voice(n) : text(n));
   if (isPrivate) return cat(label, channels, Object.fromEntries(['Owner','Co Owner',...spec.roles.filter(([n])=>/Manager|Director|Chief|Leader|Commissioner|Captain|Command|Support Lead|Creative|Store Manager|Staff|Admin/i.test(n)).map(([n])=>n)].map(n=>[n,['ViewChannel']])));
   return cat(label, channels);
 });
 templates.push({id:spec.id,name:spec.name,category:spec.category,plan:spec.plan,icon:spec.icon,description:spec.description,features:['رتب متخصصة','قنوات نصية وفويسات','أقسام خاصة بصلاحيات'],roles,categories:cats});
}


// Expanded shared systems. Each template receives only relevant shared modules;
// private categories use role overwrites rather than relying on channel names.
const toText = names => names.trim().split(/\s+/).map(n => text(n));
const toVoice = names => names.trim().split(/\s+/).map(n => voice(n));
const hasRole = (t,n) => t.roles.some(r=>r.name.toLowerCase()===n.toLowerCase());
const ensureRole = (t,n,color='#7f8c8d',permissions=[]) => { if(!hasRole(t,n)) t.roles.push(role(n,color,permissions)); };
const staffNames = ['Owner','Co Owner','Management','Admin','Moderator','Manager','Server Manager','Head Admin','Support Manager','Support','Support Agent','Ticket Team','Application Reviewer','Event Manager','Partnership Manager','Log Viewer'];
const privateAccess = t => Object.fromEntries(staffNames.filter(n=>hasRole(t,n)).map(n=>[n,['ViewChannel']]));
const addCat = (t,name,channels,priv=false) => { if(!t.categories.some(c=>c.name===name)) t.categories.push(cat(name,channels,priv?privateAccess(t):{})); };
for (const t of templates) {
  // Shared roles are data definitions only; dangerous Administrator is never granted automatically here.
  ensureRole(t,'Co Owner','#c0392b',['ManageChannels','ManageRoles']);
  ensureRole(t,'Management','#8e44ad',['ManageMessages','ViewAuditLog']);
  ensureRole(t,'Senior Moderator','#2980b9',['ManageMessages']);
  ensureRole(t,'Support Agent','#16a085',['ManageMessages']);
  ensureRole(t,'Ticket Team','#1abc9c',[]);
  ensureRole(t,'Application Reviewer','#f39c12',[]);
  ensureRole(t,'Log Viewer','#95a5a6',[]);
  ensureRole(t,'Muted','#555555',[]);
  addCat(t,'🔐・الإدارة العليا',toText('owner-room co-owner-room executive-management management-chat management-announcements management-decisions management-meetings management-planning staff-chat staff-announcements staff-discussion staff-suggestions staff-requests staff-complaints staff-reports staff-attendance staff-leave-requests staff-promotions staff-demotions staff-evaluations staff-training staff-recruitment staff-interviews staff-accepted staff-rejected staff-private-meetings staff-activity staff-performance staff-archive'),true);
  addCat(t,'⚠️・العقوبات والتحذيرات',toText('warning-system warning-logs active-warnings expired-warnings warning-appeals verbal-warnings official-warnings staff-warnings staff-strikes member-strikes timeout-logs mute-logs kick-logs ban-logs unban-logs blacklist-logs punishment-appeals punishment-review disciplinary-reports evidence-submissions case-review repeat-offenders moderation-decisions'),true);
  addCat(t,'📑・السجلات Logs',toText('member-join-logs member-leave-logs member-kick-logs member-ban-logs member-unban-logs member-timeout-logs member-warning-logs member-nickname-logs member-role-add-logs member-role-remove-logs message-delete-logs message-edit-logs bulk-delete-logs channel-create-logs channel-delete-logs channel-update-logs category-logs role-create-logs role-delete-logs role-update-logs permission-change-logs voice-join-logs voice-leave-logs voice-move-logs voice-mute-logs voice-deafen-logs invite-logs ticket-logs application-logs bot-command-logs security-logs template-logs system-errors'),true);
  const shopLike=/store|shop|design|digital|support/.test(t.id+' '+t.category);
  const roleplay=/fivem|police|ems|gang/.test(t.id+' '+t.name);
  const eventLike=/event|gaming|valorant|minecraft|roblox|community|large/.test(t.id+' '+t.category);
  const ticketNames = shopLike ? 'ticket-panel ticket-information ticket-rules ticket-announcements ticket-staff-chat ticket-staff-requests ticket-escalation ticket-reviews ticket-transcripts ticket-statistics ticket-logs' : 'ticket-panel ticket-information ticket-rules ticket-announcements ticket-staff-chat ticket-staff-requests ticket-escalation ticket-reviews ticket-transcripts ticket-statistics ticket-logs';
  addCat(t,'🎫・مركز التكتات',toText(ticketNames),true);
  addCat(t,'📝・التقديمات والقبول',toText('applications-panel applications-information applications-open applications-review applications-interviews applications-accepted applications-rejected applications-pending applications-archive applications-logs staff-recruitment partnership-applications event-staff-applications creator-applications department-applications'),true);
  addCat(t,'👥・خدمات الأعضاء',toText('member-support member-questions member-reports member-appeals member-feedback member-suggestions member-polls member-activities member-achievements member-events member-roles-info member-verification member-requests member-help member-guides member-faq'));
  addCat(t,'💡・الاقتراحات والتصويت',toText('suggestions-panel suggestions-pending suggestions-approved suggestions-rejected suggestions-implemented suggestions-discussion suggestions-logs community-polls staff-polls event-polls'),true);
  if(eventLike || roleplay) addCat(t,'🏆・الفعاليات والمسابقات',toText('event-announcements event-calendar event-registration event-questions event-planning event-staff-chat event-staff-logs event-participants event-teams event-brackets event-results event-winners event-prizes event-disputes event-reports event-gallery event-feedback'),true);
  addCat(t,'🤝・الشراكات والعلاقات',toText('partnership-info partnership-rules partnership-requests partnership-review partnership-announcements partner-server-info partner-chat partnership-logs public-relations advertising-requests'),true);
  addCat(t,'🔊・الفويسات الإضافية',toVoice('Waiting-Room General-Voice-1 General-Voice-2 General-Voice-3 Gaming-Room-1 Gaming-Room-2 Gaming-Room-3 Team-Voice-1 Team-Voice-2 Team-Voice-3 Event-Voice Study-Room Music-Room Support-Room Interview-Room Staff-Room Management-Room Private-Meeting AFK'));
  if(eventLike) addCat(t,'📈・المستويات والاقتصاد',toText('economy-guide currency-information economy-chat daily-rewards-info economy-leaderboards level-information level-leaderboards member-achievements reward-information economy-logs'),true);
  if(roleplay) addCat(t,'🚨・الأقسام الميدانية',toText('department-announcements duty-roster shift-reports operation-planning incident-reports evidence-room training-schedule promotion-requests leave-requests'),true);
  if(shopLike) addCat(t,'🛍️・الطلبات والعملاء',toText('store-catalog products pricing payment-methods delivery-information how-to-order new-orders order-status order-tracking completed-orders customer-reviews refund-requests replacement-requests order-management inventory finance-reports customer-issues'),true);
  if(t.id==='programming' || /program/.test(t.id+' '+t.name)) addCat(t,'💻・المطورون',toText('frontend backend apis code-review bug-reports project-showcase collaboration looking-for-developers open-source dev-team project-planning technical-decisions'),true);
  // Template metadata used by preview/UI; handlers must not claim modules are active unless bot integrations exist.
  t.version = 2;
  t.modules = { moderation:true, logs:true, applications:true, suggestions:true, tickets:'channel-structure-only', events:eventLike?'channel-structure-only':false, economy:eventLike?'requires-existing-bot-module':false };
}

const byId = new Map(templates.map(t => [t.id, t]));
function cloneTemplate(id) { const t = byId.get(String(id)); return t ? JSON.parse(JSON.stringify(t)) : null; }
module.exports = { templates, cloneTemplate };
